// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface AuditChainEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.AuditChainEntry)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string event_type = 2;</code>
   * @return The eventType.
   */
  java.lang.String getEventType();
  /**
   * <code>string event_type = 2;</code>
   * @return The bytes for eventType.
   */
  com.google.protobuf.ByteString
      getEventTypeBytes();

  /**
   * <code>string actor_id = 3;</code>
   * @return The actorId.
   */
  java.lang.String getActorId();
  /**
   * <code>string actor_id = 3;</code>
   * @return The bytes for actorId.
   */
  com.google.protobuf.ByteString
      getActorIdBytes();

  /**
   * <code>string entity_type = 4;</code>
   * @return The entityType.
   */
  java.lang.String getEntityType();
  /**
   * <code>string entity_type = 4;</code>
   * @return The bytes for entityType.
   */
  com.google.protobuf.ByteString
      getEntityTypeBytes();

  /**
   * <code>string entity_id = 5;</code>
   * @return The entityId.
   */
  java.lang.String getEntityId();
  /**
   * <code>string entity_id = 5;</code>
   * @return The bytes for entityId.
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>uint64 timestamp = 6;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>bytes prev_hash = 7;</code>
   * @return The prevHash.
   */
  com.google.protobuf.ByteString getPrevHash();

  /**
   * <code>bytes event_hash = 8;</code>
   * @return The eventHash.
   */
  com.google.protobuf.ByteString getEventHash();

  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 9;</code>
   * @return Whether the vectorClock field is set.
   */
  boolean hasVectorClock();
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 9;</code>
   * @return The vectorClock.
   */
  me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock();
}
