// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface AuthEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.AuthEvent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>.digitaldelta.v1.AuthEventType event_type = 3;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  int getEventTypeValue();
  /**
   * <code>.digitaldelta.v1.AuthEventType event_type = 3;</code>
   * @return The eventType.
   */
  me.zayedbinhasan.digitaldelta.proto.AuthEventType getEventType();

  /**
   * <code>string device_id = 4;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 4;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>uint64 timestamp = 5;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>bytes prev_hash = 6;</code>
   * @return The prevHash.
   */
  com.google.protobuf.ByteString getPrevHash();

  /**
   * <code>bytes event_hash = 7;</code>
   * @return The eventHash.
   */
  com.google.protobuf.ByteString getEventHash();

  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   * @return Whether the vectorClock field is set.
   */
  boolean hasVectorClock();
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   * @return The vectorClock.
   */
  me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock();
}
