// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf enum {@code digitaldelta.v1.AuthEventType}
 */
public enum AuthEventType
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>AUTH_EVENT_TYPE_UNSPECIFIED = 0;</code>
   */
  AUTH_EVENT_TYPE_UNSPECIFIED(0),
  /**
   * <code>LOGIN = 1;</code>
   */
  LOGIN(1),
  /**
   * <code>OTP_VERIFY = 2;</code>
   */
  OTP_VERIFY(2),
  /**
   * <code>KEY_ROTATION = 3;</code>
   */
  KEY_ROTATION(3),
  /**
   * <code>FAILURE = 4;</code>
   */
  FAILURE(4),
  /**
   * <code>PROVISION = 5;</code>
   */
  PROVISION(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>AUTH_EVENT_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int AUTH_EVENT_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>LOGIN = 1;</code>
   */
  public static final int LOGIN_VALUE = 1;
  /**
   * <code>OTP_VERIFY = 2;</code>
   */
  public static final int OTP_VERIFY_VALUE = 2;
  /**
   * <code>KEY_ROTATION = 3;</code>
   */
  public static final int KEY_ROTATION_VALUE = 3;
  /**
   * <code>FAILURE = 4;</code>
   */
  public static final int FAILURE_VALUE = 4;
  /**
   * <code>PROVISION = 5;</code>
   */
  public static final int PROVISION_VALUE = 5;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AuthEventType valueOf(int value) {
    return forNumber(value);
  }

  public static AuthEventType forNumber(int value) {
    switch (value) {
      case 0: return AUTH_EVENT_TYPE_UNSPECIFIED;
      case 1: return LOGIN;
      case 2: return OTP_VERIFY;
      case 3: return KEY_ROTATION;
      case 4: return FAILURE;
      case 5: return PROVISION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AuthEventType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AuthEventType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AuthEventType>() {
          @java.lang.Override
          public AuthEventType findValueByNumber(int number) {
            return AuthEventType.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return AuthEventTypeVerifier.INSTANCE;
  }

  private static final class AuthEventTypeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new AuthEventTypeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return AuthEventType.forNumber(number) != null;
          }
        };

  private final int value;

  private AuthEventType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:digitaldelta.v1.AuthEventType)
}

