// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.AuthEvent}
 */
public  final class AuthEvent extends
    com.google.protobuf.GeneratedMessageLite<
        AuthEvent, AuthEvent.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.AuthEvent)
    AuthEventOrBuilder {
  private AuthEvent() {
    eventId_ = "";
    userId_ = "";
    deviceId_ = "";
    prevHash_ = com.google.protobuf.ByteString.EMPTY;
    eventHash_ = com.google.protobuf.ByteString.EMPTY;
  }
  private int bitField0_;
  public static final int EVENT_ID_FIELD_NUMBER = 1;
  private java.lang.String eventId_;
  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  @java.lang.Override
  public java.lang.String getEventId() {
    return eventId_;
  }
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(eventId_);
  }
  /**
   * <code>string event_id = 1;</code>
   * @param value The eventId to set.
   */
  private void setEventId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    eventId_ = value;
  }
  /**
   * <code>string event_id = 1;</code>
   */
  private void clearEventId() {

    eventId_ = getDefaultInstance().getEventId();
  }
  /**
   * <code>string event_id = 1;</code>
   * @param value The bytes for eventId to set.
   */
  private void setEventIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    eventId_ = value.toStringUtf8();

  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  private java.lang.String userId_;
  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    return userId_;
  }
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userId_);
  }
  /**
   * <code>string user_id = 2;</code>
   * @param value The userId to set.
   */
  private void setUserId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    userId_ = value;
  }
  /**
   * <code>string user_id = 2;</code>
   */
  private void clearUserId() {

    userId_ = getDefaultInstance().getUserId();
  }
  /**
   * <code>string user_id = 2;</code>
   * @param value The bytes for userId to set.
   */
  private void setUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userId_ = value.toStringUtf8();

  }

  public static final int EVENT_TYPE_FIELD_NUMBER = 3;
  private int eventType_;
  /**
   * <code>.digitaldelta.v1.AuthEventType event_type = 3;</code>
   * @return The enum numeric value on the wire for eventType.
   */
  @java.lang.Override
  public int getEventTypeValue() {
    return eventType_;
  }
  /**
   * <code>.digitaldelta.v1.AuthEventType event_type = 3;</code>
   * @return The eventType.
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.AuthEventType getEventType() {
    me.zayedbinhasan.digitaldelta.proto.AuthEventType result = me.zayedbinhasan.digitaldelta.proto.AuthEventType.forNumber(eventType_);
    return result == null ? me.zayedbinhasan.digitaldelta.proto.AuthEventType.UNRECOGNIZED : result;
  }
  /**
   * <code>.digitaldelta.v1.AuthEventType event_type = 3;</code>
   * @param value The enum numeric value on the wire for eventType to set.
   */
  private void setEventTypeValue(int value) {
      eventType_ = value;
  }
  /**
   * <code>.digitaldelta.v1.AuthEventType event_type = 3;</code>
   * @param value The eventType to set.
   */
  private void setEventType(me.zayedbinhasan.digitaldelta.proto.AuthEventType value) {
    eventType_ = value.getNumber();

  }
  /**
   * <code>.digitaldelta.v1.AuthEventType event_type = 3;</code>
   */
  private void clearEventType() {

    eventType_ = 0;
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 4;
  private java.lang.String deviceId_;
  /**
   * <code>string device_id = 4;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    return deviceId_;
  }
  /**
   * <code>string device_id = 4;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
  }
  /**
   * <code>string device_id = 4;</code>
   * @param value The deviceId to set.
   */
  private void setDeviceId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    deviceId_ = value;
  }
  /**
   * <code>string device_id = 4;</code>
   */
  private void clearDeviceId() {

    deviceId_ = getDefaultInstance().getDeviceId();
  }
  /**
   * <code>string device_id = 4;</code>
   * @param value The bytes for deviceId to set.
   */
  private void setDeviceIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    deviceId_ = value.toStringUtf8();

  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 5;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }
  /**
   * <code>uint64 timestamp = 5;</code>
   * @param value The timestamp to set.
   */
  private void setTimestamp(long value) {
    
    timestamp_ = value;
  }
  /**
   * <code>uint64 timestamp = 5;</code>
   */
  private void clearTimestamp() {

    timestamp_ = 0L;
  }

  public static final int PREV_HASH_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString prevHash_;
  /**
   * <code>bytes prev_hash = 6;</code>
   * @return The prevHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPrevHash() {
    return prevHash_;
  }
  /**
   * <code>bytes prev_hash = 6;</code>
   * @param value The prevHash to set.
   */
  private void setPrevHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    prevHash_ = value;
  }
  /**
   * <code>bytes prev_hash = 6;</code>
   */
  private void clearPrevHash() {

    prevHash_ = getDefaultInstance().getPrevHash();
  }

  public static final int EVENT_HASH_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString eventHash_;
  /**
   * <code>bytes event_hash = 7;</code>
   * @return The eventHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEventHash() {
    return eventHash_;
  }
  /**
   * <code>bytes event_hash = 7;</code>
   * @param value The eventHash to set.
   */
  private void setEventHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    eventHash_ = value;
  }
  /**
   * <code>bytes event_hash = 7;</code>
   */
  private void clearEventHash() {

    eventHash_ = getDefaultInstance().getEventHash();
  }

  public static final int VECTOR_CLOCK_FIELD_NUMBER = 8;
  private me.zayedbinhasan.digitaldelta.proto.VectorClock vectorClock_;
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  @java.lang.Override
  public boolean hasVectorClock() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
    return vectorClock_ == null ? me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance() : vectorClock_;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  private void setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  vectorClock_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  if (vectorClock_ != null &&
        vectorClock_ != me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance()) {
      vectorClock_ =
        me.zayedbinhasan.digitaldelta.proto.VectorClock.newBuilder(vectorClock_).mergeFrom(value).buildPartial();
    } else {
      vectorClock_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  private void clearVectorClock() {  vectorClock_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.AuthEvent prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.AuthEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.AuthEvent, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.AuthEvent)
      me.zayedbinhasan.digitaldelta.proto.AuthEventOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.AuthEvent.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string event_id = 1;</code>
     * @return The eventId.
     */
    @java.lang.Override
    public java.lang.String getEventId() {
      return instance.getEventId();
    }
    /**
     * <code>string event_id = 1;</code>
     * @return The bytes for eventId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      return instance.getEventIdBytes();
    }
    /**
     * <code>string event_id = 1;</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(
        java.lang.String value) {
      copyOnWrite();
      instance.setEventId(value);
      return this;
    }
    /**
     * <code>string event_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      copyOnWrite();
      instance.clearEventId();
      return this;
    }
    /**
     * <code>string event_id = 1;</code>
     * @param value The bytes for eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEventIdBytes(value);
      return this;
    }

    /**
     * <code>string user_id = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      return instance.getUserId();
    }
    /**
     * <code>string user_id = 2;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return instance.getUserIdBytes();
    }
    /**
     * <code>string user_id = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserId(value);
      return this;
    }
    /**
     * <code>string user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      copyOnWrite();
      instance.clearUserId();
      return this;
    }
    /**
     * <code>string user_id = 2;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIdBytes(value);
      return this;
    }

    /**
     * <code>.digitaldelta.v1.AuthEventType event_type = 3;</code>
     * @return The enum numeric value on the wire for eventType.
     */
    @java.lang.Override
    public int getEventTypeValue() {
      return instance.getEventTypeValue();
    }
    /**
     * <code>.digitaldelta.v1.AuthEventType event_type = 3;</code>
     * @param value The eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventTypeValue(int value) {
      copyOnWrite();
      instance.setEventTypeValue(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.AuthEventType event_type = 3;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.AuthEventType getEventType() {
      return instance.getEventType();
    }
    /**
     * <code>.digitaldelta.v1.AuthEventType event_type = 3;</code>
     * @param value The enum numeric value on the wire for eventType to set.
     * @return This builder for chaining.
     */
    public Builder setEventType(me.zayedbinhasan.digitaldelta.proto.AuthEventType value) {
      copyOnWrite();
      instance.setEventType(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.AuthEventType event_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventType() {
      copyOnWrite();
      instance.clearEventType();
      return this;
    }

    /**
     * <code>string device_id = 4;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return instance.getDeviceId();
    }
    /**
     * <code>string device_id = 4;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return instance.getDeviceIdBytes();
    }
    /**
     * <code>string device_id = 4;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDeviceId(value);
      return this;
    }
    /**
     * <code>string device_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      copyOnWrite();
      instance.clearDeviceId();
      return this;
    }
    /**
     * <code>string device_id = 4;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceIdBytes(value);
      return this;
    }

    /**
     * <code>uint64 timestamp = 5;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return instance.getTimestamp();
    }
    /**
     * <code>uint64 timestamp = 5;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      copyOnWrite();
      instance.setTimestamp(value);
      return this;
    }
    /**
     * <code>uint64 timestamp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      copyOnWrite();
      instance.clearTimestamp();
      return this;
    }

    /**
     * <code>bytes prev_hash = 6;</code>
     * @return The prevHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPrevHash() {
      return instance.getPrevHash();
    }
    /**
     * <code>bytes prev_hash = 6;</code>
     * @param value The prevHash to set.
     * @return This builder for chaining.
     */
    public Builder setPrevHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPrevHash(value);
      return this;
    }
    /**
     * <code>bytes prev_hash = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrevHash() {
      copyOnWrite();
      instance.clearPrevHash();
      return this;
    }

    /**
     * <code>bytes event_hash = 7;</code>
     * @return The eventHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEventHash() {
      return instance.getEventHash();
    }
    /**
     * <code>bytes event_hash = 7;</code>
     * @param value The eventHash to set.
     * @return This builder for chaining.
     */
    public Builder setEventHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEventHash(value);
      return this;
    }
    /**
     * <code>bytes event_hash = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventHash() {
      copyOnWrite();
      instance.clearEventHash();
      return this;
    }

    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    @java.lang.Override
    public boolean hasVectorClock() {
      return instance.hasVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
      return instance.getVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    public Builder setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.setVectorClock(value);
      return this;
      }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    public Builder setVectorClock(
        me.zayedbinhasan.digitaldelta.proto.VectorClock.Builder builderForValue) {
      copyOnWrite();
      instance.setVectorClock(builderForValue.build());
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    public Builder mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.mergeVectorClock(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    public Builder clearVectorClock() {  copyOnWrite();
      instance.clearVectorClock();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.AuthEvent)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.AuthEvent();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "eventId_",
            "userId_",
            "eventType_",
            "deviceId_",
            "timestamp_",
            "prevHash_",
            "eventHash_",
            "vectorClock_",
          };
          java.lang.String info =
              "\u0000\b\u0000\u0001\u0001\b\b\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\f" +
              "\u0004\u0208\u0005\u0003\u0006\n\u0007\n\b\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.AuthEvent> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.AuthEvent.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.AuthEvent>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.AuthEvent)
  private static final me.zayedbinhasan.digitaldelta.proto.AuthEvent DEFAULT_INSTANCE;
  static {
    AuthEvent defaultInstance = new AuthEvent();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AuthEvent.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.AuthEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AuthEvent> PARSER;

  public static com.google.protobuf.Parser<AuthEvent> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

