// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: delivery.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf enum {@code digitaldelta.v1.ConflictResolution}
 */
public enum ConflictResolution
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>CONFLICT_RESOLUTION_UNSPECIFIED = 0;</code>
   */
  CONFLICT_RESOLUTION_UNSPECIFIED(0),
  /**
   * <code>AUTO_LWW = 1;</code>
   */
  AUTO_LWW(1),
  /**
   * <code>AUTO_ADDITIVE = 2;</code>
   */
  AUTO_ADDITIVE(2),
  /**
   * <code>MANUAL_REQUIRED = 3;</code>
   */
  MANUAL_REQUIRED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CONFLICT_RESOLUTION_UNSPECIFIED = 0;</code>
   */
  public static final int CONFLICT_RESOLUTION_UNSPECIFIED_VALUE = 0;
  /**
   * <code>AUTO_LWW = 1;</code>
   */
  public static final int AUTO_LWW_VALUE = 1;
  /**
   * <code>AUTO_ADDITIVE = 2;</code>
   */
  public static final int AUTO_ADDITIVE_VALUE = 2;
  /**
   * <code>MANUAL_REQUIRED = 3;</code>
   */
  public static final int MANUAL_REQUIRED_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ConflictResolution valueOf(int value) {
    return forNumber(value);
  }

  public static ConflictResolution forNumber(int value) {
    switch (value) {
      case 0: return CONFLICT_RESOLUTION_UNSPECIFIED;
      case 1: return AUTO_LWW;
      case 2: return AUTO_ADDITIVE;
      case 3: return MANUAL_REQUIRED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ConflictResolution>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ConflictResolution> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ConflictResolution>() {
          @java.lang.Override
          public ConflictResolution findValueByNumber(int number) {
            return ConflictResolution.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return ConflictResolutionVerifier.INSTANCE;
  }

  private static final class ConflictResolutionVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ConflictResolutionVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return ConflictResolution.forNumber(number) != null;
          }
        };

  private final int value;

  private ConflictResolution(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:digitaldelta.v1.ConflictResolution)
}

