// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: delivery.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.DeliveryConflict}
 */
public  final class DeliveryConflict extends
    com.google.protobuf.GeneratedMessageLite<
        DeliveryConflict, DeliveryConflict.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.DeliveryConflict)
    DeliveryConflictOrBuilder {
  private DeliveryConflict() {
    conflictId_ = "";
    taskId_ = "";
    localMutationId_ = "";
    remoteMutationId_ = "";
    notes_ = "";
  }
  public static final int CONFLICT_ID_FIELD_NUMBER = 1;
  private java.lang.String conflictId_;
  /**
   * <code>string conflict_id = 1;</code>
   * @return The conflictId.
   */
  @java.lang.Override
  public java.lang.String getConflictId() {
    return conflictId_;
  }
  /**
   * <code>string conflict_id = 1;</code>
   * @return The bytes for conflictId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConflictIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(conflictId_);
  }
  /**
   * <code>string conflict_id = 1;</code>
   * @param value The conflictId to set.
   */
  private void setConflictId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    conflictId_ = value;
  }
  /**
   * <code>string conflict_id = 1;</code>
   */
  private void clearConflictId() {

    conflictId_ = getDefaultInstance().getConflictId();
  }
  /**
   * <code>string conflict_id = 1;</code>
   * @param value The bytes for conflictId to set.
   */
  private void setConflictIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    conflictId_ = value.toStringUtf8();

  }

  public static final int TASK_ID_FIELD_NUMBER = 2;
  private java.lang.String taskId_;
  /**
   * <code>string task_id = 2;</code>
   * @return The taskId.
   */
  @java.lang.Override
  public java.lang.String getTaskId() {
    return taskId_;
  }
  /**
   * <code>string task_id = 2;</code>
   * @return The bytes for taskId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(taskId_);
  }
  /**
   * <code>string task_id = 2;</code>
   * @param value The taskId to set.
   */
  private void setTaskId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    taskId_ = value;
  }
  /**
   * <code>string task_id = 2;</code>
   */
  private void clearTaskId() {

    taskId_ = getDefaultInstance().getTaskId();
  }
  /**
   * <code>string task_id = 2;</code>
   * @param value The bytes for taskId to set.
   */
  private void setTaskIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    taskId_ = value.toStringUtf8();

  }

  public static final int LOCAL_MUTATION_ID_FIELD_NUMBER = 3;
  private java.lang.String localMutationId_;
  /**
   * <code>string local_mutation_id = 3;</code>
   * @return The localMutationId.
   */
  @java.lang.Override
  public java.lang.String getLocalMutationId() {
    return localMutationId_;
  }
  /**
   * <code>string local_mutation_id = 3;</code>
   * @return The bytes for localMutationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocalMutationIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(localMutationId_);
  }
  /**
   * <code>string local_mutation_id = 3;</code>
   * @param value The localMutationId to set.
   */
  private void setLocalMutationId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    localMutationId_ = value;
  }
  /**
   * <code>string local_mutation_id = 3;</code>
   */
  private void clearLocalMutationId() {

    localMutationId_ = getDefaultInstance().getLocalMutationId();
  }
  /**
   * <code>string local_mutation_id = 3;</code>
   * @param value The bytes for localMutationId to set.
   */
  private void setLocalMutationIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    localMutationId_ = value.toStringUtf8();

  }

  public static final int REMOTE_MUTATION_ID_FIELD_NUMBER = 4;
  private java.lang.String remoteMutationId_;
  /**
   * <code>string remote_mutation_id = 4;</code>
   * @return The remoteMutationId.
   */
  @java.lang.Override
  public java.lang.String getRemoteMutationId() {
    return remoteMutationId_;
  }
  /**
   * <code>string remote_mutation_id = 4;</code>
   * @return The bytes for remoteMutationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRemoteMutationIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(remoteMutationId_);
  }
  /**
   * <code>string remote_mutation_id = 4;</code>
   * @param value The remoteMutationId to set.
   */
  private void setRemoteMutationId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    remoteMutationId_ = value;
  }
  /**
   * <code>string remote_mutation_id = 4;</code>
   */
  private void clearRemoteMutationId() {

    remoteMutationId_ = getDefaultInstance().getRemoteMutationId();
  }
  /**
   * <code>string remote_mutation_id = 4;</code>
   * @param value The bytes for remoteMutationId to set.
   */
  private void setRemoteMutationIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    remoteMutationId_ = value.toStringUtf8();

  }

  public static final int RESOLUTION_FIELD_NUMBER = 5;
  private int resolution_;
  /**
   * <code>.digitaldelta.v1.ConflictResolution resolution = 5;</code>
   * @return The enum numeric value on the wire for resolution.
   */
  @java.lang.Override
  public int getResolutionValue() {
    return resolution_;
  }
  /**
   * <code>.digitaldelta.v1.ConflictResolution resolution = 5;</code>
   * @return The resolution.
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.ConflictResolution getResolution() {
    me.zayedbinhasan.digitaldelta.proto.ConflictResolution result = me.zayedbinhasan.digitaldelta.proto.ConflictResolution.forNumber(resolution_);
    return result == null ? me.zayedbinhasan.digitaldelta.proto.ConflictResolution.UNRECOGNIZED : result;
  }
  /**
   * <code>.digitaldelta.v1.ConflictResolution resolution = 5;</code>
   * @param value The enum numeric value on the wire for resolution to set.
   */
  private void setResolutionValue(int value) {
      resolution_ = value;
  }
  /**
   * <code>.digitaldelta.v1.ConflictResolution resolution = 5;</code>
   * @param value The resolution to set.
   */
  private void setResolution(me.zayedbinhasan.digitaldelta.proto.ConflictResolution value) {
    resolution_ = value.getNumber();

  }
  /**
   * <code>.digitaldelta.v1.ConflictResolution resolution = 5;</code>
   */
  private void clearResolution() {

    resolution_ = 0;
  }

  public static final int NOTES_FIELD_NUMBER = 6;
  private java.lang.String notes_;
  /**
   * <code>string notes = 6;</code>
   * @return The notes.
   */
  @java.lang.Override
  public java.lang.String getNotes() {
    return notes_;
  }
  /**
   * <code>string notes = 6;</code>
   * @return The bytes for notes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNotesBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(notes_);
  }
  /**
   * <code>string notes = 6;</code>
   * @param value The notes to set.
   */
  private void setNotes(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    notes_ = value;
  }
  /**
   * <code>string notes = 6;</code>
   */
  private void clearNotes() {

    notes_ = getDefaultInstance().getNotes();
  }
  /**
   * <code>string notes = 6;</code>
   * @param value The bytes for notes to set.
   */
  private void setNotesBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    notes_ = value.toStringUtf8();

  }

  public static final int DETECTED_AT_FIELD_NUMBER = 7;
  private long detectedAt_;
  /**
   * <code>uint64 detected_at = 7;</code>
   * @return The detectedAt.
   */
  @java.lang.Override
  public long getDetectedAt() {
    return detectedAt_;
  }
  /**
   * <code>uint64 detected_at = 7;</code>
   * @param value The detectedAt to set.
   */
  private void setDetectedAt(long value) {
    
    detectedAt_ = value;
  }
  /**
   * <code>uint64 detected_at = 7;</code>
   */
  private void clearDetectedAt() {

    detectedAt_ = 0L;
  }

  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.DeliveryConflict prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.DeliveryConflict}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.DeliveryConflict, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.DeliveryConflict)
      me.zayedbinhasan.digitaldelta.proto.DeliveryConflictOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.DeliveryConflict.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string conflict_id = 1;</code>
     * @return The conflictId.
     */
    @java.lang.Override
    public java.lang.String getConflictId() {
      return instance.getConflictId();
    }
    /**
     * <code>string conflict_id = 1;</code>
     * @return The bytes for conflictId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConflictIdBytes() {
      return instance.getConflictIdBytes();
    }
    /**
     * <code>string conflict_id = 1;</code>
     * @param value The conflictId to set.
     * @return This builder for chaining.
     */
    public Builder setConflictId(
        java.lang.String value) {
      copyOnWrite();
      instance.setConflictId(value);
      return this;
    }
    /**
     * <code>string conflict_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConflictId() {
      copyOnWrite();
      instance.clearConflictId();
      return this;
    }
    /**
     * <code>string conflict_id = 1;</code>
     * @param value The bytes for conflictId to set.
     * @return This builder for chaining.
     */
    public Builder setConflictIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setConflictIdBytes(value);
      return this;
    }

    /**
     * <code>string task_id = 2;</code>
     * @return The taskId.
     */
    @java.lang.Override
    public java.lang.String getTaskId() {
      return instance.getTaskId();
    }
    /**
     * <code>string task_id = 2;</code>
     * @return The bytes for taskId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      return instance.getTaskIdBytes();
    }
    /**
     * <code>string task_id = 2;</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(
        java.lang.String value) {
      copyOnWrite();
      instance.setTaskId(value);
      return this;
    }
    /**
     * <code>string task_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      copyOnWrite();
      instance.clearTaskId();
      return this;
    }
    /**
     * <code>string task_id = 2;</code>
     * @param value The bytes for taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTaskIdBytes(value);
      return this;
    }

    /**
     * <code>string local_mutation_id = 3;</code>
     * @return The localMutationId.
     */
    @java.lang.Override
    public java.lang.String getLocalMutationId() {
      return instance.getLocalMutationId();
    }
    /**
     * <code>string local_mutation_id = 3;</code>
     * @return The bytes for localMutationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocalMutationIdBytes() {
      return instance.getLocalMutationIdBytes();
    }
    /**
     * <code>string local_mutation_id = 3;</code>
     * @param value The localMutationId to set.
     * @return This builder for chaining.
     */
    public Builder setLocalMutationId(
        java.lang.String value) {
      copyOnWrite();
      instance.setLocalMutationId(value);
      return this;
    }
    /**
     * <code>string local_mutation_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocalMutationId() {
      copyOnWrite();
      instance.clearLocalMutationId();
      return this;
    }
    /**
     * <code>string local_mutation_id = 3;</code>
     * @param value The bytes for localMutationId to set.
     * @return This builder for chaining.
     */
    public Builder setLocalMutationIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLocalMutationIdBytes(value);
      return this;
    }

    /**
     * <code>string remote_mutation_id = 4;</code>
     * @return The remoteMutationId.
     */
    @java.lang.Override
    public java.lang.String getRemoteMutationId() {
      return instance.getRemoteMutationId();
    }
    /**
     * <code>string remote_mutation_id = 4;</code>
     * @return The bytes for remoteMutationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRemoteMutationIdBytes() {
      return instance.getRemoteMutationIdBytes();
    }
    /**
     * <code>string remote_mutation_id = 4;</code>
     * @param value The remoteMutationId to set.
     * @return This builder for chaining.
     */
    public Builder setRemoteMutationId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRemoteMutationId(value);
      return this;
    }
    /**
     * <code>string remote_mutation_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemoteMutationId() {
      copyOnWrite();
      instance.clearRemoteMutationId();
      return this;
    }
    /**
     * <code>string remote_mutation_id = 4;</code>
     * @param value The bytes for remoteMutationId to set.
     * @return This builder for chaining.
     */
    public Builder setRemoteMutationIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRemoteMutationIdBytes(value);
      return this;
    }

    /**
     * <code>.digitaldelta.v1.ConflictResolution resolution = 5;</code>
     * @return The enum numeric value on the wire for resolution.
     */
    @java.lang.Override
    public int getResolutionValue() {
      return instance.getResolutionValue();
    }
    /**
     * <code>.digitaldelta.v1.ConflictResolution resolution = 5;</code>
     * @param value The resolution to set.
     * @return This builder for chaining.
     */
    public Builder setResolutionValue(int value) {
      copyOnWrite();
      instance.setResolutionValue(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.ConflictResolution resolution = 5;</code>
     * @return The resolution.
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.ConflictResolution getResolution() {
      return instance.getResolution();
    }
    /**
     * <code>.digitaldelta.v1.ConflictResolution resolution = 5;</code>
     * @param value The enum numeric value on the wire for resolution to set.
     * @return This builder for chaining.
     */
    public Builder setResolution(me.zayedbinhasan.digitaldelta.proto.ConflictResolution value) {
      copyOnWrite();
      instance.setResolution(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.ConflictResolution resolution = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearResolution() {
      copyOnWrite();
      instance.clearResolution();
      return this;
    }

    /**
     * <code>string notes = 6;</code>
     * @return The notes.
     */
    @java.lang.Override
    public java.lang.String getNotes() {
      return instance.getNotes();
    }
    /**
     * <code>string notes = 6;</code>
     * @return The bytes for notes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNotesBytes() {
      return instance.getNotesBytes();
    }
    /**
     * <code>string notes = 6;</code>
     * @param value The notes to set.
     * @return This builder for chaining.
     */
    public Builder setNotes(
        java.lang.String value) {
      copyOnWrite();
      instance.setNotes(value);
      return this;
    }
    /**
     * <code>string notes = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearNotes() {
      copyOnWrite();
      instance.clearNotes();
      return this;
    }
    /**
     * <code>string notes = 6;</code>
     * @param value The bytes for notes to set.
     * @return This builder for chaining.
     */
    public Builder setNotesBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNotesBytes(value);
      return this;
    }

    /**
     * <code>uint64 detected_at = 7;</code>
     * @return The detectedAt.
     */
    @java.lang.Override
    public long getDetectedAt() {
      return instance.getDetectedAt();
    }
    /**
     * <code>uint64 detected_at = 7;</code>
     * @param value The detectedAt to set.
     * @return This builder for chaining.
     */
    public Builder setDetectedAt(long value) {
      copyOnWrite();
      instance.setDetectedAt(value);
      return this;
    }
    /**
     * <code>uint64 detected_at = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDetectedAt() {
      copyOnWrite();
      instance.clearDetectedAt();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.DeliveryConflict)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.DeliveryConflict();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "conflictId_",
            "taskId_",
            "localMutationId_",
            "remoteMutationId_",
            "resolution_",
            "notes_",
            "detectedAt_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\f\u0006\u0208\u0007\u0003";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.DeliveryConflict> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.DeliveryConflict.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.DeliveryConflict>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.DeliveryConflict)
  private static final me.zayedbinhasan.digitaldelta.proto.DeliveryConflict DEFAULT_INSTANCE;
  static {
    DeliveryConflict defaultInstance = new DeliveryConflict();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DeliveryConflict.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.DeliveryConflict getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DeliveryConflict> PARSER;

  public static com.google.protobuf.Parser<DeliveryConflict> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

