// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: delivery.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.DeliveryTask}
 */
public  final class DeliveryTask extends
    com.google.protobuf.GeneratedMessageLite<
        DeliveryTask, DeliveryTask.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.DeliveryTask)
    DeliveryTaskOrBuilder {
  private DeliveryTask() {
    taskId_ = "";
    supplyId_ = "";
    originId_ = "";
    destinationId_ = "";
    assignedDriverId_ = "";
  }
  private int bitField0_;
  public static final int TASK_ID_FIELD_NUMBER = 1;
  private java.lang.String taskId_;
  /**
   * <code>string task_id = 1;</code>
   * @return The taskId.
   */
  @java.lang.Override
  public java.lang.String getTaskId() {
    return taskId_;
  }
  /**
   * <code>string task_id = 1;</code>
   * @return The bytes for taskId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTaskIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(taskId_);
  }
  /**
   * <code>string task_id = 1;</code>
   * @param value The taskId to set.
   */
  private void setTaskId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    taskId_ = value;
  }
  /**
   * <code>string task_id = 1;</code>
   */
  private void clearTaskId() {

    taskId_ = getDefaultInstance().getTaskId();
  }
  /**
   * <code>string task_id = 1;</code>
   * @param value The bytes for taskId to set.
   */
  private void setTaskIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    taskId_ = value.toStringUtf8();

  }

  public static final int SUPPLY_ID_FIELD_NUMBER = 2;
  private java.lang.String supplyId_;
  /**
   * <code>string supply_id = 2;</code>
   * @return The supplyId.
   */
  @java.lang.Override
  public java.lang.String getSupplyId() {
    return supplyId_;
  }
  /**
   * <code>string supply_id = 2;</code>
   * @return The bytes for supplyId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSupplyIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(supplyId_);
  }
  /**
   * <code>string supply_id = 2;</code>
   * @param value The supplyId to set.
   */
  private void setSupplyId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    supplyId_ = value;
  }
  /**
   * <code>string supply_id = 2;</code>
   */
  private void clearSupplyId() {

    supplyId_ = getDefaultInstance().getSupplyId();
  }
  /**
   * <code>string supply_id = 2;</code>
   * @param value The bytes for supplyId to set.
   */
  private void setSupplyIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    supplyId_ = value.toStringUtf8();

  }

  public static final int QUANTITY_FIELD_NUMBER = 3;
  private int quantity_;
  /**
   * <code>int32 quantity = 3;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }
  /**
   * <code>int32 quantity = 3;</code>
   * @param value The quantity to set.
   */
  private void setQuantity(int value) {
    
    quantity_ = value;
  }
  /**
   * <code>int32 quantity = 3;</code>
   */
  private void clearQuantity() {

    quantity_ = 0;
  }

  public static final int ORIGIN_ID_FIELD_NUMBER = 4;
  private java.lang.String originId_;
  /**
   * <code>string origin_id = 4;</code>
   * @return The originId.
   */
  @java.lang.Override
  public java.lang.String getOriginId() {
    return originId_;
  }
  /**
   * <code>string origin_id = 4;</code>
   * @return The bytes for originId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(originId_);
  }
  /**
   * <code>string origin_id = 4;</code>
   * @param value The originId to set.
   */
  private void setOriginId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    originId_ = value;
  }
  /**
   * <code>string origin_id = 4;</code>
   */
  private void clearOriginId() {

    originId_ = getDefaultInstance().getOriginId();
  }
  /**
   * <code>string origin_id = 4;</code>
   * @param value The bytes for originId to set.
   */
  private void setOriginIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    originId_ = value.toStringUtf8();

  }

  public static final int DESTINATION_ID_FIELD_NUMBER = 5;
  private java.lang.String destinationId_;
  /**
   * <code>string destination_id = 5;</code>
   * @return The destinationId.
   */
  @java.lang.Override
  public java.lang.String getDestinationId() {
    return destinationId_;
  }
  /**
   * <code>string destination_id = 5;</code>
   * @return The bytes for destinationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDestinationIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(destinationId_);
  }
  /**
   * <code>string destination_id = 5;</code>
   * @param value The destinationId to set.
   */
  private void setDestinationId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    destinationId_ = value;
  }
  /**
   * <code>string destination_id = 5;</code>
   */
  private void clearDestinationId() {

    destinationId_ = getDefaultInstance().getDestinationId();
  }
  /**
   * <code>string destination_id = 5;</code>
   * @param value The bytes for destinationId to set.
   */
  private void setDestinationIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    destinationId_ = value.toStringUtf8();

  }

  public static final int PRIORITY_FIELD_NUMBER = 6;
  private int priority_;
  /**
   * <code>.digitaldelta.v1.PriorityTier priority = 6;</code>
   * @return The enum numeric value on the wire for priority.
   */
  @java.lang.Override
  public int getPriorityValue() {
    return priority_;
  }
  /**
   * <code>.digitaldelta.v1.PriorityTier priority = 6;</code>
   * @return The priority.
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.PriorityTier getPriority() {
    me.zayedbinhasan.digitaldelta.proto.PriorityTier result = me.zayedbinhasan.digitaldelta.proto.PriorityTier.forNumber(priority_);
    return result == null ? me.zayedbinhasan.digitaldelta.proto.PriorityTier.UNRECOGNIZED : result;
  }
  /**
   * <code>.digitaldelta.v1.PriorityTier priority = 6;</code>
   * @param value The enum numeric value on the wire for priority to set.
   */
  private void setPriorityValue(int value) {
      priority_ = value;
  }
  /**
   * <code>.digitaldelta.v1.PriorityTier priority = 6;</code>
   * @param value The priority to set.
   */
  private void setPriority(me.zayedbinhasan.digitaldelta.proto.PriorityTier value) {
    priority_ = value.getNumber();

  }
  /**
   * <code>.digitaldelta.v1.PriorityTier priority = 6;</code>
   */
  private void clearPriority() {

    priority_ = 0;
  }

  public static final int DEADLINE_TIMESTAMP_FIELD_NUMBER = 7;
  private long deadlineTimestamp_;
  /**
   * <code>int64 deadline_timestamp = 7;</code>
   * @return The deadlineTimestamp.
   */
  @java.lang.Override
  public long getDeadlineTimestamp() {
    return deadlineTimestamp_;
  }
  /**
   * <code>int64 deadline_timestamp = 7;</code>
   * @param value The deadlineTimestamp to set.
   */
  private void setDeadlineTimestamp(long value) {
    
    deadlineTimestamp_ = value;
  }
  /**
   * <code>int64 deadline_timestamp = 7;</code>
   */
  private void clearDeadlineTimestamp() {

    deadlineTimestamp_ = 0L;
  }

  public static final int ASSIGNED_DRIVER_ID_FIELD_NUMBER = 8;
  private java.lang.String assignedDriverId_;
  /**
   * <code>string assigned_driver_id = 8;</code>
   * @return The assignedDriverId.
   */
  @java.lang.Override
  public java.lang.String getAssignedDriverId() {
    return assignedDriverId_;
  }
  /**
   * <code>string assigned_driver_id = 8;</code>
   * @return The bytes for assignedDriverId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAssignedDriverIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(assignedDriverId_);
  }
  /**
   * <code>string assigned_driver_id = 8;</code>
   * @param value The assignedDriverId to set.
   */
  private void setAssignedDriverId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    assignedDriverId_ = value;
  }
  /**
   * <code>string assigned_driver_id = 8;</code>
   */
  private void clearAssignedDriverId() {

    assignedDriverId_ = getDefaultInstance().getAssignedDriverId();
  }
  /**
   * <code>string assigned_driver_id = 8;</code>
   * @param value The bytes for assignedDriverId to set.
   */
  private void setAssignedDriverIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    assignedDriverId_ = value.toStringUtf8();

  }

  public static final int STATUS_FIELD_NUMBER = 9;
  private int status_;
  /**
   * <code>.digitaldelta.v1.DeliveryStatus status = 9;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.digitaldelta.v1.DeliveryStatus status = 9;</code>
   * @return The status.
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.DeliveryStatus getStatus() {
    me.zayedbinhasan.digitaldelta.proto.DeliveryStatus result = me.zayedbinhasan.digitaldelta.proto.DeliveryStatus.forNumber(status_);
    return result == null ? me.zayedbinhasan.digitaldelta.proto.DeliveryStatus.UNRECOGNIZED : result;
  }
  /**
   * <code>.digitaldelta.v1.DeliveryStatus status = 9;</code>
   * @param value The enum numeric value on the wire for status to set.
   */
  private void setStatusValue(int value) {
      status_ = value;
  }
  /**
   * <code>.digitaldelta.v1.DeliveryStatus status = 9;</code>
   * @param value The status to set.
   */
  private void setStatus(me.zayedbinhasan.digitaldelta.proto.DeliveryStatus value) {
    status_ = value.getNumber();

  }
  /**
   * <code>.digitaldelta.v1.DeliveryStatus status = 9;</code>
   */
  private void clearStatus() {

    status_ = 0;
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 10;
  private long updatedAt_;
  /**
   * <code>uint64 updated_at = 10;</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public long getUpdatedAt() {
    return updatedAt_;
  }
  /**
   * <code>uint64 updated_at = 10;</code>
   * @param value The updatedAt to set.
   */
  private void setUpdatedAt(long value) {
    
    updatedAt_ = value;
  }
  /**
   * <code>uint64 updated_at = 10;</code>
   */
  private void clearUpdatedAt() {

    updatedAt_ = 0L;
  }

  public static final int VECTOR_CLOCK_FIELD_NUMBER = 11;
  private me.zayedbinhasan.digitaldelta.proto.VectorClock vectorClock_;
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 11;</code>
   */
  @java.lang.Override
  public boolean hasVectorClock() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 11;</code>
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
    return vectorClock_ == null ? me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance() : vectorClock_;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 11;</code>
   */
  private void setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  vectorClock_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 11;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  if (vectorClock_ != null &&
        vectorClock_ != me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance()) {
      vectorClock_ =
        me.zayedbinhasan.digitaldelta.proto.VectorClock.newBuilder(vectorClock_).mergeFrom(value).buildPartial();
    } else {
      vectorClock_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 11;</code>
   */
  private void clearVectorClock() {  vectorClock_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.DeliveryTask prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.DeliveryTask}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.DeliveryTask, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.DeliveryTask)
      me.zayedbinhasan.digitaldelta.proto.DeliveryTaskOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.DeliveryTask.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string task_id = 1;</code>
     * @return The taskId.
     */
    @java.lang.Override
    public java.lang.String getTaskId() {
      return instance.getTaskId();
    }
    /**
     * <code>string task_id = 1;</code>
     * @return The bytes for taskId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      return instance.getTaskIdBytes();
    }
    /**
     * <code>string task_id = 1;</code>
     * @param value The taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskId(
        java.lang.String value) {
      copyOnWrite();
      instance.setTaskId(value);
      return this;
    }
    /**
     * <code>string task_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskId() {
      copyOnWrite();
      instance.clearTaskId();
      return this;
    }
    /**
     * <code>string task_id = 1;</code>
     * @param value The bytes for taskId to set.
     * @return This builder for chaining.
     */
    public Builder setTaskIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTaskIdBytes(value);
      return this;
    }

    /**
     * <code>string supply_id = 2;</code>
     * @return The supplyId.
     */
    @java.lang.Override
    public java.lang.String getSupplyId() {
      return instance.getSupplyId();
    }
    /**
     * <code>string supply_id = 2;</code>
     * @return The bytes for supplyId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSupplyIdBytes() {
      return instance.getSupplyIdBytes();
    }
    /**
     * <code>string supply_id = 2;</code>
     * @param value The supplyId to set.
     * @return This builder for chaining.
     */
    public Builder setSupplyId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSupplyId(value);
      return this;
    }
    /**
     * <code>string supply_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSupplyId() {
      copyOnWrite();
      instance.clearSupplyId();
      return this;
    }
    /**
     * <code>string supply_id = 2;</code>
     * @param value The bytes for supplyId to set.
     * @return This builder for chaining.
     */
    public Builder setSupplyIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSupplyIdBytes(value);
      return this;
    }

    /**
     * <code>int32 quantity = 3;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return instance.getQuantity();
    }
    /**
     * <code>int32 quantity = 3;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      copyOnWrite();
      instance.setQuantity(value);
      return this;
    }
    /**
     * <code>int32 quantity = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      copyOnWrite();
      instance.clearQuantity();
      return this;
    }

    /**
     * <code>string origin_id = 4;</code>
     * @return The originId.
     */
    @java.lang.Override
    public java.lang.String getOriginId() {
      return instance.getOriginId();
    }
    /**
     * <code>string origin_id = 4;</code>
     * @return The bytes for originId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOriginIdBytes() {
      return instance.getOriginIdBytes();
    }
    /**
     * <code>string origin_id = 4;</code>
     * @param value The originId to set.
     * @return This builder for chaining.
     */
    public Builder setOriginId(
        java.lang.String value) {
      copyOnWrite();
      instance.setOriginId(value);
      return this;
    }
    /**
     * <code>string origin_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginId() {
      copyOnWrite();
      instance.clearOriginId();
      return this;
    }
    /**
     * <code>string origin_id = 4;</code>
     * @param value The bytes for originId to set.
     * @return This builder for chaining.
     */
    public Builder setOriginIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOriginIdBytes(value);
      return this;
    }

    /**
     * <code>string destination_id = 5;</code>
     * @return The destinationId.
     */
    @java.lang.Override
    public java.lang.String getDestinationId() {
      return instance.getDestinationId();
    }
    /**
     * <code>string destination_id = 5;</code>
     * @return The bytes for destinationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDestinationIdBytes() {
      return instance.getDestinationIdBytes();
    }
    /**
     * <code>string destination_id = 5;</code>
     * @param value The destinationId to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDestinationId(value);
      return this;
    }
    /**
     * <code>string destination_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestinationId() {
      copyOnWrite();
      instance.clearDestinationId();
      return this;
    }
    /**
     * <code>string destination_id = 5;</code>
     * @param value The bytes for destinationId to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDestinationIdBytes(value);
      return this;
    }

    /**
     * <code>.digitaldelta.v1.PriorityTier priority = 6;</code>
     * @return The enum numeric value on the wire for priority.
     */
    @java.lang.Override
    public int getPriorityValue() {
      return instance.getPriorityValue();
    }
    /**
     * <code>.digitaldelta.v1.PriorityTier priority = 6;</code>
     * @param value The priority to set.
     * @return This builder for chaining.
     */
    public Builder setPriorityValue(int value) {
      copyOnWrite();
      instance.setPriorityValue(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.PriorityTier priority = 6;</code>
     * @return The priority.
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.PriorityTier getPriority() {
      return instance.getPriority();
    }
    /**
     * <code>.digitaldelta.v1.PriorityTier priority = 6;</code>
     * @param value The enum numeric value on the wire for priority to set.
     * @return This builder for chaining.
     */
    public Builder setPriority(me.zayedbinhasan.digitaldelta.proto.PriorityTier value) {
      copyOnWrite();
      instance.setPriority(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.PriorityTier priority = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriority() {
      copyOnWrite();
      instance.clearPriority();
      return this;
    }

    /**
     * <code>int64 deadline_timestamp = 7;</code>
     * @return The deadlineTimestamp.
     */
    @java.lang.Override
    public long getDeadlineTimestamp() {
      return instance.getDeadlineTimestamp();
    }
    /**
     * <code>int64 deadline_timestamp = 7;</code>
     * @param value The deadlineTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setDeadlineTimestamp(long value) {
      copyOnWrite();
      instance.setDeadlineTimestamp(value);
      return this;
    }
    /**
     * <code>int64 deadline_timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeadlineTimestamp() {
      copyOnWrite();
      instance.clearDeadlineTimestamp();
      return this;
    }

    /**
     * <code>string assigned_driver_id = 8;</code>
     * @return The assignedDriverId.
     */
    @java.lang.Override
    public java.lang.String getAssignedDriverId() {
      return instance.getAssignedDriverId();
    }
    /**
     * <code>string assigned_driver_id = 8;</code>
     * @return The bytes for assignedDriverId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAssignedDriverIdBytes() {
      return instance.getAssignedDriverIdBytes();
    }
    /**
     * <code>string assigned_driver_id = 8;</code>
     * @param value The assignedDriverId to set.
     * @return This builder for chaining.
     */
    public Builder setAssignedDriverId(
        java.lang.String value) {
      copyOnWrite();
      instance.setAssignedDriverId(value);
      return this;
    }
    /**
     * <code>string assigned_driver_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearAssignedDriverId() {
      copyOnWrite();
      instance.clearAssignedDriverId();
      return this;
    }
    /**
     * <code>string assigned_driver_id = 8;</code>
     * @param value The bytes for assignedDriverId to set.
     * @return This builder for chaining.
     */
    public Builder setAssignedDriverIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAssignedDriverIdBytes(value);
      return this;
    }

    /**
     * <code>.digitaldelta.v1.DeliveryStatus status = 9;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override
    public int getStatusValue() {
      return instance.getStatusValue();
    }
    /**
     * <code>.digitaldelta.v1.DeliveryStatus status = 9;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      copyOnWrite();
      instance.setStatusValue(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.DeliveryStatus status = 9;</code>
     * @return The status.
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.DeliveryStatus getStatus() {
      return instance.getStatus();
    }
    /**
     * <code>.digitaldelta.v1.DeliveryStatus status = 9;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(me.zayedbinhasan.digitaldelta.proto.DeliveryStatus value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.DeliveryStatus status = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }

    /**
     * <code>uint64 updated_at = 10;</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public long getUpdatedAt() {
      return instance.getUpdatedAt();
    }
    /**
     * <code>uint64 updated_at = 10;</code>
     * @param value The updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAt(long value) {
      copyOnWrite();
      instance.setUpdatedAt(value);
      return this;
    }
    /**
     * <code>uint64 updated_at = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedAt() {
      copyOnWrite();
      instance.clearUpdatedAt();
      return this;
    }

    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 11;</code>
     */
    @java.lang.Override
    public boolean hasVectorClock() {
      return instance.hasVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 11;</code>
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
      return instance.getVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 11;</code>
     */
    public Builder setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.setVectorClock(value);
      return this;
      }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 11;</code>
     */
    public Builder setVectorClock(
        me.zayedbinhasan.digitaldelta.proto.VectorClock.Builder builderForValue) {
      copyOnWrite();
      instance.setVectorClock(builderForValue.build());
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 11;</code>
     */
    public Builder mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.mergeVectorClock(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 11;</code>
     */
    public Builder clearVectorClock() {  copyOnWrite();
      instance.clearVectorClock();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.DeliveryTask)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.DeliveryTask();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "taskId_",
            "supplyId_",
            "quantity_",
            "originId_",
            "destinationId_",
            "priority_",
            "deadlineTimestamp_",
            "assignedDriverId_",
            "status_",
            "updatedAt_",
            "vectorClock_",
          };
          java.lang.String info =
              "\u0000\u000b\u0000\u0001\u0001\u000b\u000b\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0004\u0004\u0208\u0005\u0208\u0006\f\u0007\u0002\b\u0208\t\f\n\u0003\u000b" +
              "\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.DeliveryTask> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.DeliveryTask.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.DeliveryTask>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.DeliveryTask)
  private static final me.zayedbinhasan.digitaldelta.proto.DeliveryTask DEFAULT_INSTANCE;
  static {
    DeliveryTask defaultInstance = new DeliveryTask();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DeliveryTask.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.DeliveryTask getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DeliveryTask> PARSER;

  public static com.google.protobuf.Parser<DeliveryTask> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

