// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: delivery.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface DeliveryConflictOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.DeliveryConflict)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string conflict_id = 1;</code>
   * @return The conflictId.
   */
  java.lang.String getConflictId();
  /**
   * <code>string conflict_id = 1;</code>
   * @return The bytes for conflictId.
   */
  com.google.protobuf.ByteString
      getConflictIdBytes();

  /**
   * <code>string task_id = 2;</code>
   * @return The taskId.
   */
  java.lang.String getTaskId();
  /**
   * <code>string task_id = 2;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>string local_mutation_id = 3;</code>
   * @return The localMutationId.
   */
  java.lang.String getLocalMutationId();
  /**
   * <code>string local_mutation_id = 3;</code>
   * @return The bytes for localMutationId.
   */
  com.google.protobuf.ByteString
      getLocalMutationIdBytes();

  /**
   * <code>string remote_mutation_id = 4;</code>
   * @return The remoteMutationId.
   */
  java.lang.String getRemoteMutationId();
  /**
   * <code>string remote_mutation_id = 4;</code>
   * @return The bytes for remoteMutationId.
   */
  com.google.protobuf.ByteString
      getRemoteMutationIdBytes();

  /**
   * <code>.digitaldelta.v1.ConflictResolution resolution = 5;</code>
   * @return The enum numeric value on the wire for resolution.
   */
  int getResolutionValue();
  /**
   * <code>.digitaldelta.v1.ConflictResolution resolution = 5;</code>
   * @return The resolution.
   */
  me.zayedbinhasan.digitaldelta.proto.ConflictResolution getResolution();

  /**
   * <code>string notes = 6;</code>
   * @return The notes.
   */
  java.lang.String getNotes();
  /**
   * <code>string notes = 6;</code>
   * @return The bytes for notes.
   */
  com.google.protobuf.ByteString
      getNotesBytes();

  /**
   * <code>uint64 detected_at = 7;</code>
   * @return The detectedAt.
   */
  long getDetectedAt();
}
