// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sync.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface DeltaSyncResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.DeltaSyncResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .digitaldelta.v1.Mutation incoming_mutations = 1;</code>
   */
  java.util.List<me.zayedbinhasan.digitaldelta.proto.Mutation> 
      getIncomingMutationsList();
  /**
   * <code>repeated .digitaldelta.v1.Mutation incoming_mutations = 1;</code>
   */
  me.zayedbinhasan.digitaldelta.proto.Mutation getIncomingMutations(int index);
  /**
   * <code>repeated .digitaldelta.v1.Mutation incoming_mutations = 1;</code>
   */
  int getIncomingMutationsCount();

  /**
   * <code>.digitaldelta.v1.SyncCheckpoint updated_checkpoint = 2;</code>
   * @return Whether the updatedCheckpoint field is set.
   */
  boolean hasUpdatedCheckpoint();
  /**
   * <code>.digitaldelta.v1.SyncCheckpoint updated_checkpoint = 2;</code>
   * @return The updatedCheckpoint.
   */
  me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint getUpdatedCheckpoint();

  /**
   * <code>bool has_conflicts = 3;</code>
   * @return The hasConflicts.
   */
  boolean getHasConflicts();

  /**
   * <code>repeated string conflict_entity_ids = 4;</code>
   * @return A list containing the conflictEntityIds.
   */
  java.util.List<java.lang.String>
      getConflictEntityIdsList();
  /**
   * <code>repeated string conflict_entity_ids = 4;</code>
   * @return The count of conflictEntityIds.
   */
  int getConflictEntityIdsCount();
  /**
   * <code>repeated string conflict_entity_ids = 4;</code>
   * @param index The index of the element to return.
   * @return The conflictEntityIds at the given index.
   */
  java.lang.String getConflictEntityIds(int index);
  /**
   * <code>repeated string conflict_entity_ids = 4;</code>
   * @param index The index of the element to return.
   * @return The conflictEntityIds at the given index.
   */
  com.google.protobuf.ByteString
      getConflictEntityIdsBytes(int index);
}
