// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sync.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface DeltaSyncRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.DeltaSyncRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
   * @return Whether the checkpoint field is set.
   */
  boolean hasCheckpoint();
  /**
   * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
   * @return The checkpoint.
   */
  me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint getCheckpoint();

  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  java.util.List<me.zayedbinhasan.digitaldelta.proto.Mutation> 
      getOutgoingMutationsList();
  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  me.zayedbinhasan.digitaldelta.proto.Mutation getOutgoingMutations(int index);
  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  int getOutgoingMutationsCount();
}
