// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sync.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.DeltaSyncRequest}
 */
public  final class DeltaSyncRequest extends
    com.google.protobuf.GeneratedMessageLite<
        DeltaSyncRequest, DeltaSyncRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.DeltaSyncRequest)
    DeltaSyncRequestOrBuilder {
  private DeltaSyncRequest() {
    nodeId_ = "";
    outgoingMutations_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int NODE_ID_FIELD_NUMBER = 1;
  private java.lang.String nodeId_;
  /**
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  @java.lang.Override
  public java.lang.String getNodeId() {
    return nodeId_;
  }
  /**
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(nodeId_);
  }
  /**
   * <code>string node_id = 1;</code>
   * @param value The nodeId to set.
   */
  private void setNodeId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    nodeId_ = value;
  }
  /**
   * <code>string node_id = 1;</code>
   */
  private void clearNodeId() {

    nodeId_ = getDefaultInstance().getNodeId();
  }
  /**
   * <code>string node_id = 1;</code>
   * @param value The bytes for nodeId to set.
   */
  private void setNodeIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    nodeId_ = value.toStringUtf8();

  }

  public static final int CHECKPOINT_FIELD_NUMBER = 2;
  private me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint checkpoint_;
  /**
   * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
   */
  @java.lang.Override
  public boolean hasCheckpoint() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint getCheckpoint() {
    return checkpoint_ == null ? me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint.getDefaultInstance() : checkpoint_;
  }
  /**
   * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
   */
  private void setCheckpoint(me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint value) {
    value.getClass();
  checkpoint_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeCheckpoint(me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint value) {
    value.getClass();
  if (checkpoint_ != null &&
        checkpoint_ != me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint.getDefaultInstance()) {
      checkpoint_ =
        me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint.newBuilder(checkpoint_).mergeFrom(value).buildPartial();
    } else {
      checkpoint_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
   */
  private void clearCheckpoint() {  checkpoint_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int OUTGOING_MUTATIONS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<me.zayedbinhasan.digitaldelta.proto.Mutation> outgoingMutations_;
  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  @java.lang.Override
  public java.util.List<me.zayedbinhasan.digitaldelta.proto.Mutation> getOutgoingMutationsList() {
    return outgoingMutations_;
  }
  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  public java.util.List<? extends me.zayedbinhasan.digitaldelta.proto.MutationOrBuilder> 
      getOutgoingMutationsOrBuilderList() {
    return outgoingMutations_;
  }
  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  @java.lang.Override
  public int getOutgoingMutationsCount() {
    return outgoingMutations_.size();
  }
  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.Mutation getOutgoingMutations(int index) {
    return outgoingMutations_.get(index);
  }
  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  public me.zayedbinhasan.digitaldelta.proto.MutationOrBuilder getOutgoingMutationsOrBuilder(
      int index) {
    return outgoingMutations_.get(index);
  }
  private void ensureOutgoingMutationsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<me.zayedbinhasan.digitaldelta.proto.Mutation> tmp = outgoingMutations_;
    if (!tmp.isModifiable()) {
      outgoingMutations_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  private void setOutgoingMutations(
      int index, me.zayedbinhasan.digitaldelta.proto.Mutation value) {
    value.getClass();
  ensureOutgoingMutationsIsMutable();
    outgoingMutations_.set(index, value);
  }
  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  private void addOutgoingMutations(me.zayedbinhasan.digitaldelta.proto.Mutation value) {
    value.getClass();
  ensureOutgoingMutationsIsMutable();
    outgoingMutations_.add(value);
  }
  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  private void addOutgoingMutations(
      int index, me.zayedbinhasan.digitaldelta.proto.Mutation value) {
    value.getClass();
  ensureOutgoingMutationsIsMutable();
    outgoingMutations_.add(index, value);
  }
  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  private void addAllOutgoingMutations(
      java.lang.Iterable<? extends me.zayedbinhasan.digitaldelta.proto.Mutation> values) {
    ensureOutgoingMutationsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, outgoingMutations_);
  }
  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  private void clearOutgoingMutations() {
    outgoingMutations_ = emptyProtobufList();
  }
  /**
   * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
   */
  private void removeOutgoingMutations(int index) {
    ensureOutgoingMutationsIsMutable();
    outgoingMutations_.remove(index);
  }

  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.DeltaSyncRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.DeltaSyncRequest)
      me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequestOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string node_id = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      return instance.getNodeId();
    }
    /**
     * <code>string node_id = 1;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      return instance.getNodeIdBytes();
    }
    /**
     * <code>string node_id = 1;</code>
     * @param value The nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeId(
        java.lang.String value) {
      copyOnWrite();
      instance.setNodeId(value);
      return this;
    }
    /**
     * <code>string node_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeId() {
      copyOnWrite();
      instance.clearNodeId();
      return this;
    }
    /**
     * <code>string node_id = 1;</code>
     * @param value The bytes for nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNodeIdBytes(value);
      return this;
    }

    /**
     * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
     */
    @java.lang.Override
    public boolean hasCheckpoint() {
      return instance.hasCheckpoint();
    }
    /**
     * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint getCheckpoint() {
      return instance.getCheckpoint();
    }
    /**
     * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
     */
    public Builder setCheckpoint(me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint value) {
      copyOnWrite();
      instance.setCheckpoint(value);
      return this;
      }
    /**
     * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
     */
    public Builder setCheckpoint(
        me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint.Builder builderForValue) {
      copyOnWrite();
      instance.setCheckpoint(builderForValue.build());
      return this;
    }
    /**
     * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
     */
    public Builder mergeCheckpoint(me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint value) {
      copyOnWrite();
      instance.mergeCheckpoint(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.SyncCheckpoint checkpoint = 2;</code>
     */
    public Builder clearCheckpoint() {  copyOnWrite();
      instance.clearCheckpoint();
      return this;
    }

    /**
     * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
     */
    @java.lang.Override
    public java.util.List<me.zayedbinhasan.digitaldelta.proto.Mutation> getOutgoingMutationsList() {
      return java.util.Collections.unmodifiableList(
          instance.getOutgoingMutationsList());
    }
    /**
     * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
     */
    @java.lang.Override
    public int getOutgoingMutationsCount() {
      return instance.getOutgoingMutationsCount();
    }/**
     * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.Mutation getOutgoingMutations(int index) {
      return instance.getOutgoingMutations(index);
    }
    /**
     * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
     */
    public Builder setOutgoingMutations(
        int index, me.zayedbinhasan.digitaldelta.proto.Mutation value) {
      copyOnWrite();
      instance.setOutgoingMutations(index, value);
      return this;
    }
    /**
     * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
     */
    public Builder setOutgoingMutations(
        int index, me.zayedbinhasan.digitaldelta.proto.Mutation.Builder builderForValue) {
      copyOnWrite();
      instance.setOutgoingMutations(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
     */
    public Builder addOutgoingMutations(me.zayedbinhasan.digitaldelta.proto.Mutation value) {
      copyOnWrite();
      instance.addOutgoingMutations(value);
      return this;
    }
    /**
     * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
     */
    public Builder addOutgoingMutations(
        int index, me.zayedbinhasan.digitaldelta.proto.Mutation value) {
      copyOnWrite();
      instance.addOutgoingMutations(index, value);
      return this;
    }
    /**
     * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
     */
    public Builder addOutgoingMutations(
        me.zayedbinhasan.digitaldelta.proto.Mutation.Builder builderForValue) {
      copyOnWrite();
      instance.addOutgoingMutations(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
     */
    public Builder addOutgoingMutations(
        int index, me.zayedbinhasan.digitaldelta.proto.Mutation.Builder builderForValue) {
      copyOnWrite();
      instance.addOutgoingMutations(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
     */
    public Builder addAllOutgoingMutations(
        java.lang.Iterable<? extends me.zayedbinhasan.digitaldelta.proto.Mutation> values) {
      copyOnWrite();
      instance.addAllOutgoingMutations(values);
      return this;
    }
    /**
     * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
     */
    public Builder clearOutgoingMutations() {
      copyOnWrite();
      instance.clearOutgoingMutations();
      return this;
    }
    /**
     * <code>repeated .digitaldelta.v1.Mutation outgoing_mutations = 3;</code>
     */
    public Builder removeOutgoingMutations(int index) {
      copyOnWrite();
      instance.removeOutgoingMutations(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.DeltaSyncRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "nodeId_",
            "checkpoint_",
            "outgoingMutations_",
            me.zayedbinhasan.digitaldelta.proto.Mutation.class,
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0208\u0002\u1009" +
              "\u0000\u0003\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.DeltaSyncRequest)
  private static final me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest DEFAULT_INSTANCE;
  static {
    DeltaSyncRequest defaultInstance = new DeltaSyncRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DeltaSyncRequest.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.DeltaSyncRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DeltaSyncRequest> PARSER;

  public static com.google.protobuf.Parser<DeltaSyncRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

