// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: routing.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf enum {@code digitaldelta.v1.EdgeType}
 */
public enum EdgeType
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>EDGE_TYPE_UNSPECIFIED = 0;</code>
   */
  EDGE_TYPE_UNSPECIFIED(0),
  /**
   * <code>ROAD = 1;</code>
   */
  ROAD(1),
  /**
   * <code>WATERWAY = 2;</code>
   */
  WATERWAY(2),
  /**
   * <code>AIRWAY = 3;</code>
   */
  AIRWAY(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>EDGE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int EDGE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>ROAD = 1;</code>
   */
  public static final int ROAD_VALUE = 1;
  /**
   * <code>WATERWAY = 2;</code>
   */
  public static final int WATERWAY_VALUE = 2;
  /**
   * <code>AIRWAY = 3;</code>
   */
  public static final int AIRWAY_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EdgeType valueOf(int value) {
    return forNumber(value);
  }

  public static EdgeType forNumber(int value) {
    switch (value) {
      case 0: return EDGE_TYPE_UNSPECIFIED;
      case 1: return ROAD;
      case 2: return WATERWAY;
      case 3: return AIRWAY;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EdgeType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EdgeType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EdgeType>() {
          @java.lang.Override
          public EdgeType findValueByNumber(int number) {
            return EdgeType.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return EdgeTypeVerifier.INSTANCE;
  }

  private static final class EdgeTypeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new EdgeTypeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return EdgeType.forNumber(number) != null;
          }
        };

  private final int value;

  private EdgeType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:digitaldelta.v1.EdgeType)
}

