// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.GeoLocation}
 */
public  final class GeoLocation extends
    com.google.protobuf.GeneratedMessageLite<
        GeoLocation, GeoLocation.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.GeoLocation)
    GeoLocationOrBuilder {
  private GeoLocation() {
  }
  public static final int LAT_FIELD_NUMBER = 1;
  private double lat_;
  /**
   * <code>double lat = 1;</code>
   * @return The lat.
   */
  @java.lang.Override
  public double getLat() {
    return lat_;
  }
  /**
   * <code>double lat = 1;</code>
   * @param value The lat to set.
   */
  private void setLat(double value) {
    
    lat_ = value;
  }
  /**
   * <code>double lat = 1;</code>
   */
  private void clearLat() {

    lat_ = 0D;
  }

  public static final int LNG_FIELD_NUMBER = 2;
  private double lng_;
  /**
   * <code>double lng = 2;</code>
   * @return The lng.
   */
  @java.lang.Override
  public double getLng() {
    return lng_;
  }
  /**
   * <code>double lng = 2;</code>
   * @param value The lng to set.
   */
  private void setLng(double value) {
    
    lng_ = value;
  }
  /**
   * <code>double lng = 2;</code>
   */
  private void clearLng() {

    lng_ = 0D;
  }

  public static final int ACCURACY_METERS_FIELD_NUMBER = 3;
  private float accuracyMeters_;
  /**
   * <code>float accuracy_meters = 3;</code>
   * @return The accuracyMeters.
   */
  @java.lang.Override
  public float getAccuracyMeters() {
    return accuracyMeters_;
  }
  /**
   * <code>float accuracy_meters = 3;</code>
   * @param value The accuracyMeters to set.
   */
  private void setAccuracyMeters(float value) {
    
    accuracyMeters_ = value;
  }
  /**
   * <code>float accuracy_meters = 3;</code>
   */
  private void clearAccuracyMeters() {

    accuracyMeters_ = 0F;
  }

  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.GeoLocation prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.GeoLocation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.GeoLocation, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.GeoLocation)
      me.zayedbinhasan.digitaldelta.proto.GeoLocationOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.GeoLocation.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>double lat = 1;</code>
     * @return The lat.
     */
    @java.lang.Override
    public double getLat() {
      return instance.getLat();
    }
    /**
     * <code>double lat = 1;</code>
     * @param value The lat to set.
     * @return This builder for chaining.
     */
    public Builder setLat(double value) {
      copyOnWrite();
      instance.setLat(value);
      return this;
    }
    /**
     * <code>double lat = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLat() {
      copyOnWrite();
      instance.clearLat();
      return this;
    }

    /**
     * <code>double lng = 2;</code>
     * @return The lng.
     */
    @java.lang.Override
    public double getLng() {
      return instance.getLng();
    }
    /**
     * <code>double lng = 2;</code>
     * @param value The lng to set.
     * @return This builder for chaining.
     */
    public Builder setLng(double value) {
      copyOnWrite();
      instance.setLng(value);
      return this;
    }
    /**
     * <code>double lng = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLng() {
      copyOnWrite();
      instance.clearLng();
      return this;
    }

    /**
     * <code>float accuracy_meters = 3;</code>
     * @return The accuracyMeters.
     */
    @java.lang.Override
    public float getAccuracyMeters() {
      return instance.getAccuracyMeters();
    }
    /**
     * <code>float accuracy_meters = 3;</code>
     * @param value The accuracyMeters to set.
     * @return This builder for chaining.
     */
    public Builder setAccuracyMeters(float value) {
      copyOnWrite();
      instance.setAccuracyMeters(value);
      return this;
    }
    /**
     * <code>float accuracy_meters = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccuracyMeters() {
      copyOnWrite();
      instance.clearAccuracyMeters();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.GeoLocation)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.GeoLocation();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "lat_",
            "lng_",
            "accuracyMeters_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
              "\u0003\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.GeoLocation> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.GeoLocation.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.GeoLocation>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.GeoLocation)
  private static final me.zayedbinhasan.digitaldelta.proto.GeoLocation DEFAULT_INSTANCE;
  static {
    GeoLocation defaultInstance = new GeoLocation();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GeoLocation.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.GeoLocation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GeoLocation> PARSER;

  public static com.google.protobuf.Parser<GeoLocation> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

