// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface GeoLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.GeoLocation)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>double lat = 1;</code>
   * @return The lat.
   */
  double getLat();

  /**
   * <code>double lng = 2;</code>
   * @return The lng.
   */
  double getLng();

  /**
   * <code>float accuracy_meters = 3;</code>
   * @return The accuracyMeters.
   */
  float getAccuracyMeters();
}
