// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inventory.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.InventoryAdjustment}
 */
public  final class InventoryAdjustment extends
    com.google.protobuf.GeneratedMessageLite<
        InventoryAdjustment, InventoryAdjustment.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.InventoryAdjustment)
    InventoryAdjustmentOrBuilder {
  private InventoryAdjustment() {
    adjustmentId_ = "";
    itemId_ = "";
    reason_ = "";
    actorId_ = "";
  }
  private int bitField0_;
  public static final int ADJUSTMENT_ID_FIELD_NUMBER = 1;
  private java.lang.String adjustmentId_;
  /**
   * <code>string adjustment_id = 1;</code>
   * @return The adjustmentId.
   */
  @java.lang.Override
  public java.lang.String getAdjustmentId() {
    return adjustmentId_;
  }
  /**
   * <code>string adjustment_id = 1;</code>
   * @return The bytes for adjustmentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAdjustmentIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(adjustmentId_);
  }
  /**
   * <code>string adjustment_id = 1;</code>
   * @param value The adjustmentId to set.
   */
  private void setAdjustmentId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    adjustmentId_ = value;
  }
  /**
   * <code>string adjustment_id = 1;</code>
   */
  private void clearAdjustmentId() {

    adjustmentId_ = getDefaultInstance().getAdjustmentId();
  }
  /**
   * <code>string adjustment_id = 1;</code>
   * @param value The bytes for adjustmentId to set.
   */
  private void setAdjustmentIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    adjustmentId_ = value.toStringUtf8();

  }

  public static final int ITEM_ID_FIELD_NUMBER = 2;
  private java.lang.String itemId_;
  /**
   * <code>string item_id = 2;</code>
   * @return The itemId.
   */
  @java.lang.Override
  public java.lang.String getItemId() {
    return itemId_;
  }
  /**
   * <code>string item_id = 2;</code>
   * @return The bytes for itemId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getItemIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(itemId_);
  }
  /**
   * <code>string item_id = 2;</code>
   * @param value The itemId to set.
   */
  private void setItemId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    itemId_ = value;
  }
  /**
   * <code>string item_id = 2;</code>
   */
  private void clearItemId() {

    itemId_ = getDefaultInstance().getItemId();
  }
  /**
   * <code>string item_id = 2;</code>
   * @param value The bytes for itemId to set.
   */
  private void setItemIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    itemId_ = value.toStringUtf8();

  }

  public static final int SIGNED_DELTA_FIELD_NUMBER = 3;
  private int signedDelta_;
  /**
   * <code>int32 signed_delta = 3;</code>
   * @return The signedDelta.
   */
  @java.lang.Override
  public int getSignedDelta() {
    return signedDelta_;
  }
  /**
   * <code>int32 signed_delta = 3;</code>
   * @param value The signedDelta to set.
   */
  private void setSignedDelta(int value) {
    
    signedDelta_ = value;
  }
  /**
   * <code>int32 signed_delta = 3;</code>
   */
  private void clearSignedDelta() {

    signedDelta_ = 0;
  }

  public static final int REASON_FIELD_NUMBER = 4;
  private java.lang.String reason_;
  /**
   * <code>string reason = 4;</code>
   * @return The reason.
   */
  @java.lang.Override
  public java.lang.String getReason() {
    return reason_;
  }
  /**
   * <code>string reason = 4;</code>
   * @return The bytes for reason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reason_);
  }
  /**
   * <code>string reason = 4;</code>
   * @param value The reason to set.
   */
  private void setReason(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    reason_ = value;
  }
  /**
   * <code>string reason = 4;</code>
   */
  private void clearReason() {

    reason_ = getDefaultInstance().getReason();
  }
  /**
   * <code>string reason = 4;</code>
   * @param value The bytes for reason to set.
   */
  private void setReasonBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reason_ = value.toStringUtf8();

  }

  public static final int ACTOR_ID_FIELD_NUMBER = 5;
  private java.lang.String actorId_;
  /**
   * <code>string actor_id = 5;</code>
   * @return The actorId.
   */
  @java.lang.Override
  public java.lang.String getActorId() {
    return actorId_;
  }
  /**
   * <code>string actor_id = 5;</code>
   * @return The bytes for actorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActorIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(actorId_);
  }
  /**
   * <code>string actor_id = 5;</code>
   * @param value The actorId to set.
   */
  private void setActorId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    actorId_ = value;
  }
  /**
   * <code>string actor_id = 5;</code>
   */
  private void clearActorId() {

    actorId_ = getDefaultInstance().getActorId();
  }
  /**
   * <code>string actor_id = 5;</code>
   * @param value The bytes for actorId to set.
   */
  private void setActorIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    actorId_ = value.toStringUtf8();

  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }
  /**
   * <code>uint64 timestamp = 6;</code>
   * @param value The timestamp to set.
   */
  private void setTimestamp(long value) {
    
    timestamp_ = value;
  }
  /**
   * <code>uint64 timestamp = 6;</code>
   */
  private void clearTimestamp() {

    timestamp_ = 0L;
  }

  public static final int VECTOR_CLOCK_FIELD_NUMBER = 7;
  private me.zayedbinhasan.digitaldelta.proto.VectorClock vectorClock_;
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
   */
  @java.lang.Override
  public boolean hasVectorClock() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
    return vectorClock_ == null ? me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance() : vectorClock_;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
   */
  private void setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  vectorClock_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  if (vectorClock_ != null &&
        vectorClock_ != me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance()) {
      vectorClock_ =
        me.zayedbinhasan.digitaldelta.proto.VectorClock.newBuilder(vectorClock_).mergeFrom(value).buildPartial();
    } else {
      vectorClock_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
   */
  private void clearVectorClock() {  vectorClock_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.InventoryAdjustment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.InventoryAdjustment)
      me.zayedbinhasan.digitaldelta.proto.InventoryAdjustmentOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string adjustment_id = 1;</code>
     * @return The adjustmentId.
     */
    @java.lang.Override
    public java.lang.String getAdjustmentId() {
      return instance.getAdjustmentId();
    }
    /**
     * <code>string adjustment_id = 1;</code>
     * @return The bytes for adjustmentId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAdjustmentIdBytes() {
      return instance.getAdjustmentIdBytes();
    }
    /**
     * <code>string adjustment_id = 1;</code>
     * @param value The adjustmentId to set.
     * @return This builder for chaining.
     */
    public Builder setAdjustmentId(
        java.lang.String value) {
      copyOnWrite();
      instance.setAdjustmentId(value);
      return this;
    }
    /**
     * <code>string adjustment_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdjustmentId() {
      copyOnWrite();
      instance.clearAdjustmentId();
      return this;
    }
    /**
     * <code>string adjustment_id = 1;</code>
     * @param value The bytes for adjustmentId to set.
     * @return This builder for chaining.
     */
    public Builder setAdjustmentIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAdjustmentIdBytes(value);
      return this;
    }

    /**
     * <code>string item_id = 2;</code>
     * @return The itemId.
     */
    @java.lang.Override
    public java.lang.String getItemId() {
      return instance.getItemId();
    }
    /**
     * <code>string item_id = 2;</code>
     * @return The bytes for itemId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getItemIdBytes() {
      return instance.getItemIdBytes();
    }
    /**
     * <code>string item_id = 2;</code>
     * @param value The itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemId(
        java.lang.String value) {
      copyOnWrite();
      instance.setItemId(value);
      return this;
    }
    /**
     * <code>string item_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemId() {
      copyOnWrite();
      instance.clearItemId();
      return this;
    }
    /**
     * <code>string item_id = 2;</code>
     * @param value The bytes for itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setItemIdBytes(value);
      return this;
    }

    /**
     * <code>int32 signed_delta = 3;</code>
     * @return The signedDelta.
     */
    @java.lang.Override
    public int getSignedDelta() {
      return instance.getSignedDelta();
    }
    /**
     * <code>int32 signed_delta = 3;</code>
     * @param value The signedDelta to set.
     * @return This builder for chaining.
     */
    public Builder setSignedDelta(int value) {
      copyOnWrite();
      instance.setSignedDelta(value);
      return this;
    }
    /**
     * <code>int32 signed_delta = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignedDelta() {
      copyOnWrite();
      instance.clearSignedDelta();
      return this;
    }

    /**
     * <code>string reason = 4;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      return instance.getReason();
    }
    /**
     * <code>string reason = 4;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      return instance.getReasonBytes();
    }
    /**
     * <code>string reason = 4;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(
        java.lang.String value) {
      copyOnWrite();
      instance.setReason(value);
      return this;
    }
    /**
     * <code>string reason = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      copyOnWrite();
      instance.clearReason();
      return this;
    }
    /**
     * <code>string reason = 4;</code>
     * @param value The bytes for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReasonBytes(value);
      return this;
    }

    /**
     * <code>string actor_id = 5;</code>
     * @return The actorId.
     */
    @java.lang.Override
    public java.lang.String getActorId() {
      return instance.getActorId();
    }
    /**
     * <code>string actor_id = 5;</code>
     * @return The bytes for actorId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActorIdBytes() {
      return instance.getActorIdBytes();
    }
    /**
     * <code>string actor_id = 5;</code>
     * @param value The actorId to set.
     * @return This builder for chaining.
     */
    public Builder setActorId(
        java.lang.String value) {
      copyOnWrite();
      instance.setActorId(value);
      return this;
    }
    /**
     * <code>string actor_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearActorId() {
      copyOnWrite();
      instance.clearActorId();
      return this;
    }
    /**
     * <code>string actor_id = 5;</code>
     * @param value The bytes for actorId to set.
     * @return This builder for chaining.
     */
    public Builder setActorIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setActorIdBytes(value);
      return this;
    }

    /**
     * <code>uint64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return instance.getTimestamp();
    }
    /**
     * <code>uint64 timestamp = 6;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      copyOnWrite();
      instance.setTimestamp(value);
      return this;
    }
    /**
     * <code>uint64 timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      copyOnWrite();
      instance.clearTimestamp();
      return this;
    }

    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
     */
    @java.lang.Override
    public boolean hasVectorClock() {
      return instance.hasVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
      return instance.getVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
     */
    public Builder setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.setVectorClock(value);
      return this;
      }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
     */
    public Builder setVectorClock(
        me.zayedbinhasan.digitaldelta.proto.VectorClock.Builder builderForValue) {
      copyOnWrite();
      instance.setVectorClock(builderForValue.build());
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
     */
    public Builder mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.mergeVectorClock(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
     */
    public Builder clearVectorClock() {  copyOnWrite();
      instance.clearVectorClock();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.InventoryAdjustment)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "adjustmentId_",
            "itemId_",
            "signedDelta_",
            "reason_",
            "actorId_",
            "timestamp_",
            "vectorClock_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0001\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0004\u0004\u0208\u0005\u0208\u0006\u0003\u0007\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.InventoryAdjustment)
  private static final me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment DEFAULT_INSTANCE;
  static {
    InventoryAdjustment defaultInstance = new InventoryAdjustment();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      InventoryAdjustment.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.InventoryAdjustment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<InventoryAdjustment> PARSER;

  public static com.google.protobuf.Parser<InventoryAdjustment> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

