// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mesh.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface MeshMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.MeshMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>string sender_id = 2;</code>
   * @return The senderId.
   */
  java.lang.String getSenderId();
  /**
   * <code>string sender_id = 2;</code>
   * @return The bytes for senderId.
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string recipient_id = 3;</code>
   * @return The recipientId.
   */
  java.lang.String getRecipientId();
  /**
   * <code>string recipient_id = 3;</code>
   * @return The bytes for recipientId.
   */
  com.google.protobuf.ByteString
      getRecipientIdBytes();

  /**
   * <code>.digitaldelta.v1.MeshPayloadType payload_type = 4;</code>
   * @return The enum numeric value on the wire for payloadType.
   */
  int getPayloadTypeValue();
  /**
   * <code>.digitaldelta.v1.MeshPayloadType payload_type = 4;</code>
   * @return The payloadType.
   */
  me.zayedbinhasan.digitaldelta.proto.MeshPayloadType getPayloadType();

  /**
   * <code>bytes payload = 5;</code>
   * @return The payload.
   */
  com.google.protobuf.ByteString getPayload();

  /**
   * <code>uint32 ttl = 6;</code>
   * @return The ttl.
   */
  int getTtl();

  /**
   * <code>repeated string seen_nodes = 7;</code>
   * @return A list containing the seenNodes.
   */
  java.util.List<java.lang.String>
      getSeenNodesList();
  /**
   * <code>repeated string seen_nodes = 7;</code>
   * @return The count of seenNodes.
   */
  int getSeenNodesCount();
  /**
   * <code>repeated string seen_nodes = 7;</code>
   * @param index The index of the element to return.
   * @return The seenNodes at the given index.
   */
  java.lang.String getSeenNodes(int index);
  /**
   * <code>repeated string seen_nodes = 7;</code>
   * @param index The index of the element to return.
   * @return The seenNodes at the given index.
   */
  com.google.protobuf.ByteString
      getSeenNodesBytes(int index);

  /**
   * <code>uint32 attempt_count = 8;</code>
   * @return The attemptCount.
   */
  int getAttemptCount();

  /**
   * <code>uint64 created_at = 9;</code>
   * @return The createdAt.
   */
  long getCreatedAt();

  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 10;</code>
   * @return Whether the vectorClock field is set.
   */
  boolean hasVectorClock();
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 10;</code>
   * @return The vectorClock.
   */
  me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock();
}
