// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mesh.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf enum {@code digitaldelta.v1.MeshPayloadType}
 */
public enum MeshPayloadType
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>MESH_PAYLOAD_TYPE_UNSPECIFIED = 0;</code>
   */
  MESH_PAYLOAD_TYPE_UNSPECIFIED(0),
  /**
   * <code>MUTATION_BATCH = 1;</code>
   */
  MUTATION_BATCH(1),
  /**
   * <code>ROUTE_UPDATE = 2;</code>
   */
  ROUTE_UPDATE(2),
  /**
   * <code>POD_RECEIPT = 3;</code>
   */
  POD_RECEIPT(3),
  /**
   * <code>AUTH_EVENT = 4;</code>
   */
  AUTH_EVENT(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MESH_PAYLOAD_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int MESH_PAYLOAD_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>MUTATION_BATCH = 1;</code>
   */
  public static final int MUTATION_BATCH_VALUE = 1;
  /**
   * <code>ROUTE_UPDATE = 2;</code>
   */
  public static final int ROUTE_UPDATE_VALUE = 2;
  /**
   * <code>POD_RECEIPT = 3;</code>
   */
  public static final int POD_RECEIPT_VALUE = 3;
  /**
   * <code>AUTH_EVENT = 4;</code>
   */
  public static final int AUTH_EVENT_VALUE = 4;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MeshPayloadType valueOf(int value) {
    return forNumber(value);
  }

  public static MeshPayloadType forNumber(int value) {
    switch (value) {
      case 0: return MESH_PAYLOAD_TYPE_UNSPECIFIED;
      case 1: return MUTATION_BATCH;
      case 2: return ROUTE_UPDATE;
      case 3: return POD_RECEIPT;
      case 4: return AUTH_EVENT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MeshPayloadType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MeshPayloadType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MeshPayloadType>() {
          @java.lang.Override
          public MeshPayloadType findValueByNumber(int number) {
            return MeshPayloadType.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return MeshPayloadTypeVerifier.INSTANCE;
  }

  private static final class MeshPayloadTypeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new MeshPayloadTypeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return MeshPayloadType.forNumber(number) != null;
          }
        };

  private final int value;

  private MeshPayloadType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:digitaldelta.v1.MeshPayloadType)
}

