// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sync.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface MutationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.Mutation)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string mutation_id = 1;</code>
   * @return The mutationId.
   */
  java.lang.String getMutationId();
  /**
   * <code>string mutation_id = 1;</code>
   * @return The bytes for mutationId.
   */
  com.google.protobuf.ByteString
      getMutationIdBytes();

  /**
   * <code>string entity_type = 2;</code>
   * @return The entityType.
   */
  java.lang.String getEntityType();
  /**
   * <code>string entity_type = 2;</code>
   * @return The bytes for entityType.
   */
  com.google.protobuf.ByteString
      getEntityTypeBytes();

  /**
   * <code>string entity_id = 3;</code>
   * @return The entityId.
   */
  java.lang.String getEntityId();
  /**
   * <code>string entity_id = 3;</code>
   * @return The bytes for entityId.
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>map&lt;string, string&gt; changed_fields = 4;</code>
   */
  int getChangedFieldsCount();
  /**
   * <code>map&lt;string, string&gt; changed_fields = 4;</code>
   */
  boolean containsChangedFields(
      java.lang.String key);
  /**
   * Use {@link #getChangedFieldsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getChangedFields();
  /**
   * <code>map&lt;string, string&gt; changed_fields = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getChangedFieldsMap();
  /**
   * <code>map&lt;string, string&gt; changed_fields = 4;</code>
   */

  /* nullable */
java.lang.String getChangedFieldsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; changed_fields = 4;</code>
   */

  java.lang.String getChangedFieldsOrThrow(
      java.lang.String key);

  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
   * @return Whether the vectorClock field is set.
   */
  boolean hasVectorClock();
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
   * @return The vectorClock.
   */
  me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock();

  /**
   * <code>string actor_id = 6;</code>
   * @return The actorId.
   */
  java.lang.String getActorId();
  /**
   * <code>string actor_id = 6;</code>
   * @return The bytes for actorId.
   */
  com.google.protobuf.ByteString
      getActorIdBytes();

  /**
   * <code>uint64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>bytes payload_hash = 8;</code>
   * @return The payloadHash.
   */
  com.google.protobuf.ByteString getPayloadHash();

  /**
   * <code>bytes signature = 9;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();
}
