// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sync.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.Mutation}
 */
public  final class Mutation extends
    com.google.protobuf.GeneratedMessageLite<
        Mutation, Mutation.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.Mutation)
    MutationOrBuilder {
  private Mutation() {
    mutationId_ = "";
    entityType_ = "";
    entityId_ = "";
    actorId_ = "";
    payloadHash_ = com.google.protobuf.ByteString.EMPTY;
    signature_ = com.google.protobuf.ByteString.EMPTY;
  }
  private int bitField0_;
  public static final int MUTATION_ID_FIELD_NUMBER = 1;
  private java.lang.String mutationId_;
  /**
   * <code>string mutation_id = 1;</code>
   * @return The mutationId.
   */
  @java.lang.Override
  public java.lang.String getMutationId() {
    return mutationId_;
  }
  /**
   * <code>string mutation_id = 1;</code>
   * @return The bytes for mutationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMutationIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mutationId_);
  }
  /**
   * <code>string mutation_id = 1;</code>
   * @param value The mutationId to set.
   */
  private void setMutationId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    mutationId_ = value;
  }
  /**
   * <code>string mutation_id = 1;</code>
   */
  private void clearMutationId() {

    mutationId_ = getDefaultInstance().getMutationId();
  }
  /**
   * <code>string mutation_id = 1;</code>
   * @param value The bytes for mutationId to set.
   */
  private void setMutationIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    mutationId_ = value.toStringUtf8();

  }

  public static final int ENTITY_TYPE_FIELD_NUMBER = 2;
  private java.lang.String entityType_;
  /**
   * <code>string entity_type = 2;</code>
   * @return The entityType.
   */
  @java.lang.Override
  public java.lang.String getEntityType() {
    return entityType_;
  }
  /**
   * <code>string entity_type = 2;</code>
   * @return The bytes for entityType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEntityTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(entityType_);
  }
  /**
   * <code>string entity_type = 2;</code>
   * @param value The entityType to set.
   */
  private void setEntityType(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    entityType_ = value;
  }
  /**
   * <code>string entity_type = 2;</code>
   */
  private void clearEntityType() {

    entityType_ = getDefaultInstance().getEntityType();
  }
  /**
   * <code>string entity_type = 2;</code>
   * @param value The bytes for entityType to set.
   */
  private void setEntityTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    entityType_ = value.toStringUtf8();

  }

  public static final int ENTITY_ID_FIELD_NUMBER = 3;
  private java.lang.String entityId_;
  /**
   * <code>string entity_id = 3;</code>
   * @return The entityId.
   */
  @java.lang.Override
  public java.lang.String getEntityId() {
    return entityId_;
  }
  /**
   * <code>string entity_id = 3;</code>
   * @return The bytes for entityId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEntityIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(entityId_);
  }
  /**
   * <code>string entity_id = 3;</code>
   * @param value The entityId to set.
   */
  private void setEntityId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    entityId_ = value;
  }
  /**
   * <code>string entity_id = 3;</code>
   */
  private void clearEntityId() {

    entityId_ = getDefaultInstance().getEntityId();
  }
  /**
   * <code>string entity_id = 3;</code>
   * @param value The bytes for entityId to set.
   */
  private void setEntityIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    entityId_ = value.toStringUtf8();

  }

  public static final int CHANGED_FIELDS_FIELD_NUMBER = 4;
  private static final class ChangedFieldsDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, java.lang.String> changedFields_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
  internalGetChangedFields() {
    return changedFields_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.String>
  internalGetMutableChangedFields() {
    if (!changedFields_.isMutable()) {
      changedFields_ = changedFields_.mutableCopy();
    }
    return changedFields_;
  }
  @java.lang.Override

  public int getChangedFieldsCount() {
    return internalGetChangedFields().size();
  }
  /**
   * <code>map&lt;string, string&gt; changed_fields = 4;</code>
   */
  @java.lang.Override

  public boolean containsChangedFields(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    return internalGetChangedFields().containsKey(key);
  }
  /**
   * Use {@link #getChangedFieldsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getChangedFields() {
    return getChangedFieldsMap();
  }
  /**
   * <code>map&lt;string, string&gt; changed_fields = 4;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.String> getChangedFieldsMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetChangedFields());
  }
  /**
   * <code>map&lt;string, string&gt; changed_fields = 4;</code>
   */
  @java.lang.Override

  public /* nullable */
java.lang.String getChangedFieldsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetChangedFields();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; changed_fields = 4;</code>
   */
  @java.lang.Override

  public java.lang.String getChangedFieldsOrThrow(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetChangedFields();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   * <code>map&lt;string, string&gt; changed_fields = 4;</code>
   */
  private java.util.Map<java.lang.String, java.lang.String>
  getMutableChangedFieldsMap() {
    return internalGetMutableChangedFields();
  }

  public static final int VECTOR_CLOCK_FIELD_NUMBER = 5;
  private me.zayedbinhasan.digitaldelta.proto.VectorClock vectorClock_;
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
   */
  @java.lang.Override
  public boolean hasVectorClock() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
    return vectorClock_ == null ? me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance() : vectorClock_;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
   */
  private void setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  vectorClock_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  if (vectorClock_ != null &&
        vectorClock_ != me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance()) {
      vectorClock_ =
        me.zayedbinhasan.digitaldelta.proto.VectorClock.newBuilder(vectorClock_).mergeFrom(value).buildPartial();
    } else {
      vectorClock_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
   */
  private void clearVectorClock() {  vectorClock_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int ACTOR_ID_FIELD_NUMBER = 6;
  private java.lang.String actorId_;
  /**
   * <code>string actor_id = 6;</code>
   * @return The actorId.
   */
  @java.lang.Override
  public java.lang.String getActorId() {
    return actorId_;
  }
  /**
   * <code>string actor_id = 6;</code>
   * @return The bytes for actorId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActorIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(actorId_);
  }
  /**
   * <code>string actor_id = 6;</code>
   * @param value The actorId to set.
   */
  private void setActorId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    actorId_ = value;
  }
  /**
   * <code>string actor_id = 6;</code>
   */
  private void clearActorId() {

    actorId_ = getDefaultInstance().getActorId();
  }
  /**
   * <code>string actor_id = 6;</code>
   * @param value The bytes for actorId to set.
   */
  private void setActorIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    actorId_ = value.toStringUtf8();

  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 7;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }
  /**
   * <code>uint64 timestamp = 7;</code>
   * @param value The timestamp to set.
   */
  private void setTimestamp(long value) {
    
    timestamp_ = value;
  }
  /**
   * <code>uint64 timestamp = 7;</code>
   */
  private void clearTimestamp() {

    timestamp_ = 0L;
  }

  public static final int PAYLOAD_HASH_FIELD_NUMBER = 8;
  private com.google.protobuf.ByteString payloadHash_;
  /**
   * <code>bytes payload_hash = 8;</code>
   * @return The payloadHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayloadHash() {
    return payloadHash_;
  }
  /**
   * <code>bytes payload_hash = 8;</code>
   * @param value The payloadHash to set.
   */
  private void setPayloadHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    payloadHash_ = value;
  }
  /**
   * <code>bytes payload_hash = 8;</code>
   */
  private void clearPayloadHash() {

    payloadHash_ = getDefaultInstance().getPayloadHash();
  }

  public static final int SIGNATURE_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString signature_;
  /**
   * <code>bytes signature = 9;</code>
   * @return The signature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSignature() {
    return signature_;
  }
  /**
   * <code>bytes signature = 9;</code>
   * @param value The signature to set.
   */
  private void setSignature(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    signature_ = value;
  }
  /**
   * <code>bytes signature = 9;</code>
   */
  private void clearSignature() {

    signature_ = getDefaultInstance().getSignature();
  }

  public static me.zayedbinhasan.digitaldelta.proto.Mutation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Mutation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Mutation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Mutation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Mutation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Mutation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Mutation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Mutation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.Mutation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.Mutation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Mutation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Mutation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.Mutation prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.Mutation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.Mutation, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.Mutation)
      me.zayedbinhasan.digitaldelta.proto.MutationOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.Mutation.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string mutation_id = 1;</code>
     * @return The mutationId.
     */
    @java.lang.Override
    public java.lang.String getMutationId() {
      return instance.getMutationId();
    }
    /**
     * <code>string mutation_id = 1;</code>
     * @return The bytes for mutationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMutationIdBytes() {
      return instance.getMutationIdBytes();
    }
    /**
     * <code>string mutation_id = 1;</code>
     * @param value The mutationId to set.
     * @return This builder for chaining.
     */
    public Builder setMutationId(
        java.lang.String value) {
      copyOnWrite();
      instance.setMutationId(value);
      return this;
    }
    /**
     * <code>string mutation_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMutationId() {
      copyOnWrite();
      instance.clearMutationId();
      return this;
    }
    /**
     * <code>string mutation_id = 1;</code>
     * @param value The bytes for mutationId to set.
     * @return This builder for chaining.
     */
    public Builder setMutationIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMutationIdBytes(value);
      return this;
    }

    /**
     * <code>string entity_type = 2;</code>
     * @return The entityType.
     */
    @java.lang.Override
    public java.lang.String getEntityType() {
      return instance.getEntityType();
    }
    /**
     * <code>string entity_type = 2;</code>
     * @return The bytes for entityType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEntityTypeBytes() {
      return instance.getEntityTypeBytes();
    }
    /**
     * <code>string entity_type = 2;</code>
     * @param value The entityType to set.
     * @return This builder for chaining.
     */
    public Builder setEntityType(
        java.lang.String value) {
      copyOnWrite();
      instance.setEntityType(value);
      return this;
    }
    /**
     * <code>string entity_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntityType() {
      copyOnWrite();
      instance.clearEntityType();
      return this;
    }
    /**
     * <code>string entity_type = 2;</code>
     * @param value The bytes for entityType to set.
     * @return This builder for chaining.
     */
    public Builder setEntityTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEntityTypeBytes(value);
      return this;
    }

    /**
     * <code>string entity_id = 3;</code>
     * @return The entityId.
     */
    @java.lang.Override
    public java.lang.String getEntityId() {
      return instance.getEntityId();
    }
    /**
     * <code>string entity_id = 3;</code>
     * @return The bytes for entityId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEntityIdBytes() {
      return instance.getEntityIdBytes();
    }
    /**
     * <code>string entity_id = 3;</code>
     * @param value The entityId to set.
     * @return This builder for chaining.
     */
    public Builder setEntityId(
        java.lang.String value) {
      copyOnWrite();
      instance.setEntityId(value);
      return this;
    }
    /**
     * <code>string entity_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntityId() {
      copyOnWrite();
      instance.clearEntityId();
      return this;
    }
    /**
     * <code>string entity_id = 3;</code>
     * @param value The bytes for entityId to set.
     * @return This builder for chaining.
     */
    public Builder setEntityIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEntityIdBytes(value);
      return this;
    }

    @java.lang.Override

    public int getChangedFieldsCount() {
      return instance.getChangedFieldsMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; changed_fields = 4;</code>
     */
    @java.lang.Override

    public boolean containsChangedFields(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return instance.getChangedFieldsMap().containsKey(key);
    }

    public Builder clearChangedFields() {
      copyOnWrite();
      instance.getMutableChangedFieldsMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; changed_fields = 4;</code>
     */

    public Builder removeChangedFields(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      copyOnWrite();
      instance.getMutableChangedFieldsMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getChangedFieldsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getChangedFields() {
      return getChangedFieldsMap();
    }
    /**
     * <code>map&lt;string, string&gt; changed_fields = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getChangedFieldsMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getChangedFieldsMap());
    }
    /**
     * <code>map&lt;string, string&gt; changed_fields = 4;</code>
     */
    @java.lang.Override

    public /* nullable */
java.lang.String getChangedFieldsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          instance.getChangedFieldsMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; changed_fields = 4;</code>
     */
    @java.lang.Override

    public java.lang.String getChangedFieldsOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.String> map =
          instance.getChangedFieldsMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, string&gt; changed_fields = 4;</code>
     */
    public Builder putChangedFields(
        java.lang.String key,
        java.lang.String value) {
      java.lang.Class<?> keyClass = key.getClass();
      java.lang.Class<?> valueClass = value.getClass();
      copyOnWrite();
      instance.getMutableChangedFieldsMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; changed_fields = 4;</code>
     */
    public Builder putAllChangedFields(
        java.util.Map<java.lang.String, java.lang.String> values) {
      copyOnWrite();
      instance.getMutableChangedFieldsMap().putAll(values);
      return this;
    }

    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
     */
    @java.lang.Override
    public boolean hasVectorClock() {
      return instance.hasVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
      return instance.getVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
     */
    public Builder setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.setVectorClock(value);
      return this;
      }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
     */
    public Builder setVectorClock(
        me.zayedbinhasan.digitaldelta.proto.VectorClock.Builder builderForValue) {
      copyOnWrite();
      instance.setVectorClock(builderForValue.build());
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
     */
    public Builder mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.mergeVectorClock(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 5;</code>
     */
    public Builder clearVectorClock() {  copyOnWrite();
      instance.clearVectorClock();
      return this;
    }

    /**
     * <code>string actor_id = 6;</code>
     * @return The actorId.
     */
    @java.lang.Override
    public java.lang.String getActorId() {
      return instance.getActorId();
    }
    /**
     * <code>string actor_id = 6;</code>
     * @return The bytes for actorId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActorIdBytes() {
      return instance.getActorIdBytes();
    }
    /**
     * <code>string actor_id = 6;</code>
     * @param value The actorId to set.
     * @return This builder for chaining.
     */
    public Builder setActorId(
        java.lang.String value) {
      copyOnWrite();
      instance.setActorId(value);
      return this;
    }
    /**
     * <code>string actor_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearActorId() {
      copyOnWrite();
      instance.clearActorId();
      return this;
    }
    /**
     * <code>string actor_id = 6;</code>
     * @param value The bytes for actorId to set.
     * @return This builder for chaining.
     */
    public Builder setActorIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setActorIdBytes(value);
      return this;
    }

    /**
     * <code>uint64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return instance.getTimestamp();
    }
    /**
     * <code>uint64 timestamp = 7;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      copyOnWrite();
      instance.setTimestamp(value);
      return this;
    }
    /**
     * <code>uint64 timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      copyOnWrite();
      instance.clearTimestamp();
      return this;
    }

    /**
     * <code>bytes payload_hash = 8;</code>
     * @return The payloadHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayloadHash() {
      return instance.getPayloadHash();
    }
    /**
     * <code>bytes payload_hash = 8;</code>
     * @param value The payloadHash to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPayloadHash(value);
      return this;
    }
    /**
     * <code>bytes payload_hash = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayloadHash() {
      copyOnWrite();
      instance.clearPayloadHash();
      return this;
    }

    /**
     * <code>bytes signature = 9;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return instance.getSignature();
    }
    /**
     * <code>bytes signature = 9;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSignature(value);
      return this;
    }
    /**
     * <code>bytes signature = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      copyOnWrite();
      instance.clearSignature();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.Mutation)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.Mutation();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "mutationId_",
            "entityType_",
            "entityId_",
            "changedFields_",
            ChangedFieldsDefaultEntryHolder.defaultEntry,
            "vectorClock_",
            "actorId_",
            "timestamp_",
            "payloadHash_",
            "signature_",
          };
          java.lang.String info =
              "\u0000\t\u0000\u0001\u0001\t\t\u0001\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u00042\u0005\u1009\u0000\u0006\u0208\u0007\u0003\b\n\t\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.Mutation> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.Mutation.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.Mutation>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.Mutation)
  private static final me.zayedbinhasan.digitaldelta.proto.Mutation DEFAULT_INSTANCE;
  static {
    Mutation defaultInstance = new Mutation();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Mutation.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.Mutation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Mutation> PARSER;

  public static com.google.protobuf.Parser<Mutation> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

