// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: routing.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface NetworkNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.NetworkNode)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.digitaldelta.v1.NodeType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.digitaldelta.v1.NodeType type = 3;</code>
   * @return The type.
   */
  me.zayedbinhasan.digitaldelta.proto.NodeType getType();

  /**
   * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
   * @return The location.
   */
  me.zayedbinhasan.digitaldelta.proto.GeoLocation getLocation();
}
