// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: routing.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.NetworkNode}
 */
public  final class NetworkNode extends
    com.google.protobuf.GeneratedMessageLite<
        NetworkNode, NetworkNode.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.NetworkNode)
    NetworkNodeOrBuilder {
  private NetworkNode() {
    nodeId_ = "";
    name_ = "";
  }
  private int bitField0_;
  public static final int NODE_ID_FIELD_NUMBER = 1;
  private java.lang.String nodeId_;
  /**
   * <code>string node_id = 1;</code>
   * @return The nodeId.
   */
  @java.lang.Override
  public java.lang.String getNodeId() {
    return nodeId_;
  }
  /**
   * <code>string node_id = 1;</code>
   * @return The bytes for nodeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(nodeId_);
  }
  /**
   * <code>string node_id = 1;</code>
   * @param value The nodeId to set.
   */
  private void setNodeId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    nodeId_ = value;
  }
  /**
   * <code>string node_id = 1;</code>
   */
  private void clearNodeId() {

    nodeId_ = getDefaultInstance().getNodeId();
  }
  /**
   * <code>string node_id = 1;</code>
   * @param value The bytes for nodeId to set.
   */
  private void setNodeIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    nodeId_ = value.toStringUtf8();

  }

  public static final int NAME_FIELD_NUMBER = 2;
  private java.lang.String name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 2;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <code>string name = 2;</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 2;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <code>.digitaldelta.v1.NodeType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.digitaldelta.v1.NodeType type = 3;</code>
   * @return The type.
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.NodeType getType() {
    me.zayedbinhasan.digitaldelta.proto.NodeType result = me.zayedbinhasan.digitaldelta.proto.NodeType.forNumber(type_);
    return result == null ? me.zayedbinhasan.digitaldelta.proto.NodeType.UNRECOGNIZED : result;
  }
  /**
   * <code>.digitaldelta.v1.NodeType type = 3;</code>
   * @param value The enum numeric value on the wire for type to set.
   */
  private void setTypeValue(int value) {
      type_ = value;
  }
  /**
   * <code>.digitaldelta.v1.NodeType type = 3;</code>
   * @param value The type to set.
   */
  private void setType(me.zayedbinhasan.digitaldelta.proto.NodeType value) {
    type_ = value.getNumber();

  }
  /**
   * <code>.digitaldelta.v1.NodeType type = 3;</code>
   */
  private void clearType() {

    type_ = 0;
  }

  public static final int LOCATION_FIELD_NUMBER = 4;
  private me.zayedbinhasan.digitaldelta.proto.GeoLocation location_;
  /**
   * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
   */
  @java.lang.Override
  public boolean hasLocation() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.GeoLocation getLocation() {
    return location_ == null ? me.zayedbinhasan.digitaldelta.proto.GeoLocation.getDefaultInstance() : location_;
  }
  /**
   * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
   */
  private void setLocation(me.zayedbinhasan.digitaldelta.proto.GeoLocation value) {
    value.getClass();
  location_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeLocation(me.zayedbinhasan.digitaldelta.proto.GeoLocation value) {
    value.getClass();
  if (location_ != null &&
        location_ != me.zayedbinhasan.digitaldelta.proto.GeoLocation.getDefaultInstance()) {
      location_ =
        me.zayedbinhasan.digitaldelta.proto.GeoLocation.newBuilder(location_).mergeFrom(value).buildPartial();
    } else {
      location_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
   */
  private void clearLocation() {  location_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.NetworkNode prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.NetworkNode}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.NetworkNode, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.NetworkNode)
      me.zayedbinhasan.digitaldelta.proto.NetworkNodeOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.NetworkNode.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string node_id = 1;</code>
     * @return The nodeId.
     */
    @java.lang.Override
    public java.lang.String getNodeId() {
      return instance.getNodeId();
    }
    /**
     * <code>string node_id = 1;</code>
     * @return The bytes for nodeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      return instance.getNodeIdBytes();
    }
    /**
     * <code>string node_id = 1;</code>
     * @param value The nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeId(
        java.lang.String value) {
      copyOnWrite();
      instance.setNodeId(value);
      return this;
    }
    /**
     * <code>string node_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNodeId() {
      copyOnWrite();
      instance.clearNodeId();
      return this;
    }
    /**
     * <code>string node_id = 1;</code>
     * @param value The bytes for nodeId to set.
     * @return This builder for chaining.
     */
    public Builder setNodeIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNodeIdBytes(value);
      return this;
    }

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>.digitaldelta.v1.NodeType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return instance.getTypeValue();
    }
    /**
     * <code>.digitaldelta.v1.NodeType type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      copyOnWrite();
      instance.setTypeValue(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.NodeType type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.NodeType getType() {
      return instance.getType();
    }
    /**
     * <code>.digitaldelta.v1.NodeType type = 3;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setType(me.zayedbinhasan.digitaldelta.proto.NodeType value) {
      copyOnWrite();
      instance.setType(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.NodeType type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      copyOnWrite();
      instance.clearType();
      return this;
    }

    /**
     * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
     */
    @java.lang.Override
    public boolean hasLocation() {
      return instance.hasLocation();
    }
    /**
     * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.GeoLocation getLocation() {
      return instance.getLocation();
    }
    /**
     * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
     */
    public Builder setLocation(me.zayedbinhasan.digitaldelta.proto.GeoLocation value) {
      copyOnWrite();
      instance.setLocation(value);
      return this;
      }
    /**
     * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
     */
    public Builder setLocation(
        me.zayedbinhasan.digitaldelta.proto.GeoLocation.Builder builderForValue) {
      copyOnWrite();
      instance.setLocation(builderForValue.build());
      return this;
    }
    /**
     * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
     */
    public Builder mergeLocation(me.zayedbinhasan.digitaldelta.proto.GeoLocation value) {
      copyOnWrite();
      instance.mergeLocation(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.GeoLocation location = 4;</code>
     */
    public Builder clearLocation() {  copyOnWrite();
      instance.clearLocation();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.NetworkNode)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.NetworkNode();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "nodeId_",
            "name_",
            "type_",
            "location_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\f\u0004\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.NetworkNode> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.NetworkNode.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.NetworkNode>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.NetworkNode)
  private static final me.zayedbinhasan.digitaldelta.proto.NetworkNode DEFAULT_INSTANCE;
  static {
    NetworkNode defaultInstance = new NetworkNode();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      NetworkNode.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.NetworkNode getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<NetworkNode> PARSER;

  public static com.google.protobuf.Parser<NetworkNode> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

