// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: routing.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface NetworkEdgeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.NetworkEdge)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string edge_id = 1;</code>
   * @return The edgeId.
   */
  java.lang.String getEdgeId();
  /**
   * <code>string edge_id = 1;</code>
   * @return The bytes for edgeId.
   */
  com.google.protobuf.ByteString
      getEdgeIdBytes();

  /**
   * <code>string source_id = 2;</code>
   * @return The sourceId.
   */
  java.lang.String getSourceId();
  /**
   * <code>string source_id = 2;</code>
   * @return The bytes for sourceId.
   */
  com.google.protobuf.ByteString
      getSourceIdBytes();

  /**
   * <code>string target_id = 3;</code>
   * @return The targetId.
   */
  java.lang.String getTargetId();
  /**
   * <code>string target_id = 3;</code>
   * @return The bytes for targetId.
   */
  com.google.protobuf.ByteString
      getTargetIdBytes();

  /**
   * <code>.digitaldelta.v1.EdgeType type = 4;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.digitaldelta.v1.EdgeType type = 4;</code>
   * @return The type.
   */
  me.zayedbinhasan.digitaldelta.proto.EdgeType getType();

  /**
   * <code>int32 base_weight_mins = 5;</code>
   * @return The baseWeightMins.
   */
  int getBaseWeightMins();

  /**
   * <code>float risk_score = 6;</code>
   * @return The riskScore.
   */
  float getRiskScore();

  /**
   * <code>bool is_flooded = 7;</code>
   * @return The isFlooded.
   */
  boolean getIsFlooded();

  /**
   * <code>bool is_impassable = 8;</code>
   * @return The isImpassable.
   */
  boolean getIsImpassable();

  /**
   * <code>uint64 last_updated = 9;</code>
   * @return The lastUpdated.
   */
  long getLastUpdated();

  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 10;</code>
   * @return Whether the vectorClock field is set.
   */
  boolean hasVectorClock();
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 10;</code>
   * @return The vectorClock.
   */
  me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock();
}
