// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: routing.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf enum {@code digitaldelta.v1.NodeType}
 */
public enum NodeType
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>NODE_TYPE_UNSPECIFIED = 0;</code>
   */
  NODE_TYPE_UNSPECIFIED(0),
  /**
   * <code>CENTRAL_COMMAND = 1;</code>
   */
  CENTRAL_COMMAND(1),
  /**
   * <code>SUPPLY_DROP = 2;</code>
   */
  SUPPLY_DROP(2),
  /**
   * <code>RELIEF_CAMP = 3;</code>
   */
  RELIEF_CAMP(3),
  /**
   * <code>WAYPOINT = 4;</code>
   */
  WAYPOINT(4),
  /**
   * <code>HOSPITAL = 5;</code>
   */
  HOSPITAL(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NODE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int NODE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>CENTRAL_COMMAND = 1;</code>
   */
  public static final int CENTRAL_COMMAND_VALUE = 1;
  /**
   * <code>SUPPLY_DROP = 2;</code>
   */
  public static final int SUPPLY_DROP_VALUE = 2;
  /**
   * <code>RELIEF_CAMP = 3;</code>
   */
  public static final int RELIEF_CAMP_VALUE = 3;
  /**
   * <code>WAYPOINT = 4;</code>
   */
  public static final int WAYPOINT_VALUE = 4;
  /**
   * <code>HOSPITAL = 5;</code>
   */
  public static final int HOSPITAL_VALUE = 5;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static NodeType valueOf(int value) {
    return forNumber(value);
  }

  public static NodeType forNumber(int value) {
    switch (value) {
      case 0: return NODE_TYPE_UNSPECIFIED;
      case 1: return CENTRAL_COMMAND;
      case 2: return SUPPLY_DROP;
      case 3: return RELIEF_CAMP;
      case 4: return WAYPOINT;
      case 5: return HOSPITAL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<NodeType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      NodeType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<NodeType>() {
          @java.lang.Override
          public NodeType findValueByNumber(int number) {
            return NodeType.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return NodeTypeVerifier.INSTANCE;
  }

  private static final class NodeTypeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new NodeTypeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return NodeType.forNumber(number) != null;
          }
        };

  private final int value;

  private NodeType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:digitaldelta.v1.NodeType)
}

