// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.OfflineLoginRequest}
 */
public  final class OfflineLoginRequest extends
    com.google.protobuf.GeneratedMessageLite<
        OfflineLoginRequest, OfflineLoginRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.OfflineLoginRequest)
    OfflineLoginRequestOrBuilder {
  private OfflineLoginRequest() {
    userId_ = "";
    deviceId_ = "";
    otpCode_ = "";
  }
  public static final int USER_ID_FIELD_NUMBER = 1;
  private java.lang.String userId_;
  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    return userId_;
  }
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userId_);
  }
  /**
   * <code>string user_id = 1;</code>
   * @param value The userId to set.
   */
  private void setUserId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    userId_ = value;
  }
  /**
   * <code>string user_id = 1;</code>
   */
  private void clearUserId() {

    userId_ = getDefaultInstance().getUserId();
  }
  /**
   * <code>string user_id = 1;</code>
   * @param value The bytes for userId to set.
   */
  private void setUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userId_ = value.toStringUtf8();

  }

  public static final int DEVICE_ID_FIELD_NUMBER = 2;
  private java.lang.String deviceId_;
  /**
   * <code>string device_id = 2;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    return deviceId_;
  }
  /**
   * <code>string device_id = 2;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
  }
  /**
   * <code>string device_id = 2;</code>
   * @param value The deviceId to set.
   */
  private void setDeviceId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    deviceId_ = value;
  }
  /**
   * <code>string device_id = 2;</code>
   */
  private void clearDeviceId() {

    deviceId_ = getDefaultInstance().getDeviceId();
  }
  /**
   * <code>string device_id = 2;</code>
   * @param value The bytes for deviceId to set.
   */
  private void setDeviceIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    deviceId_ = value.toStringUtf8();

  }

  public static final int OTP_CODE_FIELD_NUMBER = 3;
  private java.lang.String otpCode_;
  /**
   * <code>string otp_code = 3;</code>
   * @return The otpCode.
   */
  @java.lang.Override
  public java.lang.String getOtpCode() {
    return otpCode_;
  }
  /**
   * <code>string otp_code = 3;</code>
   * @return The bytes for otpCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOtpCodeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(otpCode_);
  }
  /**
   * <code>string otp_code = 3;</code>
   * @param value The otpCode to set.
   */
  private void setOtpCode(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    otpCode_ = value;
  }
  /**
   * <code>string otp_code = 3;</code>
   */
  private void clearOtpCode() {

    otpCode_ = getDefaultInstance().getOtpCode();
  }
  /**
   * <code>string otp_code = 3;</code>
   * @param value The bytes for otpCode to set.
   */
  private void setOtpCodeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    otpCode_ = value.toStringUtf8();

  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 4;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }
  /**
   * <code>uint64 timestamp = 4;</code>
   * @param value The timestamp to set.
   */
  private void setTimestamp(long value) {
    
    timestamp_ = value;
  }
  /**
   * <code>uint64 timestamp = 4;</code>
   */
  private void clearTimestamp() {

    timestamp_ = 0L;
  }

  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.OfflineLoginRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.OfflineLoginRequest)
      me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequestOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      return instance.getUserId();
    }
    /**
     * <code>string user_id = 1;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return instance.getUserIdBytes();
    }
    /**
     * <code>string user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserId(value);
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      copyOnWrite();
      instance.clearUserId();
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIdBytes(value);
      return this;
    }

    /**
     * <code>string device_id = 2;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return instance.getDeviceId();
    }
    /**
     * <code>string device_id = 2;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return instance.getDeviceIdBytes();
    }
    /**
     * <code>string device_id = 2;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDeviceId(value);
      return this;
    }
    /**
     * <code>string device_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      copyOnWrite();
      instance.clearDeviceId();
      return this;
    }
    /**
     * <code>string device_id = 2;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceIdBytes(value);
      return this;
    }

    /**
     * <code>string otp_code = 3;</code>
     * @return The otpCode.
     */
    @java.lang.Override
    public java.lang.String getOtpCode() {
      return instance.getOtpCode();
    }
    /**
     * <code>string otp_code = 3;</code>
     * @return The bytes for otpCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOtpCodeBytes() {
      return instance.getOtpCodeBytes();
    }
    /**
     * <code>string otp_code = 3;</code>
     * @param value The otpCode to set.
     * @return This builder for chaining.
     */
    public Builder setOtpCode(
        java.lang.String value) {
      copyOnWrite();
      instance.setOtpCode(value);
      return this;
    }
    /**
     * <code>string otp_code = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOtpCode() {
      copyOnWrite();
      instance.clearOtpCode();
      return this;
    }
    /**
     * <code>string otp_code = 3;</code>
     * @param value The bytes for otpCode to set.
     * @return This builder for chaining.
     */
    public Builder setOtpCodeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOtpCodeBytes(value);
      return this;
    }

    /**
     * <code>uint64 timestamp = 4;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return instance.getTimestamp();
    }
    /**
     * <code>uint64 timestamp = 4;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      copyOnWrite();
      instance.setTimestamp(value);
      return this;
    }
    /**
     * <code>uint64 timestamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      copyOnWrite();
      instance.clearTimestamp();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.OfflineLoginRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "userId_",
            "deviceId_",
            "otpCode_",
            "timestamp_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0003";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.OfflineLoginRequest)
  private static final me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest DEFAULT_INSTANCE;
  static {
    OfflineLoginRequest defaultInstance = new OfflineLoginRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      OfflineLoginRequest.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<OfflineLoginRequest> PARSER;

  public static com.google.protobuf.Parser<OfflineLoginRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

