// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf enum {@code digitaldelta.v1.OfflineState}
 */
public enum OfflineState
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>OFFLINE_STATE_UNSPECIFIED = 0;</code>
   */
  OFFLINE_STATE_UNSPECIFIED(0),
  /**
   * <code>OFFLINE = 1;</code>
   */
  OFFLINE(1),
  /**
   * <code>SYNCING = 2;</code>
   */
  SYNCING(2),
  /**
   * <code>CONFLICT_DETECTED = 3;</code>
   */
  CONFLICT_DETECTED(3),
  /**
   * <code>VERIFIED = 4;</code>
   */
  VERIFIED(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OFFLINE_STATE_UNSPECIFIED = 0;</code>
   */
  public static final int OFFLINE_STATE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>OFFLINE = 1;</code>
   */
  public static final int OFFLINE_VALUE = 1;
  /**
   * <code>SYNCING = 2;</code>
   */
  public static final int SYNCING_VALUE = 2;
  /**
   * <code>CONFLICT_DETECTED = 3;</code>
   */
  public static final int CONFLICT_DETECTED_VALUE = 3;
  /**
   * <code>VERIFIED = 4;</code>
   */
  public static final int VERIFIED_VALUE = 4;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static OfflineState valueOf(int value) {
    return forNumber(value);
  }

  public static OfflineState forNumber(int value) {
    switch (value) {
      case 0: return OFFLINE_STATE_UNSPECIFIED;
      case 1: return OFFLINE;
      case 2: return SYNCING;
      case 3: return CONFLICT_DETECTED;
      case 4: return VERIFIED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OfflineState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      OfflineState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OfflineState>() {
          @java.lang.Override
          public OfflineState findValueByNumber(int number) {
            return OfflineState.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return OfflineStateVerifier.INSTANCE;
  }

  private static final class OfflineStateVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new OfflineStateVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return OfflineState.forNumber(number) != null;
          }
        };

  private final int value;

  private OfflineState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:digitaldelta.v1.OfflineState)
}

