// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.OfflineLoginResponse}
 */
public  final class OfflineLoginResponse extends
    com.google.protobuf.GeneratedMessageLite<
        OfflineLoginResponse, OfflineLoginResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.OfflineLoginResponse)
    OfflineLoginResponseOrBuilder {
  private OfflineLoginResponse() {
    reason_ = "";
  }
  public static final int OK_FIELD_NUMBER = 1;
  private boolean ok_;
  /**
   * <code>bool ok = 1;</code>
   * @return The ok.
   */
  @java.lang.Override
  public boolean getOk() {
    return ok_;
  }
  /**
   * <code>bool ok = 1;</code>
   * @param value The ok to set.
   */
  private void setOk(boolean value) {
    
    ok_ = value;
  }
  /**
   * <code>bool ok = 1;</code>
   */
  private void clearOk() {

    ok_ = false;
  }

  public static final int REASON_FIELD_NUMBER = 2;
  private java.lang.String reason_;
  /**
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  @java.lang.Override
  public java.lang.String getReason() {
    return reason_;
  }
  /**
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reason_);
  }
  /**
   * <code>string reason = 2;</code>
   * @param value The reason to set.
   */
  private void setReason(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    reason_ = value;
  }
  /**
   * <code>string reason = 2;</code>
   */
  private void clearReason() {

    reason_ = getDefaultInstance().getReason();
  }
  /**
   * <code>string reason = 2;</code>
   * @param value The bytes for reason to set.
   */
  private void setReasonBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reason_ = value.toStringUtf8();

  }

  public static final int ROLE_FIELD_NUMBER = 3;
  private int role_;
  /**
   * <code>.digitaldelta.v1.UserRole role = 3;</code>
   * @return The enum numeric value on the wire for role.
   */
  @java.lang.Override
  public int getRoleValue() {
    return role_;
  }
  /**
   * <code>.digitaldelta.v1.UserRole role = 3;</code>
   * @return The role.
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.UserRole getRole() {
    me.zayedbinhasan.digitaldelta.proto.UserRole result = me.zayedbinhasan.digitaldelta.proto.UserRole.forNumber(role_);
    return result == null ? me.zayedbinhasan.digitaldelta.proto.UserRole.UNRECOGNIZED : result;
  }
  /**
   * <code>.digitaldelta.v1.UserRole role = 3;</code>
   * @param value The enum numeric value on the wire for role to set.
   */
  private void setRoleValue(int value) {
      role_ = value;
  }
  /**
   * <code>.digitaldelta.v1.UserRole role = 3;</code>
   * @param value The role to set.
   */
  private void setRole(me.zayedbinhasan.digitaldelta.proto.UserRole value) {
    role_ = value.getNumber();

  }
  /**
   * <code>.digitaldelta.v1.UserRole role = 3;</code>
   */
  private void clearRole() {

    role_ = 0;
  }

  public static final int SESSION_EXPIRES_AT_FIELD_NUMBER = 4;
  private long sessionExpiresAt_;
  /**
   * <code>uint64 session_expires_at = 4;</code>
   * @return The sessionExpiresAt.
   */
  @java.lang.Override
  public long getSessionExpiresAt() {
    return sessionExpiresAt_;
  }
  /**
   * <code>uint64 session_expires_at = 4;</code>
   * @param value The sessionExpiresAt to set.
   */
  private void setSessionExpiresAt(long value) {
    
    sessionExpiresAt_ = value;
  }
  /**
   * <code>uint64 session_expires_at = 4;</code>
   */
  private void clearSessionExpiresAt() {

    sessionExpiresAt_ = 0L;
  }

  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.OfflineLoginResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.OfflineLoginResponse)
      me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponseOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bool ok = 1;</code>
     * @return The ok.
     */
    @java.lang.Override
    public boolean getOk() {
      return instance.getOk();
    }
    /**
     * <code>bool ok = 1;</code>
     * @param value The ok to set.
     * @return This builder for chaining.
     */
    public Builder setOk(boolean value) {
      copyOnWrite();
      instance.setOk(value);
      return this;
    }
    /**
     * <code>bool ok = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOk() {
      copyOnWrite();
      instance.clearOk();
      return this;
    }

    /**
     * <code>string reason = 2;</code>
     * @return The reason.
     */
    @java.lang.Override
    public java.lang.String getReason() {
      return instance.getReason();
    }
    /**
     * <code>string reason = 2;</code>
     * @return The bytes for reason.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonBytes() {
      return instance.getReasonBytes();
    }
    /**
     * <code>string reason = 2;</code>
     * @param value The reason to set.
     * @return This builder for chaining.
     */
    public Builder setReason(
        java.lang.String value) {
      copyOnWrite();
      instance.setReason(value);
      return this;
    }
    /**
     * <code>string reason = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReason() {
      copyOnWrite();
      instance.clearReason();
      return this;
    }
    /**
     * <code>string reason = 2;</code>
     * @param value The bytes for reason to set.
     * @return This builder for chaining.
     */
    public Builder setReasonBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReasonBytes(value);
      return this;
    }

    /**
     * <code>.digitaldelta.v1.UserRole role = 3;</code>
     * @return The enum numeric value on the wire for role.
     */
    @java.lang.Override
    public int getRoleValue() {
      return instance.getRoleValue();
    }
    /**
     * <code>.digitaldelta.v1.UserRole role = 3;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleValue(int value) {
      copyOnWrite();
      instance.setRoleValue(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.UserRole role = 3;</code>
     * @return The role.
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.UserRole getRole() {
      return instance.getRole();
    }
    /**
     * <code>.digitaldelta.v1.UserRole role = 3;</code>
     * @param value The enum numeric value on the wire for role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(me.zayedbinhasan.digitaldelta.proto.UserRole value) {
      copyOnWrite();
      instance.setRole(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.UserRole role = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {
      copyOnWrite();
      instance.clearRole();
      return this;
    }

    /**
     * <code>uint64 session_expires_at = 4;</code>
     * @return The sessionExpiresAt.
     */
    @java.lang.Override
    public long getSessionExpiresAt() {
      return instance.getSessionExpiresAt();
    }
    /**
     * <code>uint64 session_expires_at = 4;</code>
     * @param value The sessionExpiresAt to set.
     * @return This builder for chaining.
     */
    public Builder setSessionExpiresAt(long value) {
      copyOnWrite();
      instance.setSessionExpiresAt(value);
      return this;
    }
    /**
     * <code>uint64 session_expires_at = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionExpiresAt() {
      copyOnWrite();
      instance.clearSessionExpiresAt();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.OfflineLoginResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "ok_",
            "reason_",
            "role_",
            "sessionExpiresAt_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0007\u0002\u0208" +
              "\u0003\f\u0004\u0003";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.OfflineLoginResponse)
  private static final me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse DEFAULT_INSTANCE;
  static {
    OfflineLoginResponse defaultInstance = new OfflineLoginResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      OfflineLoginResponse.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.OfflineLoginResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<OfflineLoginResponse> PARSER;

  public static com.google.protobuf.Parser<OfflineLoginResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

