// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface OfflineLoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.OfflineLoginResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool ok = 1;</code>
   * @return The ok.
   */
  boolean getOk();

  /**
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>.digitaldelta.v1.UserRole role = 3;</code>
   * @return The enum numeric value on the wire for role.
   */
  int getRoleValue();
  /**
   * <code>.digitaldelta.v1.UserRole role = 3;</code>
   * @return The role.
   */
  me.zayedbinhasan.digitaldelta.proto.UserRole getRole();

  /**
   * <code>uint64 session_expires_at = 4;</code>
   * @return The sessionExpiresAt.
   */
  long getSessionExpiresAt();
}
