// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface OfflineLoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.OfflineLoginRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string device_id = 2;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 2;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>string otp_code = 3;</code>
   * @return The otpCode.
   */
  java.lang.String getOtpCode();
  /**
   * <code>string otp_code = 3;</code>
   * @return The bytes for otpCode.
   */
  com.google.protobuf.ByteString
      getOtpCodeBytes();

  /**
   * <code>uint64 timestamp = 4;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
