// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pod.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.PODPayload}
 */
public  final class PODPayload extends
    com.google.protobuf.GeneratedMessageLite<
        PODPayload, PODPayload.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.PODPayload)
    PODPayloadOrBuilder {
  private PODPayload() {
    deliveryId_ = "";
    senderUserId_ = "";
    recipientUserId_ = "";
    payloadHash_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int DELIVERY_ID_FIELD_NUMBER = 1;
  private java.lang.String deliveryId_;
  /**
   * <code>string delivery_id = 1;</code>
   * @return The deliveryId.
   */
  @java.lang.Override
  public java.lang.String getDeliveryId() {
    return deliveryId_;
  }
  /**
   * <code>string delivery_id = 1;</code>
   * @return The bytes for deliveryId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeliveryIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deliveryId_);
  }
  /**
   * <code>string delivery_id = 1;</code>
   * @param value The deliveryId to set.
   */
  private void setDeliveryId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    deliveryId_ = value;
  }
  /**
   * <code>string delivery_id = 1;</code>
   */
  private void clearDeliveryId() {

    deliveryId_ = getDefaultInstance().getDeliveryId();
  }
  /**
   * <code>string delivery_id = 1;</code>
   * @param value The bytes for deliveryId to set.
   */
  private void setDeliveryIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    deliveryId_ = value.toStringUtf8();

  }

  public static final int SENDER_USER_ID_FIELD_NUMBER = 2;
  private java.lang.String senderUserId_;
  /**
   * <code>string sender_user_id = 2;</code>
   * @return The senderUserId.
   */
  @java.lang.Override
  public java.lang.String getSenderUserId() {
    return senderUserId_;
  }
  /**
   * <code>string sender_user_id = 2;</code>
   * @return The bytes for senderUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(senderUserId_);
  }
  /**
   * <code>string sender_user_id = 2;</code>
   * @param value The senderUserId to set.
   */
  private void setSenderUserId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    senderUserId_ = value;
  }
  /**
   * <code>string sender_user_id = 2;</code>
   */
  private void clearSenderUserId() {

    senderUserId_ = getDefaultInstance().getSenderUserId();
  }
  /**
   * <code>string sender_user_id = 2;</code>
   * @param value The bytes for senderUserId to set.
   */
  private void setSenderUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    senderUserId_ = value.toStringUtf8();

  }

  public static final int RECIPIENT_USER_ID_FIELD_NUMBER = 3;
  private java.lang.String recipientUserId_;
  /**
   * <code>string recipient_user_id = 3;</code>
   * @return The recipientUserId.
   */
  @java.lang.Override
  public java.lang.String getRecipientUserId() {
    return recipientUserId_;
  }
  /**
   * <code>string recipient_user_id = 3;</code>
   * @return The bytes for recipientUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecipientUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(recipientUserId_);
  }
  /**
   * <code>string recipient_user_id = 3;</code>
   * @param value The recipientUserId to set.
   */
  private void setRecipientUserId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    recipientUserId_ = value;
  }
  /**
   * <code>string recipient_user_id = 3;</code>
   */
  private void clearRecipientUserId() {

    recipientUserId_ = getDefaultInstance().getRecipientUserId();
  }
  /**
   * <code>string recipient_user_id = 3;</code>
   * @param value The bytes for recipientUserId to set.
   */
  private void setRecipientUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    recipientUserId_ = value.toStringUtf8();

  }

  public static final int PAYLOAD_HASH_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString payloadHash_;
  /**
   * <code>bytes payload_hash = 4;</code>
   * @return The payloadHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayloadHash() {
    return payloadHash_;
  }
  /**
   * <code>bytes payload_hash = 4;</code>
   * @param value The payloadHash to set.
   */
  private void setPayloadHash(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    payloadHash_ = value;
  }
  /**
   * <code>bytes payload_hash = 4;</code>
   */
  private void clearPayloadHash() {

    payloadHash_ = getDefaultInstance().getPayloadHash();
  }

  public static final int NONCE_FIELD_NUMBER = 5;
  private long nonce_;
  /**
   * <code>uint64 nonce = 5;</code>
   * @return The nonce.
   */
  @java.lang.Override
  public long getNonce() {
    return nonce_;
  }
  /**
   * <code>uint64 nonce = 5;</code>
   * @param value The nonce to set.
   */
  private void setNonce(long value) {
    
    nonce_ = value;
  }
  /**
   * <code>uint64 nonce = 5;</code>
   */
  private void clearNonce() {

    nonce_ = 0L;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }
  /**
   * <code>uint64 timestamp = 6;</code>
   * @param value The timestamp to set.
   */
  private void setTimestamp(long value) {
    
    timestamp_ = value;
  }
  /**
   * <code>uint64 timestamp = 6;</code>
   */
  private void clearTimestamp() {

    timestamp_ = 0L;
  }

  public static me.zayedbinhasan.digitaldelta.proto.PODPayload parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODPayload parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODPayload parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODPayload parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODPayload parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODPayload parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODPayload parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODPayload parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.PODPayload parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.PODPayload parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODPayload parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODPayload parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.PODPayload prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.PODPayload}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.PODPayload, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.PODPayload)
      me.zayedbinhasan.digitaldelta.proto.PODPayloadOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.PODPayload.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string delivery_id = 1;</code>
     * @return The deliveryId.
     */
    @java.lang.Override
    public java.lang.String getDeliveryId() {
      return instance.getDeliveryId();
    }
    /**
     * <code>string delivery_id = 1;</code>
     * @return The bytes for deliveryId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeliveryIdBytes() {
      return instance.getDeliveryIdBytes();
    }
    /**
     * <code>string delivery_id = 1;</code>
     * @param value The deliveryId to set.
     * @return This builder for chaining.
     */
    public Builder setDeliveryId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDeliveryId(value);
      return this;
    }
    /**
     * <code>string delivery_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeliveryId() {
      copyOnWrite();
      instance.clearDeliveryId();
      return this;
    }
    /**
     * <code>string delivery_id = 1;</code>
     * @param value The bytes for deliveryId to set.
     * @return This builder for chaining.
     */
    public Builder setDeliveryIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeliveryIdBytes(value);
      return this;
    }

    /**
     * <code>string sender_user_id = 2;</code>
     * @return The senderUserId.
     */
    @java.lang.Override
    public java.lang.String getSenderUserId() {
      return instance.getSenderUserId();
    }
    /**
     * <code>string sender_user_id = 2;</code>
     * @return The bytes for senderUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderUserIdBytes() {
      return instance.getSenderUserIdBytes();
    }
    /**
     * <code>string sender_user_id = 2;</code>
     * @param value The senderUserId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSenderUserId(value);
      return this;
    }
    /**
     * <code>string sender_user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderUserId() {
      copyOnWrite();
      instance.clearSenderUserId();
      return this;
    }
    /**
     * <code>string sender_user_id = 2;</code>
     * @param value The bytes for senderUserId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSenderUserIdBytes(value);
      return this;
    }

    /**
     * <code>string recipient_user_id = 3;</code>
     * @return The recipientUserId.
     */
    @java.lang.Override
    public java.lang.String getRecipientUserId() {
      return instance.getRecipientUserId();
    }
    /**
     * <code>string recipient_user_id = 3;</code>
     * @return The bytes for recipientUserId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRecipientUserIdBytes() {
      return instance.getRecipientUserIdBytes();
    }
    /**
     * <code>string recipient_user_id = 3;</code>
     * @param value The recipientUserId to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRecipientUserId(value);
      return this;
    }
    /**
     * <code>string recipient_user_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipientUserId() {
      copyOnWrite();
      instance.clearRecipientUserId();
      return this;
    }
    /**
     * <code>string recipient_user_id = 3;</code>
     * @param value The bytes for recipientUserId to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRecipientUserIdBytes(value);
      return this;
    }

    /**
     * <code>bytes payload_hash = 4;</code>
     * @return The payloadHash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayloadHash() {
      return instance.getPayloadHash();
    }
    /**
     * <code>bytes payload_hash = 4;</code>
     * @param value The payloadHash to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPayloadHash(value);
      return this;
    }
    /**
     * <code>bytes payload_hash = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayloadHash() {
      copyOnWrite();
      instance.clearPayloadHash();
      return this;
    }

    /**
     * <code>uint64 nonce = 5;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public long getNonce() {
      return instance.getNonce();
    }
    /**
     * <code>uint64 nonce = 5;</code>
     * @param value The nonce to set.
     * @return This builder for chaining.
     */
    public Builder setNonce(long value) {
      copyOnWrite();
      instance.setNonce(value);
      return this;
    }
    /**
     * <code>uint64 nonce = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonce() {
      copyOnWrite();
      instance.clearNonce();
      return this;
    }

    /**
     * <code>uint64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return instance.getTimestamp();
    }
    /**
     * <code>uint64 timestamp = 6;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      copyOnWrite();
      instance.setTimestamp(value);
      return this;
    }
    /**
     * <code>uint64 timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      copyOnWrite();
      instance.clearTimestamp();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.PODPayload)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.PODPayload();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "deliveryId_",
            "senderUserId_",
            "recipientUserId_",
            "payloadHash_",
            "nonce_",
            "timestamp_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\n\u0005\u0003\u0006\u0003";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.PODPayload> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.PODPayload.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.PODPayload>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.PODPayload)
  private static final me.zayedbinhasan.digitaldelta.proto.PODPayload DEFAULT_INSTANCE;
  static {
    PODPayload defaultInstance = new PODPayload();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PODPayload.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.PODPayload getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PODPayload> PARSER;

  public static com.google.protobuf.Parser<PODPayload> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

