// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pod.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.PODReceipt}
 */
public  final class PODReceipt extends
    com.google.protobuf.GeneratedMessageLite<
        PODReceipt, PODReceipt.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.PODReceipt)
    PODReceiptOrBuilder {
  private PODReceipt() {
    receiptId_ = "";
    senderSignature_ = com.google.protobuf.ByteString.EMPTY;
    recipientSignature_ = com.google.protobuf.ByteString.EMPTY;
  }
  private int bitField0_;
  public static final int RECEIPT_ID_FIELD_NUMBER = 1;
  private java.lang.String receiptId_;
  /**
   * <code>string receipt_id = 1;</code>
   * @return The receiptId.
   */
  @java.lang.Override
  public java.lang.String getReceiptId() {
    return receiptId_;
  }
  /**
   * <code>string receipt_id = 1;</code>
   * @return The bytes for receiptId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiptIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(receiptId_);
  }
  /**
   * <code>string receipt_id = 1;</code>
   * @param value The receiptId to set.
   */
  private void setReceiptId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    receiptId_ = value;
  }
  /**
   * <code>string receipt_id = 1;</code>
   */
  private void clearReceiptId() {

    receiptId_ = getDefaultInstance().getReceiptId();
  }
  /**
   * <code>string receipt_id = 1;</code>
   * @param value The bytes for receiptId to set.
   */
  private void setReceiptIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    receiptId_ = value.toStringUtf8();

  }

  public static final int PAYLOAD_FIELD_NUMBER = 2;
  private me.zayedbinhasan.digitaldelta.proto.PODPayload payload_;
  /**
   * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
   */
  @java.lang.Override
  public boolean hasPayload() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.PODPayload getPayload() {
    return payload_ == null ? me.zayedbinhasan.digitaldelta.proto.PODPayload.getDefaultInstance() : payload_;
  }
  /**
   * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
   */
  private void setPayload(me.zayedbinhasan.digitaldelta.proto.PODPayload value) {
    value.getClass();
  payload_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergePayload(me.zayedbinhasan.digitaldelta.proto.PODPayload value) {
    value.getClass();
  if (payload_ != null &&
        payload_ != me.zayedbinhasan.digitaldelta.proto.PODPayload.getDefaultInstance()) {
      payload_ =
        me.zayedbinhasan.digitaldelta.proto.PODPayload.newBuilder(payload_).mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
   */
  private void clearPayload() {  payload_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int SENDER_SIGNATURE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString senderSignature_;
  /**
   * <code>bytes sender_signature = 3;</code>
   * @return The senderSignature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSenderSignature() {
    return senderSignature_;
  }
  /**
   * <code>bytes sender_signature = 3;</code>
   * @param value The senderSignature to set.
   */
  private void setSenderSignature(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    senderSignature_ = value;
  }
  /**
   * <code>bytes sender_signature = 3;</code>
   */
  private void clearSenderSignature() {

    senderSignature_ = getDefaultInstance().getSenderSignature();
  }

  public static final int RECIPIENT_SIGNATURE_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString recipientSignature_;
  /**
   * <code>bytes recipient_signature = 4;</code>
   * @return The recipientSignature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRecipientSignature() {
    return recipientSignature_;
  }
  /**
   * <code>bytes recipient_signature = 4;</code>
   * @param value The recipientSignature to set.
   */
  private void setRecipientSignature(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    recipientSignature_ = value;
  }
  /**
   * <code>bytes recipient_signature = 4;</code>
   */
  private void clearRecipientSignature() {

    recipientSignature_ = getDefaultInstance().getRecipientSignature();
  }

  public static final int VERIFIED_FIELD_NUMBER = 5;
  private boolean verified_;
  /**
   * <code>bool verified = 5;</code>
   * @return The verified.
   */
  @java.lang.Override
  public boolean getVerified() {
    return verified_;
  }
  /**
   * <code>bool verified = 5;</code>
   * @param value The verified to set.
   */
  private void setVerified(boolean value) {
    
    verified_ = value;
  }
  /**
   * <code>bool verified = 5;</code>
   */
  private void clearVerified() {

    verified_ = false;
  }

  public static final int VERIFIED_AT_FIELD_NUMBER = 6;
  private long verifiedAt_;
  /**
   * <code>uint64 verified_at = 6;</code>
   * @return The verifiedAt.
   */
  @java.lang.Override
  public long getVerifiedAt() {
    return verifiedAt_;
  }
  /**
   * <code>uint64 verified_at = 6;</code>
   * @param value The verifiedAt to set.
   */
  private void setVerifiedAt(long value) {
    
    verifiedAt_ = value;
  }
  /**
   * <code>uint64 verified_at = 6;</code>
   */
  private void clearVerifiedAt() {

    verifiedAt_ = 0L;
  }

  public static final int VECTOR_CLOCK_FIELD_NUMBER = 7;
  private me.zayedbinhasan.digitaldelta.proto.VectorClock vectorClock_;
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
   */
  @java.lang.Override
  public boolean hasVectorClock() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
    return vectorClock_ == null ? me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance() : vectorClock_;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
   */
  private void setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  vectorClock_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  if (vectorClock_ != null &&
        vectorClock_ != me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance()) {
      vectorClock_ =
        me.zayedbinhasan.digitaldelta.proto.VectorClock.newBuilder(vectorClock_).mergeFrom(value).buildPartial();
    } else {
      vectorClock_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
   */
  private void clearVectorClock() {  vectorClock_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.PODReceipt prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.PODReceipt}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.PODReceipt, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.PODReceipt)
      me.zayedbinhasan.digitaldelta.proto.PODReceiptOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.PODReceipt.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string receipt_id = 1;</code>
     * @return The receiptId.
     */
    @java.lang.Override
    public java.lang.String getReceiptId() {
      return instance.getReceiptId();
    }
    /**
     * <code>string receipt_id = 1;</code>
     * @return The bytes for receiptId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReceiptIdBytes() {
      return instance.getReceiptIdBytes();
    }
    /**
     * <code>string receipt_id = 1;</code>
     * @param value The receiptId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiptId(
        java.lang.String value) {
      copyOnWrite();
      instance.setReceiptId(value);
      return this;
    }
    /**
     * <code>string receipt_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiptId() {
      copyOnWrite();
      instance.clearReceiptId();
      return this;
    }
    /**
     * <code>string receipt_id = 1;</code>
     * @param value The bytes for receiptId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiptIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReceiptIdBytes(value);
      return this;
    }

    /**
     * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
     */
    @java.lang.Override
    public boolean hasPayload() {
      return instance.hasPayload();
    }
    /**
     * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.PODPayload getPayload() {
      return instance.getPayload();
    }
    /**
     * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
     */
    public Builder setPayload(me.zayedbinhasan.digitaldelta.proto.PODPayload value) {
      copyOnWrite();
      instance.setPayload(value);
      return this;
      }
    /**
     * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
     */
    public Builder setPayload(
        me.zayedbinhasan.digitaldelta.proto.PODPayload.Builder builderForValue) {
      copyOnWrite();
      instance.setPayload(builderForValue.build());
      return this;
    }
    /**
     * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
     */
    public Builder mergePayload(me.zayedbinhasan.digitaldelta.proto.PODPayload value) {
      copyOnWrite();
      instance.mergePayload(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
     */
    public Builder clearPayload() {  copyOnWrite();
      instance.clearPayload();
      return this;
    }

    /**
     * <code>bytes sender_signature = 3;</code>
     * @return The senderSignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSenderSignature() {
      return instance.getSenderSignature();
    }
    /**
     * <code>bytes sender_signature = 3;</code>
     * @param value The senderSignature to set.
     * @return This builder for chaining.
     */
    public Builder setSenderSignature(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSenderSignature(value);
      return this;
    }
    /**
     * <code>bytes sender_signature = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderSignature() {
      copyOnWrite();
      instance.clearSenderSignature();
      return this;
    }

    /**
     * <code>bytes recipient_signature = 4;</code>
     * @return The recipientSignature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRecipientSignature() {
      return instance.getRecipientSignature();
    }
    /**
     * <code>bytes recipient_signature = 4;</code>
     * @param value The recipientSignature to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientSignature(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRecipientSignature(value);
      return this;
    }
    /**
     * <code>bytes recipient_signature = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipientSignature() {
      copyOnWrite();
      instance.clearRecipientSignature();
      return this;
    }

    /**
     * <code>bool verified = 5;</code>
     * @return The verified.
     */
    @java.lang.Override
    public boolean getVerified() {
      return instance.getVerified();
    }
    /**
     * <code>bool verified = 5;</code>
     * @param value The verified to set.
     * @return This builder for chaining.
     */
    public Builder setVerified(boolean value) {
      copyOnWrite();
      instance.setVerified(value);
      return this;
    }
    /**
     * <code>bool verified = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVerified() {
      copyOnWrite();
      instance.clearVerified();
      return this;
    }

    /**
     * <code>uint64 verified_at = 6;</code>
     * @return The verifiedAt.
     */
    @java.lang.Override
    public long getVerifiedAt() {
      return instance.getVerifiedAt();
    }
    /**
     * <code>uint64 verified_at = 6;</code>
     * @param value The verifiedAt to set.
     * @return This builder for chaining.
     */
    public Builder setVerifiedAt(long value) {
      copyOnWrite();
      instance.setVerifiedAt(value);
      return this;
    }
    /**
     * <code>uint64 verified_at = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearVerifiedAt() {
      copyOnWrite();
      instance.clearVerifiedAt();
      return this;
    }

    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
     */
    @java.lang.Override
    public boolean hasVectorClock() {
      return instance.hasVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
      return instance.getVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
     */
    public Builder setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.setVectorClock(value);
      return this;
      }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
     */
    public Builder setVectorClock(
        me.zayedbinhasan.digitaldelta.proto.VectorClock.Builder builderForValue) {
      copyOnWrite();
      instance.setVectorClock(builderForValue.build());
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
     */
    public Builder mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.mergeVectorClock(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
     */
    public Builder clearVectorClock() {  copyOnWrite();
      instance.clearVectorClock();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.PODReceipt)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.PODReceipt();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "receiptId_",
            "payload_",
            "senderSignature_",
            "recipientSignature_",
            "verified_",
            "verifiedAt_",
            "vectorClock_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0001\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u1009" +
              "\u0000\u0003\n\u0004\n\u0005\u0007\u0006\u0003\u0007\u1009\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.PODReceipt> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.PODReceipt.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.PODReceipt>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.PODReceipt)
  private static final me.zayedbinhasan.digitaldelta.proto.PODReceipt DEFAULT_INSTANCE;
  static {
    PODReceipt defaultInstance = new PODReceipt();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PODReceipt.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.PODReceipt getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PODReceipt> PARSER;

  public static com.google.protobuf.Parser<PODReceipt> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

