// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pod.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface PODReceiptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.PODReceipt)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string receipt_id = 1;</code>
   * @return The receiptId.
   */
  java.lang.String getReceiptId();
  /**
   * <code>string receipt_id = 1;</code>
   * @return The bytes for receiptId.
   */
  com.google.protobuf.ByteString
      getReceiptIdBytes();

  /**
   * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
   * @return Whether the payload field is set.
   */
  boolean hasPayload();
  /**
   * <code>.digitaldelta.v1.PODPayload payload = 2;</code>
   * @return The payload.
   */
  me.zayedbinhasan.digitaldelta.proto.PODPayload getPayload();

  /**
   * <code>bytes sender_signature = 3;</code>
   * @return The senderSignature.
   */
  com.google.protobuf.ByteString getSenderSignature();

  /**
   * <code>bytes recipient_signature = 4;</code>
   * @return The recipientSignature.
   */
  com.google.protobuf.ByteString getRecipientSignature();

  /**
   * <code>bool verified = 5;</code>
   * @return The verified.
   */
  boolean getVerified();

  /**
   * <code>uint64 verified_at = 6;</code>
   * @return The verifiedAt.
   */
  long getVerifiedAt();

  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
   * @return Whether the vectorClock field is set.
   */
  boolean hasVectorClock();
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 7;</code>
   * @return The vectorClock.
   */
  me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock();
}
