// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: delivery.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf enum {@code digitaldelta.v1.PriorityTier}
 */
public enum PriorityTier
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>PRIORITY_TIER_UNSPECIFIED = 0;</code>
   */
  PRIORITY_TIER_UNSPECIFIED(0),
  /**
   * <code>P0_CRITICAL = 1;</code>
   */
  P0_CRITICAL(1),
  /**
   * <code>P1_HIGH = 2;</code>
   */
  P1_HIGH(2),
  /**
   * <code>P2_STANDARD = 3;</code>
   */
  P2_STANDARD(3),
  /**
   * <code>P3_LOW = 4;</code>
   */
  P3_LOW(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PRIORITY_TIER_UNSPECIFIED = 0;</code>
   */
  public static final int PRIORITY_TIER_UNSPECIFIED_VALUE = 0;
  /**
   * <code>P0_CRITICAL = 1;</code>
   */
  public static final int P0_CRITICAL_VALUE = 1;
  /**
   * <code>P1_HIGH = 2;</code>
   */
  public static final int P1_HIGH_VALUE = 2;
  /**
   * <code>P2_STANDARD = 3;</code>
   */
  public static final int P2_STANDARD_VALUE = 3;
  /**
   * <code>P3_LOW = 4;</code>
   */
  public static final int P3_LOW_VALUE = 4;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PriorityTier valueOf(int value) {
    return forNumber(value);
  }

  public static PriorityTier forNumber(int value) {
    switch (value) {
      case 0: return PRIORITY_TIER_UNSPECIFIED;
      case 1: return P0_CRITICAL;
      case 2: return P1_HIGH;
      case 3: return P2_STANDARD;
      case 4: return P3_LOW;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PriorityTier>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PriorityTier> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PriorityTier>() {
          @java.lang.Override
          public PriorityTier findValueByNumber(int number) {
            return PriorityTier.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return PriorityTierVerifier.INSTANCE;
  }

  private static final class PriorityTierVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new PriorityTierVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return PriorityTier.forNumber(number) != null;
          }
        };

  private final int value;

  private PriorityTier(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:digitaldelta.v1.PriorityTier)
}

