// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sync.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface RegisterNodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.RegisterNodeResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool ok = 1;</code>
   * @return The ok.
   */
  boolean getOk();

  /**
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>uint64 server_time = 3;</code>
   * @return The serverTime.
   */
  long getServerTime();
}
