// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mesh.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface RelayPolicyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.RelayPolicy)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 max_ttl = 1;</code>
   * @return The maxTtl.
   */
  int getMaxTtl();

  /**
   * <code>uint32 max_attempts = 2;</code>
   * @return The maxAttempts.
   */
  int getMaxAttempts();

  /**
   * <code>uint32 base_backoff_ms = 3;</code>
   * @return The baseBackoffMs.
   */
  int getBaseBackoffMs();
}
