// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mesh.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.RelayPolicy}
 */
public  final class RelayPolicy extends
    com.google.protobuf.GeneratedMessageLite<
        RelayPolicy, RelayPolicy.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.RelayPolicy)
    RelayPolicyOrBuilder {
  private RelayPolicy() {
  }
  public static final int MAX_TTL_FIELD_NUMBER = 1;
  private int maxTtl_;
  /**
   * <code>uint32 max_ttl = 1;</code>
   * @return The maxTtl.
   */
  @java.lang.Override
  public int getMaxTtl() {
    return maxTtl_;
  }
  /**
   * <code>uint32 max_ttl = 1;</code>
   * @param value The maxTtl to set.
   */
  private void setMaxTtl(int value) {
    
    maxTtl_ = value;
  }
  /**
   * <code>uint32 max_ttl = 1;</code>
   */
  private void clearMaxTtl() {

    maxTtl_ = 0;
  }

  public static final int MAX_ATTEMPTS_FIELD_NUMBER = 2;
  private int maxAttempts_;
  /**
   * <code>uint32 max_attempts = 2;</code>
   * @return The maxAttempts.
   */
  @java.lang.Override
  public int getMaxAttempts() {
    return maxAttempts_;
  }
  /**
   * <code>uint32 max_attempts = 2;</code>
   * @param value The maxAttempts to set.
   */
  private void setMaxAttempts(int value) {
    
    maxAttempts_ = value;
  }
  /**
   * <code>uint32 max_attempts = 2;</code>
   */
  private void clearMaxAttempts() {

    maxAttempts_ = 0;
  }

  public static final int BASE_BACKOFF_MS_FIELD_NUMBER = 3;
  private int baseBackoffMs_;
  /**
   * <code>uint32 base_backoff_ms = 3;</code>
   * @return The baseBackoffMs.
   */
  @java.lang.Override
  public int getBaseBackoffMs() {
    return baseBackoffMs_;
  }
  /**
   * <code>uint32 base_backoff_ms = 3;</code>
   * @param value The baseBackoffMs to set.
   */
  private void setBaseBackoffMs(int value) {
    
    baseBackoffMs_ = value;
  }
  /**
   * <code>uint32 base_backoff_ms = 3;</code>
   */
  private void clearBaseBackoffMs() {

    baseBackoffMs_ = 0;
  }

  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.RelayPolicy prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.RelayPolicy}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.RelayPolicy, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.RelayPolicy)
      me.zayedbinhasan.digitaldelta.proto.RelayPolicyOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.RelayPolicy.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint32 max_ttl = 1;</code>
     * @return The maxTtl.
     */
    @java.lang.Override
    public int getMaxTtl() {
      return instance.getMaxTtl();
    }
    /**
     * <code>uint32 max_ttl = 1;</code>
     * @param value The maxTtl to set.
     * @return This builder for chaining.
     */
    public Builder setMaxTtl(int value) {
      copyOnWrite();
      instance.setMaxTtl(value);
      return this;
    }
    /**
     * <code>uint32 max_ttl = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxTtl() {
      copyOnWrite();
      instance.clearMaxTtl();
      return this;
    }

    /**
     * <code>uint32 max_attempts = 2;</code>
     * @return The maxAttempts.
     */
    @java.lang.Override
    public int getMaxAttempts() {
      return instance.getMaxAttempts();
    }
    /**
     * <code>uint32 max_attempts = 2;</code>
     * @param value The maxAttempts to set.
     * @return This builder for chaining.
     */
    public Builder setMaxAttempts(int value) {
      copyOnWrite();
      instance.setMaxAttempts(value);
      return this;
    }
    /**
     * <code>uint32 max_attempts = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxAttempts() {
      copyOnWrite();
      instance.clearMaxAttempts();
      return this;
    }

    /**
     * <code>uint32 base_backoff_ms = 3;</code>
     * @return The baseBackoffMs.
     */
    @java.lang.Override
    public int getBaseBackoffMs() {
      return instance.getBaseBackoffMs();
    }
    /**
     * <code>uint32 base_backoff_ms = 3;</code>
     * @param value The baseBackoffMs to set.
     * @return This builder for chaining.
     */
    public Builder setBaseBackoffMs(int value) {
      copyOnWrite();
      instance.setBaseBackoffMs(value);
      return this;
    }
    /**
     * <code>uint32 base_backoff_ms = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBaseBackoffMs() {
      copyOnWrite();
      instance.clearBaseBackoffMs();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.RelayPolicy)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.RelayPolicy();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "maxTtl_",
            "maxAttempts_",
            "baseBackoffMs_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
              "\u0003\u000b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.RelayPolicy> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.RelayPolicy.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.RelayPolicy>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.RelayPolicy)
  private static final me.zayedbinhasan.digitaldelta.proto.RelayPolicy DEFAULT_INSTANCE;
  static {
    RelayPolicy defaultInstance = new RelayPolicy();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RelayPolicy.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.RelayPolicy getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RelayPolicy> PARSER;

  public static com.google.protobuf.Parser<RelayPolicy> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

