// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mesh.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface RelayAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.RelayAck)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string message_id = 1;</code>
   * @return The messageId.
   */
  java.lang.String getMessageId();
  /**
   * <code>string message_id = 1;</code>
   * @return The bytes for messageId.
   */
  com.google.protobuf.ByteString
      getMessageIdBytes();

  /**
   * <code>string node_id = 2;</code>
   * @return The nodeId.
   */
  java.lang.String getNodeId();
  /**
   * <code>string node_id = 2;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>bool accepted = 3;</code>
   * @return The accepted.
   */
  boolean getAccepted();

  /**
   * <code>string reason = 4;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 4;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>uint64 timestamp = 5;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
