// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: routing.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.RouteResult}
 */
public  final class RouteResult extends
    com.google.protobuf.GeneratedMessageLite<
        RouteResult, RouteResult.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.RouteResult)
    RouteResultOrBuilder {
  private RouteResult() {
  }
  private int bitField0_;
  public static final int ROUTE_FIELD_NUMBER = 1;
  private me.zayedbinhasan.digitaldelta.proto.Route route_;
  /**
   * <code>.digitaldelta.v1.Route route = 1;</code>
   */
  @java.lang.Override
  public boolean hasRoute() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.digitaldelta.v1.Route route = 1;</code>
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.Route getRoute() {
    return route_ == null ? me.zayedbinhasan.digitaldelta.proto.Route.getDefaultInstance() : route_;
  }
  /**
   * <code>.digitaldelta.v1.Route route = 1;</code>
   */
  private void setRoute(me.zayedbinhasan.digitaldelta.proto.Route value) {
    value.getClass();
  route_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.digitaldelta.v1.Route route = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeRoute(me.zayedbinhasan.digitaldelta.proto.Route value) {
    value.getClass();
  if (route_ != null &&
        route_ != me.zayedbinhasan.digitaldelta.proto.Route.getDefaultInstance()) {
      route_ =
        me.zayedbinhasan.digitaldelta.proto.Route.newBuilder(route_).mergeFrom(value).buildPartial();
    } else {
      route_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.digitaldelta.v1.Route route = 1;</code>
   */
  private void clearRoute() {  route_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int CONFIDENCE_FIELD_NUMBER = 2;
  private float confidence_;
  /**
   * <code>float confidence = 2;</code>
   * @return The confidence.
   */
  @java.lang.Override
  public float getConfidence() {
    return confidence_;
  }
  /**
   * <code>float confidence = 2;</code>
   * @param value The confidence to set.
   */
  private void setConfidence(float value) {
    
    confidence_ = value;
  }
  /**
   * <code>float confidence = 2;</code>
   */
  private void clearConfidence() {

    confidence_ = 0F;
  }

  public static final int RECOMPUTED_DUE_TO_CHAOS_FIELD_NUMBER = 3;
  private boolean recomputedDueToChaos_;
  /**
   * <code>bool recomputed_due_to_chaos = 3;</code>
   * @return The recomputedDueToChaos.
   */
  @java.lang.Override
  public boolean getRecomputedDueToChaos() {
    return recomputedDueToChaos_;
  }
  /**
   * <code>bool recomputed_due_to_chaos = 3;</code>
   * @param value The recomputedDueToChaos to set.
   */
  private void setRecomputedDueToChaos(boolean value) {
    
    recomputedDueToChaos_ = value;
  }
  /**
   * <code>bool recomputed_due_to_chaos = 3;</code>
   */
  private void clearRecomputedDueToChaos() {

    recomputedDueToChaos_ = false;
  }

  public static me.zayedbinhasan.digitaldelta.proto.RouteResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RouteResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RouteResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RouteResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RouteResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RouteResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RouteResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RouteResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.RouteResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.RouteResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RouteResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.RouteResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.RouteResult prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.RouteResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.RouteResult, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.RouteResult)
      me.zayedbinhasan.digitaldelta.proto.RouteResultOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.RouteResult.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.digitaldelta.v1.Route route = 1;</code>
     */
    @java.lang.Override
    public boolean hasRoute() {
      return instance.hasRoute();
    }
    /**
     * <code>.digitaldelta.v1.Route route = 1;</code>
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.Route getRoute() {
      return instance.getRoute();
    }
    /**
     * <code>.digitaldelta.v1.Route route = 1;</code>
     */
    public Builder setRoute(me.zayedbinhasan.digitaldelta.proto.Route value) {
      copyOnWrite();
      instance.setRoute(value);
      return this;
      }
    /**
     * <code>.digitaldelta.v1.Route route = 1;</code>
     */
    public Builder setRoute(
        me.zayedbinhasan.digitaldelta.proto.Route.Builder builderForValue) {
      copyOnWrite();
      instance.setRoute(builderForValue.build());
      return this;
    }
    /**
     * <code>.digitaldelta.v1.Route route = 1;</code>
     */
    public Builder mergeRoute(me.zayedbinhasan.digitaldelta.proto.Route value) {
      copyOnWrite();
      instance.mergeRoute(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.Route route = 1;</code>
     */
    public Builder clearRoute() {  copyOnWrite();
      instance.clearRoute();
      return this;
    }

    /**
     * <code>float confidence = 2;</code>
     * @return The confidence.
     */
    @java.lang.Override
    public float getConfidence() {
      return instance.getConfidence();
    }
    /**
     * <code>float confidence = 2;</code>
     * @param value The confidence to set.
     * @return This builder for chaining.
     */
    public Builder setConfidence(float value) {
      copyOnWrite();
      instance.setConfidence(value);
      return this;
    }
    /**
     * <code>float confidence = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfidence() {
      copyOnWrite();
      instance.clearConfidence();
      return this;
    }

    /**
     * <code>bool recomputed_due_to_chaos = 3;</code>
     * @return The recomputedDueToChaos.
     */
    @java.lang.Override
    public boolean getRecomputedDueToChaos() {
      return instance.getRecomputedDueToChaos();
    }
    /**
     * <code>bool recomputed_due_to_chaos = 3;</code>
     * @param value The recomputedDueToChaos to set.
     * @return This builder for chaining.
     */
    public Builder setRecomputedDueToChaos(boolean value) {
      copyOnWrite();
      instance.setRecomputedDueToChaos(value);
      return this;
    }
    /**
     * <code>bool recomputed_due_to_chaos = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecomputedDueToChaos() {
      copyOnWrite();
      instance.clearRecomputedDueToChaos();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.RouteResult)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.RouteResult();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "route_",
            "confidence_",
            "recomputedDueToChaos_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
              "\u0001\u0003\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.RouteResult> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.RouteResult.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.RouteResult>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.RouteResult)
  private static final me.zayedbinhasan.digitaldelta.proto.RouteResult DEFAULT_INSTANCE;
  static {
    RouteResult defaultInstance = new RouteResult();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RouteResult.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.RouteResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RouteResult> PARSER;

  public static com.google.protobuf.Parser<RouteResult> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

