// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: routing.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface RouteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.Route)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string route_id = 1;</code>
   * @return The routeId.
   */
  java.lang.String getRouteId();
  /**
   * <code>string route_id = 1;</code>
   * @return The bytes for routeId.
   */
  com.google.protobuf.ByteString
      getRouteIdBytes();

  /**
   * <code>repeated string edge_ids = 2;</code>
   * @return A list containing the edgeIds.
   */
  java.util.List<java.lang.String>
      getEdgeIdsList();
  /**
   * <code>repeated string edge_ids = 2;</code>
   * @return The count of edgeIds.
   */
  int getEdgeIdsCount();
  /**
   * <code>repeated string edge_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The edgeIds at the given index.
   */
  java.lang.String getEdgeIds(int index);
  /**
   * <code>repeated string edge_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The edgeIds at the given index.
   */
  com.google.protobuf.ByteString
      getEdgeIdsBytes(int index);

  /**
   * <code>int32 total_duration_mins = 3;</code>
   * @return The totalDurationMins.
   */
  int getTotalDurationMins();

  /**
   * <code>.digitaldelta.v1.VehicleType vehicle = 4;</code>
   * @return The enum numeric value on the wire for vehicle.
   */
  int getVehicleValue();
  /**
   * <code>.digitaldelta.v1.VehicleType vehicle = 4;</code>
   * @return The vehicle.
   */
  me.zayedbinhasan.digitaldelta.proto.VehicleType getVehicle();

  /**
   * <code>int64 eta_timestamp = 5;</code>
   * @return The etaTimestamp.
   */
  long getEtaTimestamp();

  /**
   * <code>string reason_code = 6;</code>
   * @return The reasonCode.
   */
  java.lang.String getReasonCode();
  /**
   * <code>string reason_code = 6;</code>
   * @return The bytes for reasonCode.
   */
  com.google.protobuf.ByteString
      getReasonCodeBytes();

  /**
   * <code>uint64 updated_at = 7;</code>
   * @return The updatedAt.
   */
  long getUpdatedAt();

  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   * @return Whether the vectorClock field is set.
   */
  boolean hasVectorClock();
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   * @return The vectorClock.
   */
  me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock();
}
