// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: routing.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.Route}
 */
public  final class Route extends
    com.google.protobuf.GeneratedMessageLite<
        Route, Route.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.Route)
    RouteOrBuilder {
  private Route() {
    routeId_ = "";
    edgeIds_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    reasonCode_ = "";
  }
  private int bitField0_;
  public static final int ROUTE_ID_FIELD_NUMBER = 1;
  private java.lang.String routeId_;
  /**
   * <code>string route_id = 1;</code>
   * @return The routeId.
   */
  @java.lang.Override
  public java.lang.String getRouteId() {
    return routeId_;
  }
  /**
   * <code>string route_id = 1;</code>
   * @return The bytes for routeId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRouteIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(routeId_);
  }
  /**
   * <code>string route_id = 1;</code>
   * @param value The routeId to set.
   */
  private void setRouteId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    routeId_ = value;
  }
  /**
   * <code>string route_id = 1;</code>
   */
  private void clearRouteId() {

    routeId_ = getDefaultInstance().getRouteId();
  }
  /**
   * <code>string route_id = 1;</code>
   * @param value The bytes for routeId to set.
   */
  private void setRouteIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    routeId_ = value.toStringUtf8();

  }

  public static final int EDGE_IDS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> edgeIds_;
  /**
   * <code>repeated string edge_ids = 2;</code>
   * @return A list containing the edgeIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getEdgeIdsList() {
    return edgeIds_;
  }
  /**
   * <code>repeated string edge_ids = 2;</code>
   * @return The count of edgeIds.
   */
  @java.lang.Override
  public int getEdgeIdsCount() {
    return edgeIds_.size();
  }
  /**
   * <code>repeated string edge_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The edgeIds at the given index.
   */
  @java.lang.Override
  public java.lang.String getEdgeIds(int index) {
    return edgeIds_.get(index);
  }
  /**
   * <code>repeated string edge_ids = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the edgeIds at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEdgeIdsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        edgeIds_.get(index));
  }
  private void ensureEdgeIdsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        edgeIds_;  if (!tmp.isModifiable()) {
      edgeIds_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string edge_ids = 2;</code>
   * @param index The index to set the value at.
   * @param value The edgeIds to set.
   */
  private void setEdgeIds(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureEdgeIdsIsMutable();
    edgeIds_.set(index, value);
  }
  /**
   * <code>repeated string edge_ids = 2;</code>
   * @param value The edgeIds to add.
   */
  private void addEdgeIds(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureEdgeIdsIsMutable();
    edgeIds_.add(value);
  }
  /**
   * <code>repeated string edge_ids = 2;</code>
   * @param values The edgeIds to add.
   */
  private void addAllEdgeIds(
      java.lang.Iterable<java.lang.String> values) {
    ensureEdgeIdsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, edgeIds_);
  }
  /**
   * <code>repeated string edge_ids = 2;</code>
   */
  private void clearEdgeIds() {
    edgeIds_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string edge_ids = 2;</code>
   * @param value The bytes of the edgeIds to add.
   */
  private void addEdgeIdsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureEdgeIdsIsMutable();
    edgeIds_.add(value.toStringUtf8());
  }

  public static final int TOTAL_DURATION_MINS_FIELD_NUMBER = 3;
  private int totalDurationMins_;
  /**
   * <code>int32 total_duration_mins = 3;</code>
   * @return The totalDurationMins.
   */
  @java.lang.Override
  public int getTotalDurationMins() {
    return totalDurationMins_;
  }
  /**
   * <code>int32 total_duration_mins = 3;</code>
   * @param value The totalDurationMins to set.
   */
  private void setTotalDurationMins(int value) {
    
    totalDurationMins_ = value;
  }
  /**
   * <code>int32 total_duration_mins = 3;</code>
   */
  private void clearTotalDurationMins() {

    totalDurationMins_ = 0;
  }

  public static final int VEHICLE_FIELD_NUMBER = 4;
  private int vehicle_;
  /**
   * <code>.digitaldelta.v1.VehicleType vehicle = 4;</code>
   * @return The enum numeric value on the wire for vehicle.
   */
  @java.lang.Override
  public int getVehicleValue() {
    return vehicle_;
  }
  /**
   * <code>.digitaldelta.v1.VehicleType vehicle = 4;</code>
   * @return The vehicle.
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.VehicleType getVehicle() {
    me.zayedbinhasan.digitaldelta.proto.VehicleType result = me.zayedbinhasan.digitaldelta.proto.VehicleType.forNumber(vehicle_);
    return result == null ? me.zayedbinhasan.digitaldelta.proto.VehicleType.UNRECOGNIZED : result;
  }
  /**
   * <code>.digitaldelta.v1.VehicleType vehicle = 4;</code>
   * @param value The enum numeric value on the wire for vehicle to set.
   */
  private void setVehicleValue(int value) {
      vehicle_ = value;
  }
  /**
   * <code>.digitaldelta.v1.VehicleType vehicle = 4;</code>
   * @param value The vehicle to set.
   */
  private void setVehicle(me.zayedbinhasan.digitaldelta.proto.VehicleType value) {
    vehicle_ = value.getNumber();

  }
  /**
   * <code>.digitaldelta.v1.VehicleType vehicle = 4;</code>
   */
  private void clearVehicle() {

    vehicle_ = 0;
  }

  public static final int ETA_TIMESTAMP_FIELD_NUMBER = 5;
  private long etaTimestamp_;
  /**
   * <code>int64 eta_timestamp = 5;</code>
   * @return The etaTimestamp.
   */
  @java.lang.Override
  public long getEtaTimestamp() {
    return etaTimestamp_;
  }
  /**
   * <code>int64 eta_timestamp = 5;</code>
   * @param value The etaTimestamp to set.
   */
  private void setEtaTimestamp(long value) {
    
    etaTimestamp_ = value;
  }
  /**
   * <code>int64 eta_timestamp = 5;</code>
   */
  private void clearEtaTimestamp() {

    etaTimestamp_ = 0L;
  }

  public static final int REASON_CODE_FIELD_NUMBER = 6;
  private java.lang.String reasonCode_;
  /**
   * <code>string reason_code = 6;</code>
   * @return The reasonCode.
   */
  @java.lang.Override
  public java.lang.String getReasonCode() {
    return reasonCode_;
  }
  /**
   * <code>string reason_code = 6;</code>
   * @return The bytes for reasonCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReasonCodeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reasonCode_);
  }
  /**
   * <code>string reason_code = 6;</code>
   * @param value The reasonCode to set.
   */
  private void setReasonCode(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    reasonCode_ = value;
  }
  /**
   * <code>string reason_code = 6;</code>
   */
  private void clearReasonCode() {

    reasonCode_ = getDefaultInstance().getReasonCode();
  }
  /**
   * <code>string reason_code = 6;</code>
   * @param value The bytes for reasonCode to set.
   */
  private void setReasonCodeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reasonCode_ = value.toStringUtf8();

  }

  public static final int UPDATED_AT_FIELD_NUMBER = 7;
  private long updatedAt_;
  /**
   * <code>uint64 updated_at = 7;</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public long getUpdatedAt() {
    return updatedAt_;
  }
  /**
   * <code>uint64 updated_at = 7;</code>
   * @param value The updatedAt to set.
   */
  private void setUpdatedAt(long value) {
    
    updatedAt_ = value;
  }
  /**
   * <code>uint64 updated_at = 7;</code>
   */
  private void clearUpdatedAt() {

    updatedAt_ = 0L;
  }

  public static final int VECTOR_CLOCK_FIELD_NUMBER = 8;
  private me.zayedbinhasan.digitaldelta.proto.VectorClock vectorClock_;
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  @java.lang.Override
  public boolean hasVectorClock() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
    return vectorClock_ == null ? me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance() : vectorClock_;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  private void setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  vectorClock_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  if (vectorClock_ != null &&
        vectorClock_ != me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance()) {
      vectorClock_ =
        me.zayedbinhasan.digitaldelta.proto.VectorClock.newBuilder(vectorClock_).mergeFrom(value).buildPartial();
    } else {
      vectorClock_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  private void clearVectorClock() {  vectorClock_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static me.zayedbinhasan.digitaldelta.proto.Route parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Route parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Route parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Route parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Route parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Route parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Route parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Route parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.Route parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.Route parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Route parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.Route parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.Route prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.Route}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.Route, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.Route)
      me.zayedbinhasan.digitaldelta.proto.RouteOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.Route.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string route_id = 1;</code>
     * @return The routeId.
     */
    @java.lang.Override
    public java.lang.String getRouteId() {
      return instance.getRouteId();
    }
    /**
     * <code>string route_id = 1;</code>
     * @return The bytes for routeId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRouteIdBytes() {
      return instance.getRouteIdBytes();
    }
    /**
     * <code>string route_id = 1;</code>
     * @param value The routeId to set.
     * @return This builder for chaining.
     */
    public Builder setRouteId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRouteId(value);
      return this;
    }
    /**
     * <code>string route_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRouteId() {
      copyOnWrite();
      instance.clearRouteId();
      return this;
    }
    /**
     * <code>string route_id = 1;</code>
     * @param value The bytes for routeId to set.
     * @return This builder for chaining.
     */
    public Builder setRouteIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRouteIdBytes(value);
      return this;
    }

    /**
     * <code>repeated string edge_ids = 2;</code>
     * @return A list containing the edgeIds.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getEdgeIdsList() {
      return java.util.Collections.unmodifiableList(
          instance.getEdgeIdsList());
    }
    /**
     * <code>repeated string edge_ids = 2;</code>
     * @return The count of edgeIds.
     */
    @java.lang.Override
    public int getEdgeIdsCount() {
      return instance.getEdgeIdsCount();
    }
    /**
     * <code>repeated string edge_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The edgeIds at the given index.
     */
    @java.lang.Override
    public java.lang.String getEdgeIds(int index) {
      return instance.getEdgeIds(index);
    }
    /**
     * <code>repeated string edge_ids = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the edgeIds at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEdgeIdsBytes(int index) {
      return instance.getEdgeIdsBytes(index);
    }
    /**
     * <code>repeated string edge_ids = 2;</code>
     * @param index The index to set the value at.
     * @param value The edgeIds to set.
     * @return This builder for chaining.
     */
    public Builder setEdgeIds(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setEdgeIds(index, value);
      return this;
    }
    /**
     * <code>repeated string edge_ids = 2;</code>
     * @param value The edgeIds to add.
     * @return This builder for chaining.
     */
    public Builder addEdgeIds(
        java.lang.String value) {
      copyOnWrite();
      instance.addEdgeIds(value);
      return this;
    }
    /**
     * <code>repeated string edge_ids = 2;</code>
     * @param values The edgeIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllEdgeIds(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllEdgeIds(values);
      return this;
    }
    /**
     * <code>repeated string edge_ids = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEdgeIds() {
      copyOnWrite();
      instance.clearEdgeIds();
      return this;
    }
    /**
     * <code>repeated string edge_ids = 2;</code>
     * @param value The bytes of the edgeIds to add.
     * @return This builder for chaining.
     */
    public Builder addEdgeIdsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addEdgeIdsBytes(value);
      return this;
    }

    /**
     * <code>int32 total_duration_mins = 3;</code>
     * @return The totalDurationMins.
     */
    @java.lang.Override
    public int getTotalDurationMins() {
      return instance.getTotalDurationMins();
    }
    /**
     * <code>int32 total_duration_mins = 3;</code>
     * @param value The totalDurationMins to set.
     * @return This builder for chaining.
     */
    public Builder setTotalDurationMins(int value) {
      copyOnWrite();
      instance.setTotalDurationMins(value);
      return this;
    }
    /**
     * <code>int32 total_duration_mins = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalDurationMins() {
      copyOnWrite();
      instance.clearTotalDurationMins();
      return this;
    }

    /**
     * <code>.digitaldelta.v1.VehicleType vehicle = 4;</code>
     * @return The enum numeric value on the wire for vehicle.
     */
    @java.lang.Override
    public int getVehicleValue() {
      return instance.getVehicleValue();
    }
    /**
     * <code>.digitaldelta.v1.VehicleType vehicle = 4;</code>
     * @param value The vehicle to set.
     * @return This builder for chaining.
     */
    public Builder setVehicleValue(int value) {
      copyOnWrite();
      instance.setVehicleValue(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VehicleType vehicle = 4;</code>
     * @return The vehicle.
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.VehicleType getVehicle() {
      return instance.getVehicle();
    }
    /**
     * <code>.digitaldelta.v1.VehicleType vehicle = 4;</code>
     * @param value The enum numeric value on the wire for vehicle to set.
     * @return This builder for chaining.
     */
    public Builder setVehicle(me.zayedbinhasan.digitaldelta.proto.VehicleType value) {
      copyOnWrite();
      instance.setVehicle(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VehicleType vehicle = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVehicle() {
      copyOnWrite();
      instance.clearVehicle();
      return this;
    }

    /**
     * <code>int64 eta_timestamp = 5;</code>
     * @return The etaTimestamp.
     */
    @java.lang.Override
    public long getEtaTimestamp() {
      return instance.getEtaTimestamp();
    }
    /**
     * <code>int64 eta_timestamp = 5;</code>
     * @param value The etaTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setEtaTimestamp(long value) {
      copyOnWrite();
      instance.setEtaTimestamp(value);
      return this;
    }
    /**
     * <code>int64 eta_timestamp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEtaTimestamp() {
      copyOnWrite();
      instance.clearEtaTimestamp();
      return this;
    }

    /**
     * <code>string reason_code = 6;</code>
     * @return The reasonCode.
     */
    @java.lang.Override
    public java.lang.String getReasonCode() {
      return instance.getReasonCode();
    }
    /**
     * <code>string reason_code = 6;</code>
     * @return The bytes for reasonCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonCodeBytes() {
      return instance.getReasonCodeBytes();
    }
    /**
     * <code>string reason_code = 6;</code>
     * @param value The reasonCode to set.
     * @return This builder for chaining.
     */
    public Builder setReasonCode(
        java.lang.String value) {
      copyOnWrite();
      instance.setReasonCode(value);
      return this;
    }
    /**
     * <code>string reason_code = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearReasonCode() {
      copyOnWrite();
      instance.clearReasonCode();
      return this;
    }
    /**
     * <code>string reason_code = 6;</code>
     * @param value The bytes for reasonCode to set.
     * @return This builder for chaining.
     */
    public Builder setReasonCodeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReasonCodeBytes(value);
      return this;
    }

    /**
     * <code>uint64 updated_at = 7;</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public long getUpdatedAt() {
      return instance.getUpdatedAt();
    }
    /**
     * <code>uint64 updated_at = 7;</code>
     * @param value The updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAt(long value) {
      copyOnWrite();
      instance.setUpdatedAt(value);
      return this;
    }
    /**
     * <code>uint64 updated_at = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedAt() {
      copyOnWrite();
      instance.clearUpdatedAt();
      return this;
    }

    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    @java.lang.Override
    public boolean hasVectorClock() {
      return instance.hasVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
      return instance.getVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    public Builder setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.setVectorClock(value);
      return this;
      }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    public Builder setVectorClock(
        me.zayedbinhasan.digitaldelta.proto.VectorClock.Builder builderForValue) {
      copyOnWrite();
      instance.setVectorClock(builderForValue.build());
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    public Builder mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.mergeVectorClock(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    public Builder clearVectorClock() {  copyOnWrite();
      instance.clearVectorClock();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.Route)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.Route();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "routeId_",
            "edgeIds_",
            "totalDurationMins_",
            "vehicle_",
            "etaTimestamp_",
            "reasonCode_",
            "updatedAt_",
            "vectorClock_",
          };
          java.lang.String info =
              "\u0000\b\u0000\u0001\u0001\b\b\u0000\u0001\u0000\u0001\u0208\u0002\u021a\u0003\u0004" +
              "\u0004\f\u0005\u0002\u0006\u0208\u0007\u0003\b\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.Route> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.Route.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.Route>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.Route)
  private static final me.zayedbinhasan.digitaldelta.proto.Route DEFAULT_INSTANCE;
  static {
    Route defaultInstance = new Route();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Route.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.Route getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Route> PARSER;

  public static com.google.protobuf.Parser<Route> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

