// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inventory.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.SupplyItem}
 */
public  final class SupplyItem extends
    com.google.protobuf.GeneratedMessageLite<
        SupplyItem, SupplyItem.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.SupplyItem)
    SupplyItemOrBuilder {
  private SupplyItem() {
    itemId_ = "";
    name_ = "";
    locationId_ = "";
  }
  private int bitField0_;
  public static final int ITEM_ID_FIELD_NUMBER = 1;
  private java.lang.String itemId_;
  /**
   * <code>string item_id = 1;</code>
   * @return The itemId.
   */
  @java.lang.Override
  public java.lang.String getItemId() {
    return itemId_;
  }
  /**
   * <code>string item_id = 1;</code>
   * @return The bytes for itemId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getItemIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(itemId_);
  }
  /**
   * <code>string item_id = 1;</code>
   * @param value The itemId to set.
   */
  private void setItemId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    itemId_ = value;
  }
  /**
   * <code>string item_id = 1;</code>
   */
  private void clearItemId() {

    itemId_ = getDefaultInstance().getItemId();
  }
  /**
   * <code>string item_id = 1;</code>
   * @param value The bytes for itemId to set.
   */
  private void setItemIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    itemId_ = value.toStringUtf8();

  }

  public static final int NAME_FIELD_NUMBER = 2;
  private java.lang.String name_;
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 2;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <code>string name = 2;</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 2;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static final int CATEGORY_FIELD_NUMBER = 3;
  private int category_;
  /**
   * <code>.digitaldelta.v1.SupplyCategory category = 3;</code>
   * @return The enum numeric value on the wire for category.
   */
  @java.lang.Override
  public int getCategoryValue() {
    return category_;
  }
  /**
   * <code>.digitaldelta.v1.SupplyCategory category = 3;</code>
   * @return The category.
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.SupplyCategory getCategory() {
    me.zayedbinhasan.digitaldelta.proto.SupplyCategory result = me.zayedbinhasan.digitaldelta.proto.SupplyCategory.forNumber(category_);
    return result == null ? me.zayedbinhasan.digitaldelta.proto.SupplyCategory.UNRECOGNIZED : result;
  }
  /**
   * <code>.digitaldelta.v1.SupplyCategory category = 3;</code>
   * @param value The enum numeric value on the wire for category to set.
   */
  private void setCategoryValue(int value) {
      category_ = value;
  }
  /**
   * <code>.digitaldelta.v1.SupplyCategory category = 3;</code>
   * @param value The category to set.
   */
  private void setCategory(me.zayedbinhasan.digitaldelta.proto.SupplyCategory value) {
    category_ = value.getNumber();

  }
  /**
   * <code>.digitaldelta.v1.SupplyCategory category = 3;</code>
   */
  private void clearCategory() {

    category_ = 0;
  }

  public static final int QUANTITY_FIELD_NUMBER = 4;
  private int quantity_;
  /**
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }
  /**
   * <code>int32 quantity = 4;</code>
   * @param value The quantity to set.
   */
  private void setQuantity(int value) {
    
    quantity_ = value;
  }
  /**
   * <code>int32 quantity = 4;</code>
   */
  private void clearQuantity() {

    quantity_ = 0;
  }

  public static final int PRIORITY_FIELD_NUMBER = 5;
  private int priority_;
  /**
   * <code>int32 priority = 5;</code>
   * @return The priority.
   */
  @java.lang.Override
  public int getPriority() {
    return priority_;
  }
  /**
   * <code>int32 priority = 5;</code>
   * @param value The priority to set.
   */
  private void setPriority(int value) {
    
    priority_ = value;
  }
  /**
   * <code>int32 priority = 5;</code>
   */
  private void clearPriority() {

    priority_ = 0;
  }

  public static final int LOCATION_ID_FIELD_NUMBER = 6;
  private java.lang.String locationId_;
  /**
   * <code>string location_id = 6;</code>
   * @return The locationId.
   */
  @java.lang.Override
  public java.lang.String getLocationId() {
    return locationId_;
  }
  /**
   * <code>string location_id = 6;</code>
   * @return The bytes for locationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocationIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(locationId_);
  }
  /**
   * <code>string location_id = 6;</code>
   * @param value The locationId to set.
   */
  private void setLocationId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    locationId_ = value;
  }
  /**
   * <code>string location_id = 6;</code>
   */
  private void clearLocationId() {

    locationId_ = getDefaultInstance().getLocationId();
  }
  /**
   * <code>string location_id = 6;</code>
   * @param value The bytes for locationId to set.
   */
  private void setLocationIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    locationId_ = value.toStringUtf8();

  }

  public static final int LAST_UPDATED_FIELD_NUMBER = 7;
  private long lastUpdated_;
  /**
   * <code>uint64 last_updated = 7;</code>
   * @return The lastUpdated.
   */
  @java.lang.Override
  public long getLastUpdated() {
    return lastUpdated_;
  }
  /**
   * <code>uint64 last_updated = 7;</code>
   * @param value The lastUpdated to set.
   */
  private void setLastUpdated(long value) {
    
    lastUpdated_ = value;
  }
  /**
   * <code>uint64 last_updated = 7;</code>
   */
  private void clearLastUpdated() {

    lastUpdated_ = 0L;
  }

  public static final int VECTOR_CLOCK_FIELD_NUMBER = 8;
  private me.zayedbinhasan.digitaldelta.proto.VectorClock vectorClock_;
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  @java.lang.Override
  public boolean hasVectorClock() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
    return vectorClock_ == null ? me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance() : vectorClock_;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  private void setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  vectorClock_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
    value.getClass();
  if (vectorClock_ != null &&
        vectorClock_ != me.zayedbinhasan.digitaldelta.proto.VectorClock.getDefaultInstance()) {
      vectorClock_ =
        me.zayedbinhasan.digitaldelta.proto.VectorClock.newBuilder(vectorClock_).mergeFrom(value).buildPartial();
    } else {
      vectorClock_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   */
  private void clearVectorClock() {  vectorClock_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.SupplyItem prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.SupplyItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.SupplyItem, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.SupplyItem)
      me.zayedbinhasan.digitaldelta.proto.SupplyItemOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.SupplyItem.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string item_id = 1;</code>
     * @return The itemId.
     */
    @java.lang.Override
    public java.lang.String getItemId() {
      return instance.getItemId();
    }
    /**
     * <code>string item_id = 1;</code>
     * @return The bytes for itemId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getItemIdBytes() {
      return instance.getItemIdBytes();
    }
    /**
     * <code>string item_id = 1;</code>
     * @param value The itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemId(
        java.lang.String value) {
      copyOnWrite();
      instance.setItemId(value);
      return this;
    }
    /**
     * <code>string item_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearItemId() {
      copyOnWrite();
      instance.clearItemId();
      return this;
    }
    /**
     * <code>string item_id = 1;</code>
     * @param value The bytes for itemId to set.
     * @return This builder for chaining.
     */
    public Builder setItemIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setItemIdBytes(value);
      return this;
    }

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>.digitaldelta.v1.SupplyCategory category = 3;</code>
     * @return The enum numeric value on the wire for category.
     */
    @java.lang.Override
    public int getCategoryValue() {
      return instance.getCategoryValue();
    }
    /**
     * <code>.digitaldelta.v1.SupplyCategory category = 3;</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryValue(int value) {
      copyOnWrite();
      instance.setCategoryValue(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.SupplyCategory category = 3;</code>
     * @return The category.
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.SupplyCategory getCategory() {
      return instance.getCategory();
    }
    /**
     * <code>.digitaldelta.v1.SupplyCategory category = 3;</code>
     * @param value The enum numeric value on the wire for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(me.zayedbinhasan.digitaldelta.proto.SupplyCategory value) {
      copyOnWrite();
      instance.setCategory(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.SupplyCategory category = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      copyOnWrite();
      instance.clearCategory();
      return this;
    }

    /**
     * <code>int32 quantity = 4;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return instance.getQuantity();
    }
    /**
     * <code>int32 quantity = 4;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      copyOnWrite();
      instance.setQuantity(value);
      return this;
    }
    /**
     * <code>int32 quantity = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      copyOnWrite();
      instance.clearQuantity();
      return this;
    }

    /**
     * <code>int32 priority = 5;</code>
     * @return The priority.
     */
    @java.lang.Override
    public int getPriority() {
      return instance.getPriority();
    }
    /**
     * <code>int32 priority = 5;</code>
     * @param value The priority to set.
     * @return This builder for chaining.
     */
    public Builder setPriority(int value) {
      copyOnWrite();
      instance.setPriority(value);
      return this;
    }
    /**
     * <code>int32 priority = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPriority() {
      copyOnWrite();
      instance.clearPriority();
      return this;
    }

    /**
     * <code>string location_id = 6;</code>
     * @return The locationId.
     */
    @java.lang.Override
    public java.lang.String getLocationId() {
      return instance.getLocationId();
    }
    /**
     * <code>string location_id = 6;</code>
     * @return The bytes for locationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocationIdBytes() {
      return instance.getLocationIdBytes();
    }
    /**
     * <code>string location_id = 6;</code>
     * @param value The locationId to set.
     * @return This builder for chaining.
     */
    public Builder setLocationId(
        java.lang.String value) {
      copyOnWrite();
      instance.setLocationId(value);
      return this;
    }
    /**
     * <code>string location_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocationId() {
      copyOnWrite();
      instance.clearLocationId();
      return this;
    }
    /**
     * <code>string location_id = 6;</code>
     * @param value The bytes for locationId to set.
     * @return This builder for chaining.
     */
    public Builder setLocationIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLocationIdBytes(value);
      return this;
    }

    /**
     * <code>uint64 last_updated = 7;</code>
     * @return The lastUpdated.
     */
    @java.lang.Override
    public long getLastUpdated() {
      return instance.getLastUpdated();
    }
    /**
     * <code>uint64 last_updated = 7;</code>
     * @param value The lastUpdated to set.
     * @return This builder for chaining.
     */
    public Builder setLastUpdated(long value) {
      copyOnWrite();
      instance.setLastUpdated(value);
      return this;
    }
    /**
     * <code>uint64 last_updated = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastUpdated() {
      copyOnWrite();
      instance.clearLastUpdated();
      return this;
    }

    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    @java.lang.Override
    public boolean hasVectorClock() {
      return instance.hasVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock() {
      return instance.getVectorClock();
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    public Builder setVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.setVectorClock(value);
      return this;
      }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    public Builder setVectorClock(
        me.zayedbinhasan.digitaldelta.proto.VectorClock.Builder builderForValue) {
      copyOnWrite();
      instance.setVectorClock(builderForValue.build());
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    public Builder mergeVectorClock(me.zayedbinhasan.digitaldelta.proto.VectorClock value) {
      copyOnWrite();
      instance.mergeVectorClock(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
     */
    public Builder clearVectorClock() {  copyOnWrite();
      instance.clearVectorClock();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.SupplyItem)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.SupplyItem();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "itemId_",
            "name_",
            "category_",
            "quantity_",
            "priority_",
            "locationId_",
            "lastUpdated_",
            "vectorClock_",
          };
          java.lang.String info =
              "\u0000\b\u0000\u0001\u0001\b\b\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\f" +
              "\u0004\u0004\u0005\u0004\u0006\u0208\u0007\u0003\b\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.SupplyItem> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.SupplyItem.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.SupplyItem>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.SupplyItem)
  private static final me.zayedbinhasan.digitaldelta.proto.SupplyItem DEFAULT_INSTANCE;
  static {
    SupplyItem defaultInstance = new SupplyItem();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SupplyItem.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.SupplyItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SupplyItem> PARSER;

  public static com.google.protobuf.Parser<SupplyItem> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

