// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: inventory.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

public interface SupplyItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:digitaldelta.v1.SupplyItem)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string item_id = 1;</code>
   * @return The itemId.
   */
  java.lang.String getItemId();
  /**
   * <code>string item_id = 1;</code>
   * @return The bytes for itemId.
   */
  com.google.protobuf.ByteString
      getItemIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.digitaldelta.v1.SupplyCategory category = 3;</code>
   * @return The enum numeric value on the wire for category.
   */
  int getCategoryValue();
  /**
   * <code>.digitaldelta.v1.SupplyCategory category = 3;</code>
   * @return The category.
   */
  me.zayedbinhasan.digitaldelta.proto.SupplyCategory getCategory();

  /**
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <code>int32 priority = 5;</code>
   * @return The priority.
   */
  int getPriority();

  /**
   * <code>string location_id = 6;</code>
   * @return The locationId.
   */
  java.lang.String getLocationId();
  /**
   * <code>string location_id = 6;</code>
   * @return The bytes for locationId.
   */
  com.google.protobuf.ByteString
      getLocationIdBytes();

  /**
   * <code>uint64 last_updated = 7;</code>
   * @return The lastUpdated.
   */
  long getLastUpdated();

  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   * @return Whether the vectorClock field is set.
   */
  boolean hasVectorClock();
  /**
   * <code>.digitaldelta.v1.VectorClock vector_clock = 8;</code>
   * @return The vectorClock.
   */
  me.zayedbinhasan.digitaldelta.proto.VectorClock getVectorClock();
}
