// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.SyncCheckpoint}
 */
public  final class SyncCheckpoint extends
    com.google.protobuf.GeneratedMessageLite<
        SyncCheckpoint, SyncCheckpoint.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.SyncCheckpoint)
    SyncCheckpointOrBuilder {
  private SyncCheckpoint() {
  }
  public static final int LAST_SEEN_COUNTER_BY_DEVICE_FIELD_NUMBER = 1;
  private static final class LastSeenCounterByDeviceDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.UINT64,
                0L);
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, java.lang.Long> lastSeenCounterByDevice_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Long>
  internalGetLastSeenCounterByDevice() {
    return lastSeenCounterByDevice_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Long>
  internalGetMutableLastSeenCounterByDevice() {
    if (!lastSeenCounterByDevice_.isMutable()) {
      lastSeenCounterByDevice_ = lastSeenCounterByDevice_.mutableCopy();
    }
    return lastSeenCounterByDevice_;
  }
  @java.lang.Override

  public int getLastSeenCounterByDeviceCount() {
    return internalGetLastSeenCounterByDevice().size();
  }
  /**
   * <code>map&lt;string, uint64&gt; last_seen_counter_by_device = 1;</code>
   */
  @java.lang.Override

  public boolean containsLastSeenCounterByDevice(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    return internalGetLastSeenCounterByDevice().containsKey(key);
  }
  /**
   * Use {@link #getLastSeenCounterByDeviceMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getLastSeenCounterByDevice() {
    return getLastSeenCounterByDeviceMap();
  }
  /**
   * <code>map&lt;string, uint64&gt; last_seen_counter_by_device = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.Long> getLastSeenCounterByDeviceMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetLastSeenCounterByDevice());
  }
  /**
   * <code>map&lt;string, uint64&gt; last_seen_counter_by_device = 1;</code>
   */
  @java.lang.Override

  public long getLastSeenCounterByDeviceOrDefault(
      java.lang.String key,
      long defaultValue) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetLastSeenCounterByDevice();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, uint64&gt; last_seen_counter_by_device = 1;</code>
   */
  @java.lang.Override

  public long getLastSeenCounterByDeviceOrThrow(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetLastSeenCounterByDevice();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   * <code>map&lt;string, uint64&gt; last_seen_counter_by_device = 1;</code>
   */
  private java.util.Map<java.lang.String, java.lang.Long>
  getMutableLastSeenCounterByDeviceMap() {
    return internalGetMutableLastSeenCounterByDevice();
  }

  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.SyncCheckpoint}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.SyncCheckpoint)
      me.zayedbinhasan.digitaldelta.proto.SyncCheckpointOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    @java.lang.Override

    public int getLastSeenCounterByDeviceCount() {
      return instance.getLastSeenCounterByDeviceMap().size();
    }
    /**
     * <code>map&lt;string, uint64&gt; last_seen_counter_by_device = 1;</code>
     */
    @java.lang.Override

    public boolean containsLastSeenCounterByDevice(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return instance.getLastSeenCounterByDeviceMap().containsKey(key);
    }

    public Builder clearLastSeenCounterByDevice() {
      copyOnWrite();
      instance.getMutableLastSeenCounterByDeviceMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, uint64&gt; last_seen_counter_by_device = 1;</code>
     */

    public Builder removeLastSeenCounterByDevice(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      copyOnWrite();
      instance.getMutableLastSeenCounterByDeviceMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getLastSeenCounterByDeviceMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getLastSeenCounterByDevice() {
      return getLastSeenCounterByDeviceMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; last_seen_counter_by_device = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Long> getLastSeenCounterByDeviceMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getLastSeenCounterByDeviceMap());
    }
    /**
     * <code>map&lt;string, uint64&gt; last_seen_counter_by_device = 1;</code>
     */
    @java.lang.Override

    public long getLastSeenCounterByDeviceOrDefault(
        java.lang.String key,
        long defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.Long> map =
          instance.getLastSeenCounterByDeviceMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, uint64&gt; last_seen_counter_by_device = 1;</code>
     */
    @java.lang.Override

    public long getLastSeenCounterByDeviceOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.Long> map =
          instance.getLastSeenCounterByDeviceMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, uint64&gt; last_seen_counter_by_device = 1;</code>
     */
    public Builder putLastSeenCounterByDevice(
        java.lang.String key,
        long value) {
      java.lang.Class<?> keyClass = key.getClass();

      copyOnWrite();
      instance.getMutableLastSeenCounterByDeviceMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, uint64&gt; last_seen_counter_by_device = 1;</code>
     */
    public Builder putAllLastSeenCounterByDevice(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      copyOnWrite();
      instance.getMutableLastSeenCounterByDeviceMap().putAll(values);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.SyncCheckpoint)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "lastSeenCounterByDevice_",
            LastSeenCounterByDeviceDefaultEntryHolder.defaultEntry,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u00012";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.SyncCheckpoint)
  private static final me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint DEFAULT_INSTANCE;
  static {
    SyncCheckpoint defaultInstance = new SyncCheckpoint();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SyncCheckpoint.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.SyncCheckpoint getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SyncCheckpoint> PARSER;

  public static com.google.protobuf.Parser<SyncCheckpoint> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

