// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: auth.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.UserIdentity}
 */
public  final class UserIdentity extends
    com.google.protobuf.GeneratedMessageLite<
        UserIdentity, UserIdentity.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.UserIdentity)
    UserIdentityOrBuilder {
  private UserIdentity() {
    userId_ = "";
    displayName_ = "";
    publicKey_ = "";
  }
  public static final int USER_ID_FIELD_NUMBER = 1;
  private java.lang.String userId_;
  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    return userId_;
  }
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(userId_);
  }
  /**
   * <code>string user_id = 1;</code>
   * @param value The userId to set.
   */
  private void setUserId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    userId_ = value;
  }
  /**
   * <code>string user_id = 1;</code>
   */
  private void clearUserId() {

    userId_ = getDefaultInstance().getUserId();
  }
  /**
   * <code>string user_id = 1;</code>
   * @param value The bytes for userId to set.
   */
  private void setUserIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    userId_ = value.toStringUtf8();

  }

  public static final int DISPLAY_NAME_FIELD_NUMBER = 2;
  private java.lang.String displayName_;
  /**
   * <code>string display_name = 2;</code>
   * @return The displayName.
   */
  @java.lang.Override
  public java.lang.String getDisplayName() {
    return displayName_;
  }
  /**
   * <code>string display_name = 2;</code>
   * @return The bytes for displayName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDisplayNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(displayName_);
  }
  /**
   * <code>string display_name = 2;</code>
   * @param value The displayName to set.
   */
  private void setDisplayName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    displayName_ = value;
  }
  /**
   * <code>string display_name = 2;</code>
   */
  private void clearDisplayName() {

    displayName_ = getDefaultInstance().getDisplayName();
  }
  /**
   * <code>string display_name = 2;</code>
   * @param value The bytes for displayName to set.
   */
  private void setDisplayNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    displayName_ = value.toStringUtf8();

  }

  public static final int ROLE_FIELD_NUMBER = 3;
  private int role_;
  /**
   * <code>.digitaldelta.v1.UserRole role = 3;</code>
   * @return The enum numeric value on the wire for role.
   */
  @java.lang.Override
  public int getRoleValue() {
    return role_;
  }
  /**
   * <code>.digitaldelta.v1.UserRole role = 3;</code>
   * @return The role.
   */
  @java.lang.Override
  public me.zayedbinhasan.digitaldelta.proto.UserRole getRole() {
    me.zayedbinhasan.digitaldelta.proto.UserRole result = me.zayedbinhasan.digitaldelta.proto.UserRole.forNumber(role_);
    return result == null ? me.zayedbinhasan.digitaldelta.proto.UserRole.UNRECOGNIZED : result;
  }
  /**
   * <code>.digitaldelta.v1.UserRole role = 3;</code>
   * @param value The enum numeric value on the wire for role to set.
   */
  private void setRoleValue(int value) {
      role_ = value;
  }
  /**
   * <code>.digitaldelta.v1.UserRole role = 3;</code>
   * @param value The role to set.
   */
  private void setRole(me.zayedbinhasan.digitaldelta.proto.UserRole value) {
    role_ = value.getNumber();

  }
  /**
   * <code>.digitaldelta.v1.UserRole role = 3;</code>
   */
  private void clearRole() {

    role_ = 0;
  }

  public static final int PUBLIC_KEY_FIELD_NUMBER = 4;
  private java.lang.String publicKey_;
  /**
   * <code>string public_key = 4;</code>
   * @return The publicKey.
   */
  @java.lang.Override
  public java.lang.String getPublicKey() {
    return publicKey_;
  }
  /**
   * <code>string public_key = 4;</code>
   * @return The bytes for publicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPublicKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(publicKey_);
  }
  /**
   * <code>string public_key = 4;</code>
   * @param value The publicKey to set.
   */
  private void setPublicKey(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    publicKey_ = value;
  }
  /**
   * <code>string public_key = 4;</code>
   */
  private void clearPublicKey() {

    publicKey_ = getDefaultInstance().getPublicKey();
  }
  /**
   * <code>string public_key = 4;</code>
   * @param value The bytes for publicKey to set.
   */
  private void setPublicKeyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    publicKey_ = value.toStringUtf8();

  }

  public static final int CREATED_AT_FIELD_NUMBER = 5;
  private long createdAt_;
  /**
   * <code>uint64 created_at = 5;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public long getCreatedAt() {
    return createdAt_;
  }
  /**
   * <code>uint64 created_at = 5;</code>
   * @param value The createdAt to set.
   */
  private void setCreatedAt(long value) {
    
    createdAt_ = value;
  }
  /**
   * <code>uint64 created_at = 5;</code>
   */
  private void clearCreatedAt() {

    createdAt_ = 0L;
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 6;
  private long updatedAt_;
  /**
   * <code>uint64 updated_at = 6;</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public long getUpdatedAt() {
    return updatedAt_;
  }
  /**
   * <code>uint64 updated_at = 6;</code>
   * @param value The updatedAt to set.
   */
  private void setUpdatedAt(long value) {
    
    updatedAt_ = value;
  }
  /**
   * <code>uint64 updated_at = 6;</code>
   */
  private void clearUpdatedAt() {

    updatedAt_ = 0L;
  }

  public static final int ACTIVE_FIELD_NUMBER = 7;
  private boolean active_;
  /**
   * <code>bool active = 7;</code>
   * @return The active.
   */
  @java.lang.Override
  public boolean getActive() {
    return active_;
  }
  /**
   * <code>bool active = 7;</code>
   * @param value The active to set.
   */
  private void setActive(boolean value) {
    
    active_ = value;
  }
  /**
   * <code>bool active = 7;</code>
   */
  private void clearActive() {

    active_ = false;
  }

  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.UserIdentity prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.UserIdentity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.UserIdentity, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.UserIdentity)
      me.zayedbinhasan.digitaldelta.proto.UserIdentityOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.UserIdentity.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      return instance.getUserId();
    }
    /**
     * <code>string user_id = 1;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      return instance.getUserIdBytes();
    }
    /**
     * <code>string user_id = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      copyOnWrite();
      instance.setUserId(value);
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      copyOnWrite();
      instance.clearUserId();
      return this;
    }
    /**
     * <code>string user_id = 1;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUserIdBytes(value);
      return this;
    }

    /**
     * <code>string display_name = 2;</code>
     * @return The displayName.
     */
    @java.lang.Override
    public java.lang.String getDisplayName() {
      return instance.getDisplayName();
    }
    /**
     * <code>string display_name = 2;</code>
     * @return The bytes for displayName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      return instance.getDisplayNameBytes();
    }
    /**
     * <code>string display_name = 2;</code>
     * @param value The displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayName(
        java.lang.String value) {
      copyOnWrite();
      instance.setDisplayName(value);
      return this;
    }
    /**
     * <code>string display_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayName() {
      copyOnWrite();
      instance.clearDisplayName();
      return this;
    }
    /**
     * <code>string display_name = 2;</code>
     * @param value The bytes for displayName to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDisplayNameBytes(value);
      return this;
    }

    /**
     * <code>.digitaldelta.v1.UserRole role = 3;</code>
     * @return The enum numeric value on the wire for role.
     */
    @java.lang.Override
    public int getRoleValue() {
      return instance.getRoleValue();
    }
    /**
     * <code>.digitaldelta.v1.UserRole role = 3;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleValue(int value) {
      copyOnWrite();
      instance.setRoleValue(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.UserRole role = 3;</code>
     * @return The role.
     */
    @java.lang.Override
    public me.zayedbinhasan.digitaldelta.proto.UserRole getRole() {
      return instance.getRole();
    }
    /**
     * <code>.digitaldelta.v1.UserRole role = 3;</code>
     * @param value The enum numeric value on the wire for role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(me.zayedbinhasan.digitaldelta.proto.UserRole value) {
      copyOnWrite();
      instance.setRole(value);
      return this;
    }
    /**
     * <code>.digitaldelta.v1.UserRole role = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {
      copyOnWrite();
      instance.clearRole();
      return this;
    }

    /**
     * <code>string public_key = 4;</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public java.lang.String getPublicKey() {
      return instance.getPublicKey();
    }
    /**
     * <code>string public_key = 4;</code>
     * @return The bytes for publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPublicKeyBytes() {
      return instance.getPublicKeyBytes();
    }
    /**
     * <code>string public_key = 4;</code>
     * @param value The publicKey to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setPublicKey(value);
      return this;
    }
    /**
     * <code>string public_key = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicKey() {
      copyOnWrite();
      instance.clearPublicKey();
      return this;
    }
    /**
     * <code>string public_key = 4;</code>
     * @param value The bytes for publicKey to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPublicKeyBytes(value);
      return this;
    }

    /**
     * <code>uint64 created_at = 5;</code>
     * @return The createdAt.
     */
    @java.lang.Override
    public long getCreatedAt() {
      return instance.getCreatedAt();
    }
    /**
     * <code>uint64 created_at = 5;</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(long value) {
      copyOnWrite();
      instance.setCreatedAt(value);
      return this;
    }
    /**
     * <code>uint64 created_at = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      copyOnWrite();
      instance.clearCreatedAt();
      return this;
    }

    /**
     * <code>uint64 updated_at = 6;</code>
     * @return The updatedAt.
     */
    @java.lang.Override
    public long getUpdatedAt() {
      return instance.getUpdatedAt();
    }
    /**
     * <code>uint64 updated_at = 6;</code>
     * @param value The updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAt(long value) {
      copyOnWrite();
      instance.setUpdatedAt(value);
      return this;
    }
    /**
     * <code>uint64 updated_at = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedAt() {
      copyOnWrite();
      instance.clearUpdatedAt();
      return this;
    }

    /**
     * <code>bool active = 7;</code>
     * @return The active.
     */
    @java.lang.Override
    public boolean getActive() {
      return instance.getActive();
    }
    /**
     * <code>bool active = 7;</code>
     * @param value The active to set.
     * @return This builder for chaining.
     */
    public Builder setActive(boolean value) {
      copyOnWrite();
      instance.setActive(value);
      return this;
    }
    /**
     * <code>bool active = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearActive() {
      copyOnWrite();
      instance.clearActive();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.UserIdentity)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.UserIdentity();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "userId_",
            "displayName_",
            "role_",
            "publicKey_",
            "createdAt_",
            "updatedAt_",
            "active_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\f\u0004\u0208\u0005\u0003\u0006\u0003\u0007\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.UserIdentity> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.UserIdentity.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.UserIdentity>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.UserIdentity)
  private static final me.zayedbinhasan.digitaldelta.proto.UserIdentity DEFAULT_INSTANCE;
  static {
    UserIdentity defaultInstance = new UserIdentity();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserIdentity.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.UserIdentity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserIdentity> PARSER;

  public static com.google.protobuf.Parser<UserIdentity> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

