// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf type {@code digitaldelta.v1.VectorClock}
 */
public  final class VectorClock extends
    com.google.protobuf.GeneratedMessageLite<
        VectorClock, VectorClock.Builder> implements
    // @@protoc_insertion_point(message_implements:digitaldelta.v1.VectorClock)
    VectorClockOrBuilder {
  private VectorClock() {
  }
  public static final int COUNTERS_FIELD_NUMBER = 1;
  private static final class CountersDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        java.lang.String, java.lang.Long> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<java.lang.String, java.lang.Long>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.UINT64,
                0L);
  }
  private com.google.protobuf.MapFieldLite<
      java.lang.String, java.lang.Long> counters_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Long>
  internalGetCounters() {
    return counters_;
  }
  private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Long>
  internalGetMutableCounters() {
    if (!counters_.isMutable()) {
      counters_ = counters_.mutableCopy();
    }
    return counters_;
  }
  @java.lang.Override

  public int getCountersCount() {
    return internalGetCounters().size();
  }
  /**
   * <code>map&lt;string, uint64&gt; counters = 1;</code>
   */
  @java.lang.Override

  public boolean containsCounters(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    return internalGetCounters().containsKey(key);
  }
  /**
   * Use {@link #getCountersMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.Long> getCounters() {
    return getCountersMap();
  }
  /**
   * <code>map&lt;string, uint64&gt; counters = 1;</code>
   */
  @java.lang.Override

  public java.util.Map<java.lang.String, java.lang.Long> getCountersMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetCounters());
  }
  /**
   * <code>map&lt;string, uint64&gt; counters = 1;</code>
   */
  @java.lang.Override

  public long getCountersOrDefault(
      java.lang.String key,
      long defaultValue) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetCounters();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, uint64&gt; counters = 1;</code>
   */
  @java.lang.Override

  public long getCountersOrThrow(
      java.lang.String key) {
    java.lang.Class<?> keyClass = key.getClass();
    java.util.Map<java.lang.String, java.lang.Long> map =
        internalGetCounters();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   * <code>map&lt;string, uint64&gt; counters = 1;</code>
   */
  private java.util.Map<java.lang.String, java.lang.Long>
  getMutableCountersMap() {
    return internalGetMutableCounters();
  }

  public static me.zayedbinhasan.digitaldelta.proto.VectorClock parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.VectorClock parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.VectorClock parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.VectorClock parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.VectorClock parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static me.zayedbinhasan.digitaldelta.proto.VectorClock parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.VectorClock parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.VectorClock parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static me.zayedbinhasan.digitaldelta.proto.VectorClock parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static me.zayedbinhasan.digitaldelta.proto.VectorClock parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static me.zayedbinhasan.digitaldelta.proto.VectorClock parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static me.zayedbinhasan.digitaldelta.proto.VectorClock parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(me.zayedbinhasan.digitaldelta.proto.VectorClock prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code digitaldelta.v1.VectorClock}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        me.zayedbinhasan.digitaldelta.proto.VectorClock, Builder> implements
      // @@protoc_insertion_point(builder_implements:digitaldelta.v1.VectorClock)
      me.zayedbinhasan.digitaldelta.proto.VectorClockOrBuilder {
    // Construct using me.zayedbinhasan.digitaldelta.proto.VectorClock.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    @java.lang.Override

    public int getCountersCount() {
      return instance.getCountersMap().size();
    }
    /**
     * <code>map&lt;string, uint64&gt; counters = 1;</code>
     */
    @java.lang.Override

    public boolean containsCounters(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      return instance.getCountersMap().containsKey(key);
    }

    public Builder clearCounters() {
      copyOnWrite();
      instance.getMutableCountersMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, uint64&gt; counters = 1;</code>
     */

    public Builder removeCounters(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      copyOnWrite();
      instance.getMutableCountersMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getCountersMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getCounters() {
      return getCountersMap();
    }
    /**
     * <code>map&lt;string, uint64&gt; counters = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Long> getCountersMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getCountersMap());
    }
    /**
     * <code>map&lt;string, uint64&gt; counters = 1;</code>
     */
    @java.lang.Override

    public long getCountersOrDefault(
        java.lang.String key,
        long defaultValue) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.Long> map =
          instance.getCountersMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, uint64&gt; counters = 1;</code>
     */
    @java.lang.Override

    public long getCountersOrThrow(
        java.lang.String key) {
      java.lang.Class<?> keyClass = key.getClass();
      java.util.Map<java.lang.String, java.lang.Long> map =
          instance.getCountersMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, uint64&gt; counters = 1;</code>
     */
    public Builder putCounters(
        java.lang.String key,
        long value) {
      java.lang.Class<?> keyClass = key.getClass();

      copyOnWrite();
      instance.getMutableCountersMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, uint64&gt; counters = 1;</code>
     */
    public Builder putAllCounters(
        java.util.Map<java.lang.String, java.lang.Long> values) {
      copyOnWrite();
      instance.getMutableCountersMap().putAll(values);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:digitaldelta.v1.VectorClock)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new me.zayedbinhasan.digitaldelta.proto.VectorClock();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "counters_",
            CountersDefaultEntryHolder.defaultEntry,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u00012";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<me.zayedbinhasan.digitaldelta.proto.VectorClock> parser = PARSER;
        if (parser == null) {
          synchronized (me.zayedbinhasan.digitaldelta.proto.VectorClock.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<me.zayedbinhasan.digitaldelta.proto.VectorClock>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:digitaldelta.v1.VectorClock)
  private static final me.zayedbinhasan.digitaldelta.proto.VectorClock DEFAULT_INSTANCE;
  static {
    VectorClock defaultInstance = new VectorClock();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      VectorClock.class, defaultInstance);
  }

  public static me.zayedbinhasan.digitaldelta.proto.VectorClock getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<VectorClock> PARSER;

  public static com.google.protobuf.Parser<VectorClock> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

