// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: routing.proto
// Protobuf Java Version: 4.28.2

package me.zayedbinhasan.digitaldelta.proto;

/**
 * Protobuf enum {@code digitaldelta.v1.VehicleType}
 */
public enum VehicleType
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>VEHICLE_TYPE_UNSPECIFIED = 0;</code>
   */
  VEHICLE_TYPE_UNSPECIFIED(0),
  /**
   * <code>TRUCK = 1;</code>
   */
  TRUCK(1),
  /**
   * <code>SPEEDBOAT = 2;</code>
   */
  SPEEDBOAT(2),
  /**
   * <code>DRONE = 3;</code>
   */
  DRONE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>VEHICLE_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int VEHICLE_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>TRUCK = 1;</code>
   */
  public static final int TRUCK_VALUE = 1;
  /**
   * <code>SPEEDBOAT = 2;</code>
   */
  public static final int SPEEDBOAT_VALUE = 2;
  /**
   * <code>DRONE = 3;</code>
   */
  public static final int DRONE_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static VehicleType valueOf(int value) {
    return forNumber(value);
  }

  public static VehicleType forNumber(int value) {
    switch (value) {
      case 0: return VEHICLE_TYPE_UNSPECIFIED;
      case 1: return TRUCK;
      case 2: return SPEEDBOAT;
      case 3: return DRONE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<VehicleType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      VehicleType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<VehicleType>() {
          @java.lang.Override
          public VehicleType findValueByNumber(int number) {
            return VehicleType.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return VehicleTypeVerifier.INSTANCE;
  }

  private static final class VehicleTypeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new VehicleTypeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return VehicleType.forNumber(number) != null;
          }
        };

  private final int value;

  private VehicleType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:digitaldelta.v1.VehicleType)
}

